### ISSUE TITLE
问题：goproxy.cn如何支持github私有仓库的拉取？

### ISSUE THREAD

**Issue by zhangshuiyong** [goproxy/goproxy.cn#100]

**Comment by aofei** [comment]
如果你的 Go 版本是 1.13 或更高，那么设置好 GOPROXY=https://goproxy.cn,direct 的同时设置 GOPRIVATE 环境变量就好了，比如 GOPRIVATE=github.com/jonsnow,git.example.com 表示所有以他们为前缀的 module path 都将走 direct 的方式拉取。

**Comment by aofei** [comment]
由于问题已回答，这个 issue 我就先关闭了哈，如果还有其他问题欢迎随时提问。
