### ISSUE TITLE
扩展k8s的ingress-nginx,在build的时候设置代理也无法下载相关包

### ISSUE THREAD

**Issue by Chenpipi** [goproxy/goproxy.cn#101]
## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.15.2 linux/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/code/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/code/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"  or GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/code/go/src/k8s.io/ingress-nginx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build272164749=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## What did you do?

参考如下连接，准备扩展ingress-nginx，但是出现下面的超时错误
ref: https://www.elvinefendi.com/2019/11/22/ingress-nginx-openidc-plugin.html
## What is the behavior of the bug?

[dev-env] building image
go: finding module for package k8s.io/apimachinery/pkg/util/wait
go: finding module for package k8s.io/apimachinery/pkg/api/errors
go: finding module for package k8s.io/api/core/v1
go: finding module for package k8s.io/apimachinery/pkg/version
go: finding module for package k8s.io/klog/v2
go: finding module for package k8s.io/apiserver/pkg/server/healthz
go: finding module for package k8s.io/client-go/rest
go: finding module for package github.com/prometheus/client_golang/prometheus/promhttp
go: finding module for package k8s.io/apimachinery/pkg/apis/meta/v1
go: finding module for package k8s.io/client-go/util/cert
go: finding module for package k8s.io/client-go/kubernetes
go: finding module for package github.com/mitchellh/go-ps
go: finding module for package k8s.io/client-go/tools/cache
go: finding module for package github.com/spf13/pflag
go: finding module for package k8s.io/apimachinery/pkg/util/version
go: finding module for package github.com/zakjan/cert-chain-resolver/certUtil
go: finding module for package github.com/prometheus/client_golang/prometheus
go: finding module for package k8s.io/api/networking/v1beta1
go: finding module for package k8s.io/apimachinery/pkg/util/intstr
go: finding module for package github.com/fsnotify/fsnotify
go: finding module for package k8s.io/apimachinery/pkg/api/equality
go: finding module for package github.com/armon/go-proxyproto
go: finding module for package gopkg.in/go-playground/pool.v3
go: finding module for package k8s.io/client-go/tools/clientcmd
go: finding module for package k8s.io/client-go/tools/leaderelection/resourcelock
go: finding module for package github.com/pkg/errors
go: finding module for package k8s.io/client-go/tools/record
go: finding module for package k8s.io/client-go/tools/leaderelection
go: finding module for package pault.ag/go/sniff/parser
go: finding module for package k8s.io/kubernetes/pkg/util/sysctl
go: finding module for package github.com/eapache/channels
go: finding module for package github.com/prometheus/client_model/go
go: finding module for package github.com/mitchellh/hashstructure
go: finding module for package k8s.io/kubernetes/pkg/kubelet/util/sliceutils
go: finding module for package github.com/prometheus/common/expfmt
go: finding module for package k8s.io/client-go/kubernetes/scheme
go: finding module for package github.com/mitchellh/mapstructure
go: finding module for package k8s.io/apimachinery/pkg/util/validation
go: finding module for package k8s.io/apimachinery/pkg/runtime
go: finding module for package github.com/ncabatoff/process-exporter/proc
go: finding module for package github.com/json-iterator/go
go: finding module for package github.com/opencontainers/runc/libcontainer/cgroups
go: finding module for package k8s.io/api/admission/v1beta1
go: finding module for package k8s.io/client-go/util/workqueue
go: finding module for package github.com/imdario/mergo
go: finding module for package k8s.io/client-go/informers
go: finding module for package k8s.io/apimachinery/pkg/runtime/schema
go: finding module for package k8s.io/apimachinery/pkg/runtime/serializer
go: finding module for package github.com/ncabatoff/process-exporter
go: finding module for package k8s.io/apimachinery/pkg/watch
go: finding module for package k8s.io/apimachinery/pkg/util/runtime
go: finding module for package k8s.io/apimachinery/pkg/util/sets
go: finding module for package k8s.io/client-go/kubernetes/typed/core/v1
go: finding module for package k8s.io/client-go/util/flowcontrol
go: finding module for package k8s.io/apimachinery/pkg/util/json
go: finding module for package k8s.io/apimachinery/pkg/labels
internal/ingress/controller/nginx.go:38:2: module github.com/armon/go-proxyproto: Get "https://proxy.golang.org/github.com/armon/go-proxyproto/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/ingress/controller/nginx.go:39:2: module github.com/eapache/channels: Get "https://proxy.golang.org/github.com/eapache/channels/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/watch/file_watcher.go:26:2: module github.com/fsnotify/fsnotify: Get "https://proxy.golang.org/github.com/fsnotify/fsnotify/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/ingress/annotations/annotations.go:20:2: module github.com/imdario/mergo: Get "https://proxy.golang.org/github.com/imdario/mergo/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/metric/collectors/socket.go:27:2: module github.com/json-iterator/go: Get "https://proxy.golang.org/github.com/json-iterator/go/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/nginx/main.go:30:2: module github.com/mitchellh/go-ps: Get "https://proxy.golang.org/github.com/mitchellh/go-ps/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/controller.go:26:2: module github.com/mitchellh/hashstructure: Get "https://proxy.golang.org/github.com/mitchellh/hashstructure/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/template/configmap.go:29:2: module github.com/mitchellh/mapstructure: Get "https://proxy.golang.org/github.com/mitchellh/mapstructure/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/ingress/metric/collectors/process.go:25:2: module github.com/ncabatoff/process-exporter: Get "https://proxy.golang.org/github.com/ncabatoff/process-exporter/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/checker.go:26:2: module github.com/ncabatoff/process-exporter/proc: Get "https://proxy.golang.org/github.com/ncabatoff/process-exporter/proc/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/runtime/cpu_linux.go:29:2: module github.com/opencontainers/runc/libcontainer/cgroups: Get "https://proxy.golang.org/github.com/opencontainers/runc/libcontainer/cgroups/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/file/structure.go:22:2: module github.com/pkg/errors: Get "https://proxy.golang.org/github.com/pkg/errors/@v/list": dial tcp 34.64.4.81:443: i/o timeout
cmd/nginx/main.go:32:2: module github.com/prometheus/client_golang/prometheus: Get "https://proxy.golang.org/github.com/prometheus/client_golang/prometheus/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:33:2: module github.com/prometheus/client_golang/prometheus/promhttp: Get "https://proxy.golang.org/github.com/prometheus/client_golang/prometheus/promhttp/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/metric/collectors/testutils.go:27:2: module github.com/prometheus/client_model/go: Get "https://proxy.golang.org/github.com/prometheus/client_model/go/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/metric/collectors/testutils.go:28:2: module github.com/prometheus/common/expfmt: Get "https://proxy.golang.org/github.com/prometheus/common/expfmt/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/flags.go:25:2: module github.com/spf13/pflag: Get "https://proxy.golang.org/github.com/spf13/pflag/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/net/ssl/ssl.go:41:2: module github.com/zakjan/cert-chain-resolver/certUtil: Get "https://proxy.golang.org/github.com/zakjan/cert-chain-resolver/cert%21util/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/status/status.go:31:2: module gopkg.in/go-playground/pool.v3: Get "https://proxy.golang.org/gopkg.in/go-playground/pool.v3/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/admission/controller/main.go:22:2: module k8s.io/api/admission/v1beta1: Get "https://proxy.golang.org/k8s.io/api/admission/v1beta1/@v/list": dial tcp 34.64.4.81:443: i/o timeout
cmd/nginx/flags.go:27:2: module k8s.io/api/core: Get "https://proxy.golang.org/k8s.io/api/core/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/annotations/class/main.go:20:2: module k8s.io/api/networking/v1beta1: Get "https://proxy.golang.org/k8s.io/api/networking/v1beta1/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/controller.go:29:2: module k8s.io/apimachinery/pkg/api/equality: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/api/equality/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:34:2: module k8s.io/apimachinery/pkg/api/errors: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/api/errors/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:35:2: module k8s.io/apimachinery/pkg/apis/meta: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/apis/meta/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/store/store.go:33:2: module k8s.io/apimachinery/pkg/labels: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/labels/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/admission/controller/server.go:25:2: module k8s.io/apimachinery/pkg/runtime: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/runtime/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/ingress/sslcert.go:23:2: module k8s.io/apimachinery/pkg/runtime/schema: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/runtime/schema/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/admission/controller/server.go:26:2: module k8s.io/apimachinery/pkg/runtime/serializer: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/runtime/serializer/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/controller.go:30:2: module k8s.io/apimachinery/pkg/util/intstr: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/util/intstr/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/admission/controller/server.go:27:2: module k8s.io/apimachinery/pkg/util/json: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/util/json/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/store/store.go:35:2: module k8s.io/apimachinery/pkg/util/runtime: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/util/runtime/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/annotations/parser/main.go:26:2: module k8s.io/apimachinery/pkg/util/sets: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/util/sets/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/endpoints.go:25:2: module k8s.io/apimachinery/pkg/util/validation: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/util/validation/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/k8s/main.go:30:2: module k8s.io/apimachinery/pkg/util/version: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/util/version/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:36:2: module k8s.io/apimachinery/pkg/util/wait: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/util/wait/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:37:2: module k8s.io/apimachinery/pkg/version: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/version/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/store/store.go:37:2: module k8s.io/apimachinery/pkg/watch: Get "https://proxy.golang.org/k8s.io/apimachinery/pkg/watch/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:38:2: module k8s.io/apiserver/pkg/server/healthz: Get "https://proxy.golang.org/k8s.io/apiserver/pkg/server/healthz/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/store/store.go:38:2: module k8s.io/client-go/informers: Get "https://proxy.golang.org/k8s.io/client-go/informers/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:39:2: module k8s.io/client-go/kubernetes: Get "https://proxy.golang.org/k8s.io/client-go/kubernetes/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/nginx.go:43:2: module k8s.io/client-go/kubernetes/scheme: Get "https://proxy.golang.org/k8s.io/client-go/kubernetes/scheme/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/nginx.go:44:2: module k8s.io/client-go/kubernetes/typed/core: Get "https://proxy.golang.org/k8s.io/client-go/kubernetes/typed/core/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:40:2: module k8s.io/client-go/rest: Get "https://proxy.golang.org/k8s.io/client-go/rest/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/k8s/main.go:32:2: module k8s.io/client-go/tools/cache: Get "https://proxy.golang.org/k8s.io/client-go/tools/cache/@v/list": dial tcp 34.64.4.113:443: i/o timeout
cmd/nginx/main.go:41:2: module k8s.io/client-go/tools/clientcmd: Get "https://proxy.golang.org/k8s.io/client-go/tools/clientcmd/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/ingress/controller/status.go:30:2: module k8s.io/client-go/tools/leaderelection: Get "https://proxy.golang.org/k8s.io/client-go/tools/leaderelection/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/ingress/controller/status.go:31:2: module k8s.io/client-go/tools/leaderelection/resourcelock: Get "https://proxy.golang.org/k8s.io/client-go/tools/leaderelection/resourcelock/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/ingress/controller/nginx.go:45:2: module k8s.io/client-go/tools/record: Get "https://proxy.golang.org/k8s.io/client-go/tools/record/@v/list": dial tcp 34.64.4.81:443: i/o timeout
cmd/nginx/main.go:42:2: module k8s.io/client-go/util/cert: Get "https://proxy.golang.org/k8s.io/client-go/util/cert/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/nginx.go:46:2: module k8s.io/client-go/util/flowcontrol: Get "https://proxy.golang.org/k8s.io/client-go/util/flowcontrol/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/task/queue.go:28:2: module k8s.io/client-go/util/workqueue: Get "https://proxy.golang.org/k8s.io/client-go/util/workqueue/@v/list": dial tcp 34.64.4.81:443: i/o timeout
internal/file/file.go:24:2: module k8s.io/klog/v2: Get "https://proxy.golang.org/k8s.io/klog/v2/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/status/status.go:37:2: module k8s.io/kubernetes/pkg/kubelet/util/sliceutils: Get "https://proxy.golang.org/k8s.io/kubernetes/pkg/kubelet/util/sliceutils/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/util.go:29:2: module k8s.io/kubernetes/pkg/util/sysctl: Get "https://proxy.golang.org/k8s.io/kubernetes/pkg/util/sysctl/@v/list": dial tcp 34.64.4.113:443: i/o timeout
internal/ingress/controller/tcp.go:26:2: module pault.ag/go/sniff/parser: Get "https://proxy.golang.org/pault.ag/go/sniff/parser/@v/list": dial tcp 34.64.4.113:443: i/o timeout
Makefile:80: recipe for target 'build' failed
make[1]: *** [build] Error 1
Makefile:159: recipe for target 'dev-env' failed
make: *** [dev-env] Error 2

## Do you have any guesses?

No

**Comment by aofei** [comment]
根据你贴出来的日志内容，说明你的构建环境并没有设置正确的 GOPROXY 环境变量。需要注意，容器的环境变量跟宿主机的环境变量是完全相独立的，所以建议检查一下你的 image 脚本是否有设置。

**Comment by Chenpipi** [comment]
> 根据你贴出来的日志内容，说明你的构建环境并没有设置正确的 GOPROXY 环境变量。需要注意，容器的环境变量跟宿主机的环境变量是完全相独立的，所以建议检查一下你的 image 脚本是否有设置。

非常感谢，确实是build的环境变量和系统不同导致的。
