### ISSUE TITLE
问题：go mod download时出现证书问题

### ISSUE THREAD

**Issue by mingocn** [goproxy/goproxy.cn#103]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.13.8 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/work/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build049840781=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

go mod download

## 你实际看到的结果是什么？

go: github.com/natefinch/lumberjack@v2.0.0+incompatible: Get https://goproxy.cn/github.com/natefinch/lumberjack/@v/v2.0.0+incompatible.mod: x509: certificate signed by unknown authority

**Comment by aofei** [comment]
你好，这个错误表面你环境中的 CA 库缺失了主流的 CA 机构证书，请问你的环境是什么系统？如果是 Ubuntu 的话，可以尝试执行 `sudo apt install ca-certificates`。

**Comment by mingocn** [comment]
> 你好，这个错误表面你环境中的 CA 库缺失了主流的 CA 机构证书，请问你的环境是什么系统？如果是 Ubuntu 的话，可以尝试执行 `sudo apt install ca-certificates`。

感谢，正是ubuntu，顺利解决问题。
