### ISSUE TITLE
问题：go get失败怎么办？

### ISSUE THREAD

**Issue by weilongyun** [goproxy/goproxy.cn#104]
go get失败怎么办？

**Comment by aofei** [comment]
你好，你需要提供详细的错误信息，不然简单的一句是无法发现你的问题究竟出在哪里。

最好是按照我们提供的 issue 模板来填写，比如 go env 的输出对解答问题会很有帮助。

**Comment by aofei** [comment]
由于长时间未回复，所以我就暂时先关闭这个 issue 了哈，如果还有其他问题欢迎随时提问～
