### ISSUE TITLE
问题：D:\GOPATH\GOPATH\pkg\mod\github.com\go-playground\universal-translator@v0.17.0\errors.go:7:2: github.com/go-playground/locales@v0.13.0: stream error: stream ID 241; INTERNA L_ERROR

### ISSUE THREAD

**Issue by duanlianjie** [goproxy/goproxy.cn#106]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

确定

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.15.3 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\GOPATH\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GOPATH\GOPATH
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ xxx\AppData\Local\Temp\go-build152554950=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

Google搜索问题：输入`go get -u github.com/gin-gonic/gin`后，在末尾一行提示`D:\GOPATH\GOPATH\pkg\mod\github.com\go-playground\universal-translator@v0.17.0\errors.go:7:2: github.com/go-playground/locales@v0.13.0: stream error: stream ID 241; INTERNA L_ERROR`，并且在我的GOPATH下的src目录中也没有gin-gonic文件夹；然后我尝试输入`go get github.com/go-playground/locales`，提示`go: downloading github.com/go-playground/locales v0.13.0`
`go get github.com/go-playground/locales: github.com/go-playground/locales@v0.13.0: stream error: stream ID 9; INTERNAL_ERROR`

## 你期望看到的结果是什么？

期望看到安装成功

## 你实际看到的结果是什么？

实际没有安装成功

**Comment by aofei** [comment]
你好，首先 Go modules 并不会将下载的模块数据放在 `$GOPATH/src` 下了，现在是放在 `$GOMODCACHE` 下，`$GOMODCACHE` 为空时（即默认值）取 `$GOPATH[0]/pkg/mod`。

然后再说一下你遇到的这个错误，请问你处于相同环境下在终端直接请求 `https://goproxy.cn/github.com/gin-gonic/gin/@latest` 时能否拿到正常的响应？比如你执行 `curl -i https://goproxy.cn/github.com/gin-gonic/gin/@latest` 这条命令时的输出结果是什么？

**Comment by aofei** [comment]
Go modules 的工作方式就是脱离 `$GOPATH/src` 的，所以当你启用了 Go modules 后你就不需要再关心 `$GOPATH/src` 了，代码想放在哪里就放在哪里。

你报错那个的意思是你没有安装 [curl](https://curl.se/) 工具。

**Comment by duanlianjie** [comment]
谢谢回复！

输入`curl -i https://goproxy.cn/github.com/gin-gonic/gin/@latest`后显示如下:
```
HTTP/1.1 200 OK
Server: Tengine
Content-Type: application/json; charset=utf-8
Content-Length: 50
Connection: keep-alive
Date: Wed, 18 Nov 2020 10:46:23 GMT
Cache-Control: public, max-age=60
X-M-Log: QNM:fs228;SRCPROXY:fs177;SRC:119;SRCPROXY:119;QNM3:120
X-M-Reqid: El4AAI6srXpalEgW
X-Qnm-Cache: Validate as miss: no-header,MissValidate
Ali-Swift-Global-Savetime: 1605696383
Via: cache24.l2nu20-1[321,200-0,M], cache7.l2nu20-1[322,0], cache2.cn17[514,200-0,M], cache2.cn17[516,0]
X-Cache: MISS TCP_MISS dirn:-2:-2
X-Swift-SaveTime: Wed, 18 Nov 2020 10:46:23 GMT
X-Swift-CacheTime: 60
Timing-Allow-Origin: *
EagleId: 79c2079616056963831297309e

{"Version":"v1.6.3","Time":"2020-05-03T14:00:20Z"}
```

**Comment by duanlianjie** [comment]
谢谢回复！

我刚才装了curl工具，`curl -i https://goproxy.cn/github.com/gin-gonic/gin/@latest`的结果是：
```
HTTP/1.1 200 OK
Server: Tengine
Content-Type: application/json; charset=utf-8
Content-Length: 50
Connection: keep-alive
Date: Wed, 18 Nov 2020 10:52:39 GMT
Cache-Control: public, max-age=60
X-M-Log: QNM:fs228;SRCPROXY:fs176;SRC:125;SRCPROXY:125;QNM3:126
X-M-Reqid: El4AAF7NiQiylEgW
X-Qnm-Cache: Validate as miss: no-header,MissValidate
Ali-Swift-Global-Savetime: 1605696759
Via: cache24.l2nu20-1[288,200-0,M], cache17.l2nu20-1[289,0], cache2.cn17[483,200-0,M], cache8.cn17[488,0]
X-Cache: MISS TCP_REFRESH_MISS dirn:9:513565241
X-Swift-SaveTime: Wed, 18 Nov 2020 10:52:39 GMT
X-Swift-CacheTime: 60
Timing-Allow-Origin: *
EagleId: 79c2079c16056967592155103e

{"Version":"v1.6.3","Time":"2020-05-03T14:00:20Z"}
```
然后莫名其妙我输入`go get -u github.com/gin-gonic/gin`后又成功地将gin下载到$GOMODCACHE下了，现在的问题是，我在代码中`import "github.com/gin-gonic/gin"`依然报错，不知道怎么回事？

**Comment by aofei** [comment]
如果你 go get 执行成功了，那说明题干中提到的错误只是偶尔发生的，事实上 go 的HTTP/2 客户端设计得的确有些问题。

至于为什么代码中 import 还会报错，那就有可能是你的开发工具暂时还没有识别到，比如 GoLand 就有一个索引的过程，你可以尝试重启 GoLand 看看。

**Comment by duanlianjie** [comment]
谢谢回复！

我重启了GoLand还是不行，然后我把`$GOMODCACHE`下的文件都移动到`$GOPATH/src`下之后，并且把`gin@v1.6.3`文件夹重命名为`gin`，然后执行了以下两个命令可以运行quick_start了。

```
  go mod init gin

  go mod edit -require github.com/gin-gonic/gin@latest
```

**Comment by aofei** [comment]
需要注意，当你处于 Go modules 模式下时，是不会再去操纵 `$GOPATH/src` 的。

你的 GoLand 项目是不是没有启用 Go modules 啊？GoLand 中需要单独配置启用，以及单独配置 `GOPROXY` 等环境变量的，它们与系统环境变量不共享。

**Comment by duanlianjie** [comment]
太感谢了！

是的，我重建了个Go Modules的项目后，执行了刚才那两个命令后可以了。我去了解下Go Modules，太感谢了！

**Comment by aofei** [comment]
好的，既然问题解决了，那这个 issue 我就先关闭了哈～
