### ISSUE TITLE
问题： goproxy.cn与proxy.golang.org库同步间隔时间

### ISSUE THREAD

**Issue by Shineee** [goproxy/goproxy.cn#107]
goproxy.cn的库与proxy.golang.org的库同步间隔时间是多少呢？

**Comment by aofei** [comment]
你好，Go module proxy 跟传统的“镜像“是不一样的，所以并不存在和某个其他代理“同步时间”的概念，你可以理解成我们是实时回源到 GitHub 的。当然为了防止恶意攻击我们会加上 CDN 缓存时间，通常是自第一个请求起的一到两分钟后过期，最坏情况下可能到五分钟。如果你想让某个版本立马被请求到，你可以直接 go get example.com/foobar@v1.2.3 这样子来明确请求版本号，可以立即拿到。

**Comment by Shineee** [comment]
明白了，谢谢

**Comment by aofei** [comment]
由于问题已回答，这个 issue 我就先关闭了哈，如果还有其他问题欢迎随时提问～
