### ISSUE TITLE
建议官网命令去掉$

### ISSUE THREAD

**Issue by snuglove** [goproxy/goproxy.cn#109]
官网命令页面
$ go env -w GO111MODULE=on
$ go env -w GOPROXY=https://goproxy.cn,direct

建议把前面的$ 去掉 这样可以直接复制执行 不用每次在vs上手动去除然后在粘贴到服务器上执行

**Comment by dyingway** [comment]
```
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct
```
帮助文件是普适性的，而不是偷懒用的

**Comment by aofei** [comment]
前几天我想了一下这个，忘记回复了。

其实 CLI 示例中为命令加前导 `$` 算是一个普遍行为了，比如 [`git init`](https://git-scm.com/docs/git-init#_examples) 中。你还可以在其他地方找到很多。这样其实也有好处，可以区分示例中的输入和输出部分。所以，我想还是不需要改变这个了。

**Comment by snuglove** [comment]
谢谢两位的解答,因为我不是go开发者,从我的角度考虑,我不会记住这个,用的时候我就去官网查找,所以才有这个问题.感谢解答
