### ISSUE TITLE
企业级开发场景下，如何屏蔽内网的依赖包

### ISSUE THREAD

**Issue by lambdaxs** [goproxy/goproxy.cn#11]
是否有白名单配置？

**Comment by aofei** [comment]
是这样的，目前来说私有模块的处理方式主要有以下几种：

## < Go 1.13

搭建私有的 GOPROXY 服务，可以使用 [Goproxy](https://github.com/goproxy/goproxy)，然后使用 [goproxy.cn](https://goproxy.cn) 来作为上游代理，因为 Goproxy 是内置支持设置 `GONOPROXY` 的，换句话说即使是在 Go 1.13 之前都可以使用。

## >= Go 1.13

也可以搭建私有的 GOPROXY 服务，或者可以使用 `GOPROXY` 列表：

```bash
$ export GOPROXH=https://goproxy.cn,direct
```

这个的好处就是优先使用 `https://goproxy.cn` 来抓取模块，如果发现是 404 或者 410 那么就回退到 `direct` 也就是直接去模块的源头抓取，比如你使用 GitHub 的私有库时就可以这么设置，因为 GitHub 的原则是你无权访问的资源对你来说就是不存在（404）的。

或者是使用 `GONOPROXY` 或 `GOPRIVATE`：

```bash
$ export GONOPROXY=*.corp.example.com
$ # 或者
$ export GOPRIVATE=*.corp.example.com
```

这个是目前最好的解决方案了。

**Comment by lambdaxs** [comment]
多谢

**Comment by douglarek** [comment]
@aofei 能否展开说说第一种方案，如何使用 goproxy.cn 作为上游？

**Comment by aofei** [comment]
@douglarek 

总共有两种方式：

## 第一种

创建一个 `main.go` 文件：

```go
package main

import (
        "net/http"

        "github.com/goproxy/goproxy"
)

func main() {
        http.ListenAndServe(":8080", goproxy.New())
}
```

接着执行

```bash
$ GOPROXY=https://goproxy.cn GONOPROXY=github.com go run main.go
```

然后设置你具体项目开发环境的 `GOPROXY` 环境变量：

```bash
$ export GOPROXY=http://localhost:8080
```

就好了。

## 第二种

创建一个 `main.go` 文件：

```go
package main

import (
        "log"
        "net/http"
        "os"

        "github.com/goproxy/goproxy"
)

func main() {
        if err := os.Setenv("GOPROXY", "https://goproxy.cn"); err != nil {
                log.Fatalf("failed to set $GOPROXY: %v", err)
        }

        if err := os.Setenv("GONOPROXY", "github.com"); err != nil {
                log.Fatalf("failed to set $GONOPROXY: %v", err)
        }

        http.ListenAndServe(":8080", goproxy.New())
}
```

接着执行

```bash
$ go run main.go
```

然后设置你具体项目开发环境的 `GOPROXY` 环境变量：

```bash
$ export GOPROXY=http://localhost:8080
```

就好了。

---

如果你想更深入了解 [Goproxy](https://github.com/goproxy/goproxy) 这个项目的高级用法，那么你可以看一看它的 [GoDoc](https://godoc.org/github.com/goproxy/goproxy)。[Goproxy](https://github.com/goproxy/goproxy) 这个项目很轻量级是可编程的，归根结底它就是一个 [`http.Handler`](https://godoc.org/net/http#Handler) 的实现罢了，所以你可以用各种机制像是 Middleware 之类的比如 Basic Auth 这种来过滤请求，你可以把它作为一个模块引入你们公司内网网站或者你自己的网站，我觉得就可以在一定程度上解决私有包的问题了。

**Comment by douglarek** [comment]
@aofei thanks
