### ISSUE TITLE
问题：fabric智能合约mian.go中引入两个包shim和peer，执行命令go mod tidy报错，请问怎么解决？

### ISSUE THREAD

**Issue by JsuBaron** [goproxy/goproxy.cn#112]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

没有

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.16.3 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jsubaron/.cache/go-build"
GOENV="/home/jsubaron/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jsubaron/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jsubaron/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jsubaron/go/src/github.com/kongyixueyuan.com/kongyixueyuan/chaincode/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2495851802=/tmp/go-build -gno-record-gcc-switches"

</pre>
</details>

## 你做了什么？

编写的fabric智能合约mian.go中引入两个包shim和peer，执行命令go mod tidy报错如下：
<pre>
$ go env
go: finding module for package github.com/hyperledger/fabric/core/chaincode/shim
go: finding module for package github.com/hyperledger/fabric/protos/peer
github.com/kongyixueyuan.com/kongyixueyuan/chaincode imports
	github.com/hyperledger/fabric/core/chaincode/shim: module github.com/hyperledger/fabric/core/chaincode/shim: Get "https://goproxy.cn/github.com/hyperledger/fabric/core/chaincode/shim/@v/list": dial tcp: lookup goproxy.cn: no such host
github.com/kongyixueyuan.com/kongyixueyuan/chaincode imports
	github.com/hyperledger/fabric/protos/peer: module github.com/hyperledger/fabric/protos/peer: Get "https://goproxy.cn/github.com/hyperledger/fabric/protos/peer/@v/list": dial tcp: lookup goproxy.cn: no such host
</pre>

**Comment by aofei** [comment]
你好，这是一个你机器本地的 DNS 错误（lookup goproxy.cn: no such host），你可以检查一下机器的网络配置，比如你可以在该机器的终端直接执行 dig goproxy.cn 命令来看看是否能正常解析拿到 CDN 节点 IP。

**Comment by JsuBaron** [comment]
问题解决了，感谢 👍

**Comment by aofei** [comment]
由于问题已解决，那这个 issue 我就先关闭了哈，有其他问题的话欢迎随时开新 issue 提问～
