### ISSUE TITLE
问题：https://goproxy.cn/github.com/pdfcpu/pdfcpu/@v/v0.3.11.info 报504的错误

### ISSUE THREAD

**Issue by hawayiii** [goproxy/goproxy.cn#113]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.16 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/weiyihe/Library/Caches/go-build"
GOENV="/Users/weiyihe/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/weiyihe/go/pkg/mod"
GONOPROXY="*.garena.com"
GONOSUMDB="*.garena.com"
GOOS="darwin"
GOPATH="/Users/weiyihe/go"
GOPRIVATE="*.garena.com"
GOPROXY="https://goproxy.cn/,direct"
GOROOT="/Users/weiyihe/go/go1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/weiyihe/go/go1.16/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qr/djbn9vzj42s9vvl8532bvy740000gp/T/go-build3956575379=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？

我在执行go get github.com/pdfcpu/pdfcpu的时候，发现包下载失败；
发现使用代理访问链接：https://goproxy.cn/github.com/pdfcpu/pdfcpu/@v/v0.3.11.info 报504的错误，
但是使用goproxy.io代理不会报错，https://goproxy.io/github.com/pdfcpu/pdfcpu/@v/v0.3.11.info 是可以正常返回的；

## 你期望看到的结果是什么？

https://goproxy.cn/github.com/pdfcpu/pdfcpu/@v/v0.3.11.info能正常返回数据

## 你实际看到的结果是什么？

504 Gateway Time-out

**Comment by aofei** [comment]
这大概是跟 github.com/pdfcpu/pdfcpu 是个超大 repo 有关，它的压缩包有 246582215 bytes (235.16 MiB) 之大。对于绝大多数 Go 项目来说 repo 压缩包都在 20 MiB 以内（即时 github.com/kubernetes/kubernetes 也才 14.87 MiB），因此对于类似 pdfcpu 这类问题 repo 我们的 CDN 给后台的时间不够，所以 CDN 着急提前响应了 504 给客户端。

已找到解决方案，部署后我会更新到这里。

**Comment by aofei** [comment]
已修复，现在你可以正常获取了，感谢反馈～😊

**Comment by hawayiii** [comment]
thx
