### ISSUE TITLE
运行时获取golang的protobuf包出错，能通过设置代理解决吗

### ISSUE THREAD

**Issue by bhtomming** [goproxy/goproxy.cn#114]
## 在docker里的xcaddy启动时出现下面的错误，在网上找了没有解决方法，我想求助于你们，不知道通过设置代理能不能起作用。

<details>
<summary><code>panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc000304540, 0x1c28f40, 0xc0003066f0, 0xc000304540)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0001840e0, 0x1c665a0, 0xc000304540, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc000303200, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc0001821e0, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc0002da540, 0x1c28f40, 0xc000185730, 0xc0002da540)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc00009a100, 0x1c665a0, 0xc0002da540, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0002d9200, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc0000962a0, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc0001a5a40, 0x1c28f40, 0xc0002212c0, 0xc0001a5a40)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0001050c0, 0x1c665a0, 0xc0001a5a40, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc00029e600, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc000107dd0, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc0000dda40, 0x1c28f40, 0xc0002d82f0, 0xc0000dda40)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0000a4140, 0x1c665a0, 0xc0000dda40, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0002e8600, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc00009e480, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc0002c1a40, 0x1c28f40, 0xc0003ca320, 0xc0002c1a40)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc00028a120, 0x1c665a0, 0xc0002c1a40, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0003da600, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc000282390, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc00024ba40, 0x1c28f40, 0xc0003d42d0, 0xc00024ba40)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0002040d0, 0x1c665a0, 0xc00024ba40, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0003e4600, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc0002001e0, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc00034a540, 0x1c28f40, 0xc0001a10f0, 0xc00034a540)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc00009a150, 0x1c665a0, 0xc00034a540, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc000349200, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc0000963f0, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc0003d0540, 0x1c28f40, 0xc000319560, 0xc0003d0540)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc00006c140, 0x1c665a0, 0xc0003d0540, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0003cf200, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc000102420, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc0003ca540, 0x1c28f40, 0xc0002131e0, 0xc0003ca540)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc000097010, 0x1c665a0, 0xc0003ca540, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0003c9200, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc0000999e0, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
panic: proto: file "pb.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5d580, 0xc0002bfa40, 0x1c28f40, 0xc000293c70, 0xc0002bfa40)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0002920c0, 0x1c665a0, 0xc0002bfa40, 0x0, 0x0)
	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0003ba600, 0x47a, 0x600, 0x800000003, 0x0, 0x1c3c680, 0xc000282150, 0x1c45b80, ...)
	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x197198a, 0x8, 0x26398e0, 0x2b3, 0x2b3)
	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
github.com/dgraph-io/badger/v2/pb.init.1()
	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a</code> 的输出结果</summary>
<br>

</details>

**Comment by aofei** [comment]
你好，这看起来并不像是一个获取 google.golang.org/protobuf 包时产生的错误，所以跟 Go module proxy 也就无关了。这个错误是你项目中的 protobuf 存在 proto package 名称冲突导致的，解决办法是把同名的 proto package 换个其他名称，解决办法请参考[这里](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict)。
