### ISSUE TITLE
问题：包路径的大小写处理有问题

### ISSUE THREAD

**Issue by joesonw** [goproxy/goproxy.cn#118]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

`github.com/TencentCloud/tdmq-go-client@v0.2.0-beta.1`此包
`https://goproxy.cn/github.com/%21tencent%21cloud/tdmq-go-client/@v/v0.2.0-beta.1.zip` 有问题
`https://goproxy.cn/github.com/TencentCloud/tdmq-go-client/@v/v0.2.0-beta.1.zip` 有问题
`https://goproxy.cn/github.com/tencentcloud/tdmq-go-client/@v/v0.2.0-beta.1.zip` 没问题
`https://goproxy.io/github.com/%21tencent%21cloud/tdmq-go-client/@v/v0.2.0-beta.1.zip` 没问题

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go 1.15.2
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

## 你做了什么？

go get  github.com/TencentCloud/tdmq-go-client@v0.2.0-beta.1

## 你期望看到的结果是什么？
成功

## 你实际看到的结果是什么？

```
github.com/TencentCloud/tdmq-go-client@v0.2.0-beta.1: reading https://goproxy.cn/github.com/%21tencent%21cloud/tdmq-go-client/@v/v0.2.0-beta.1.zip: 404 Not Found
```

**Comment by aofei** [comment]
抱歉，这是昨天的 b4adc0284601a6ea954ea0c43c8730413c8d19dd 引入的 bug，现已修复并部署。

顺便说一下，通过你遇到这个问题发现了你的 GOPROXY 环境变量配置可能存在点儿缺陷，如果你配置成 `https://goproxy.cn,direct` 的话会更好，也就是尾部多个 `,direct`，那样你这次是遇不到这个问题的。当然如果你遇不到这个问题的话你也就不会来反馈我们也就不能及时获知来修复，不过无论如何还是应该告知你一下。

非常感谢你能来反馈！帮了大忙～😄
