### ISSUE TITLE
问题：将GO111MODULE设置为on以后无法执行get指令

### ISSUE THREAD

**Issue by PeachSix** [goproxy/goproxy.cn#119]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

确定

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.11.6 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY="https://goproxy.cn"
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build407052023=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

export GO111MODULE=on
export GOPROXY=https://goproxy.cn
go get -v github.com/gin-gonic/gin
## 你期望看到的结果是什么？

安装gin框架

## 你实际看到的结果是什么？

go: cannot find main module; see 'go help modules'

**Comment by PeachSix** [comment]
> ## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？
> 确定
> 
> ## 当你执行 `go version` 命令后的输出结果是什么？
> $ go version
> 
> go version go1.11.6 linux/amd64
> ## 当你执行 `go env` 命令后的输出结果是什么？
> `go env` 的输出结果
> ## 你做了什么？
> export GO111MODULE=on
> export GOPROXY=https://goproxy.cn
> go get -v github.com/gin-gonic/gin
> 
> ## 你期望看到的结果是什么？
> 安装gin框架
> 
> ## 你实际看到的结果是什么？
> go: cannot find main module; see 'go help modules'

**Comment by aofei** [comment]
> go: cannot find main module; see 'go help modules'

这个错误信息的意思是，你需要在一个模块项目（即“主模块”）中执行 `go get` 命令，也就是说执行此命令的当前目录下（或者其父级目录）中包含一个 `go.mod` 文件才行。

你可以通过使用 `go mod init` 来在当前目录初始化一个 `go.mod` 文件，比如 `go mod init some-project.tld`。

**Comment by PeachSix** [comment]
好了，谢谢。
