### ISSUE TITLE
go get with custom package name 404

### ISSUE THREAD

**Issue by runzexia** [goproxy/goproxy.cn#12]
```
GOPROXY=https://goproxy.cn/ GO111MODULE=on go get kubesphere.io/kubesphere@cda4f4f05ae1d5c653e7158b8de0164f92341e5c
go: finding kubesphere.io/kubesphere v0.0.0-20190726052749-cda4f4f05ae1
go: finding github.com/onsi/ginkgo v1.8.0
go: kubesphere.io/kubesphere@v0.0.0-20190726052749-cda4f4f05ae1: unexpected status (https://goproxy.cn/kubesphere.io/kubesphere/@v/v0.0.0-20190726052749-cda4f4f05ae1.info): 404 Not Found
go: error loading module requirements
```

**Comment by aofei** [comment]
This's the error I found in the log:

```
unrecognized import path "kubesphere.io/kubesphere" (https fetch: Get http://kubesphere.io/kubesphere/?go-get=1: redirected from secure URL https://kubesphere.io/kubesphere?go-get=1 to insecure URL http://kubesphere.io/kubesphere/?go-get=1)
```

**Comment by runzexia** [comment]
I can get this pkg when I don't use goproxy/ using ali goproxy. Where can I find this log?

**Comment by aofei** [comment]
What version of Go are you using? I guess Ali's proxy runs under an old version of Go, and it seems that the new version of Go is becoming more stringent in terms of security.

**Comment by runzexia** [comment]
I use `go version go1.12.1 darwin/amd64`

**Comment by aofei** [comment]
Weird, the [proxy.golang.org](https://proxy.golang.org) prints the same as the [goproxy.cn](https://goproxy.cn).

See https://proxy.golang.org/kubesphere.io/kubesphere/@v/v0.0.0-20190726052749-cda4f4f05ae1.info.

But the `GOPROXY=direct GO111MODULE=on go get kubesphere.io/kubesphere@cda4f4f05ae1d5c653e7158b8de0164f92341e5c` has no problems on my side (go version go1.12.7 linux/amd64).

**Comment by runzexia** [comment]
Yes, this behavior is very strange, and I don't know why there is a record of access to http url in the log.

**Comment by aofei** [comment]
I don't know, it seems that the [kubesphere.io](https://kubesphere.io) is doing something wrong. See [this](https://github.com/golang/go/issues/32071) and [this](https://github.com/golang/go/issues/29618).

After my tests, most of the packages using other services (such as [golang.org/x/text](https://golang.org/x/text) and [gopkg.in/yaml.v2](https://gopkg.in/yaml.v2)) can be obtained through the [goproxy.cn](https://goproxy.cn) without any special treatment. I found out that you're a KubeSphere employee, so can you please investigate it? And I sincerely hope that you can share the reasons after solving. Thanks! 😊

**Comment by runzexia** [comment]
Thanks！！！ I will check the problem of kubesphere

**Comment by runzexia** [comment]
We fixed it, thank you!

**Comment by aofei** [comment]
So... how?

**Comment by runzexia** [comment]
> So... how?


It could work now, thank you very much!

**Comment by aofei** [comment]
Sorry, I didn't express myself clearly. What I want to ask is how did you solve this problem? What exact changes have been made? I'd like to learn something from this problem too. 😊

**Comment by runzexia** [comment]
At first we will put https://kubesphere.io/kubesphere?go-get=1 
redirect to http://kubesphere.io/kubesphere/?go-get=1.

Now https://kubesphere.io/kubesphere?go-get=1 no redirection, it work

**Comment by aofei** [comment]
Got it, thanks!
