### ISSUE TITLE
Go 模块：github.com/sunshinev/go-sword/v2

### ISSUE THREAD

**Issue by sunshinev** [goproxy/goproxy.cn#120]
删除了v2.0.1的分支，但是还是可以go get到，
请问多久更新，才能只拉取到最新版本v2.0.0

**Comment by aofei** [comment]
可以理解成**永远不会被删除**，因为 Go 模块代理被设计出来的目的之一就是为了确保构建的可复现性，[FAQ 里也有解释到](https://goproxy.cn/faq#001.000)。

设想，如果某人依赖了你的 `github.com/sunshinev/go-sword/v2 v2.0.1` 写了一个项目并用到了生产环境，可你在其后删除或篡改了该模块版本，那么带来的灾难将是不可预估的。

此外，就算 [goproxy.cn](https://goproxy.cn) 在存储中帮你删除了指定的模块版本也是毫无意义的，因为 [sum.golang.org](https://sum.golang.org) 这个官方的 [Go 模块校验和数据库](golang.org/design/25530-sumdb)已经将该模块版本的校验和数据写死进数据库，从算法设计上这一行为不可逆，也就是说校验和数据库无法帮你删掉某一特定模块版本的校验和数据，除非整库重置。

因此，你只能通过释放 `v2.0.2` 之类的比问题模块版本更大的模块版本来解决掉这一问题了。

**Comment by sunshinev** [comment]
@aofei 感谢啦，现在只能释放高版本啦~
