### ISSUE TITLE
问题：Win10 Pro(1909)遇到的一个GOPROXY不起作用的问题

### ISSUE THREAD

**Issue by jiangjianshan** [goproxy/goproxy.cn#121]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

是的

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.16.6 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=F:\Projects\go\bin
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=F:\Projects\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\Projects\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.google.cn
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.6
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build2626814047=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

在Windows 10专业版(1909)安装完微信和企业微信后，打开Vim执行:GoBinariesUpdate

## 你期望看到的结果是什么？

显示的“vim-go: Updating revive. Reinstalling github.com/mgechev/revive@lastest to folder F:\Projects\go\bin”会切换到下一个module，直到全部更新完。不确定是什么影响到了GOPROXY，有没有什么命令行方式可以去获取更多诊断信息？

## 你实际看到的结果是什么？

卡在“vim-go: Updating revive. Reinstalling github.com/mgechev/revive@lastest to folder F:\Projects\go\bin”一直不会动。但这个问题在我这台双系统的另外一个Linux系统下缺不存在，Linux下同样的GOPROXY设置，go get的速度很快，不会卡在这里

**Comment by aofei** [comment]
你好，虽然我不太清楚你这个 Windows 系统的 Vim 是在什么模拟器环境下运行的，但这个问题感觉是它所处的环境中的环境变量配置错误导致的。

你可以直接在 Vim 中执行一下 `:!go env` 来确认一下它所处的环境中的 Go 相关环境变量。

**Comment by aofei** [comment]
另外可以顺便检查一下你有没有配置系统级的 `http_proxy` 或 `https_proxy` 环境变量，经常有人在 Windows 下因为配错这个导致异常。

**Comment by jiangjianshan** [comment]
昨天经过逐一排查，发现是因为AnyShareNew_Windows_All_x64_fm-6.0.3-20181106-release-5055.exe这个云盘客户端软件安装后就会出现这个情况。关于http_proxy和https_proxy我一直是没有去配置的，不知道是不是这个云盘客户端软件安装完后引起了配置上的变化导致的。现在不想再重装系统去验证了，所以先不装这个云盘客户端，目前运行Go的升级都很正常。

**Comment by jiangjianshan** [comment]
最近发现一个解决方案，就是在把那个客户端对应的AnyShare服务在管理那里关闭掉就可以解决了
