### ISSUE TITLE
能否手动清理缓存

### ISSUE THREAD

**Issue by mimicode** [goproxy/goproxy.cn#122]
比如我给库新建一个tag,由于先修改的 go.mod 编辑器主动去下载了，而goproxy.cn 发现没有就标记这个版本是没有的。
后续我怎么请求都无法请求到。
 

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

## 你期望看到的结果是什么？

能不能手动清理你们的404标记，如这样

https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/xxxxx/xxxx@v0.0.1@nocache

可用让404的标记 失效，而不是等待一个未知的时间。或者再次发行一个新的tag

## 你实际看到的结果是什么？

新的tag立即生效

**Comment by aofei** [comment]
新建的 tag 如果不能立即生效的话，只能是一种场景，就是在打 tag 前你试图提前拉取过那个 tag 的模块版本，这种场景的模块拉取请求类型的确是模块代理应该防御的，否则很容易就被类似垃圾请求打垮。事实上这种请求很少发生，如果只是某次不小心提前拉取的话，那么其实是可以很好解决这个问题的，你只需要 `go get path@<tag-commit-hash>` 就好了，也就是说 `@` 后面不跟具体的 tag，而是跟它所指向的 commit hash。

另外缓存时间并非未知，如果你只是 `go get path`，或者 `go get path@latest`，那么平均缓存时间是一分钟，最坏情况下两分钟。

**Comment by aofei** [comment]
鉴于问题已回答，这个 issue 我就先关闭了，如果还有其他问题欢迎随时开新 issue 提问～
