### ISSUE TITLE
问题：go mod tidy网络报错：GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by IT-YUNMENGZE** [goproxy/goproxy.cn#123]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

是的

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.17.1 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yuan/.cache/go-build"
GOENV="/home/yuan/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/yuan/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/yuan/src/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/yuan/src/GoProjects/Cia-Scheduler/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build419764146=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

go.mod文件内容如下：

```
module Cia-Scheduler

go 1.17


require (
	github.com/spf13/cobra v1.1.1
	k8s.io/api v0.20.0
	k8s.io/apimachinery v0.20.0
	k8s.io/component-base v0.20.0
	k8s.io/klog v1.0.0
	k8s.io/kubernetes v1.20.0
	sigs.k8s.io/controller-runtime v0.7.0
)
```
随后我执行了go mod tidy
`yuan@yuan-PC:~/src/GoProjects/Cia-Scheduler$ go mod tidy
`
## 你期望看到的结果是什么？

运行go mod tidy后成功拉取go.mod文件中的模块

## 你实际看到的结果是什么？

网络链接报错
```
yuan@yuan-PC:~/src/GoProjects/Cia-Scheduler$ go mod tidy
go: k8s.io/kubernetes@v1.20.0 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: git ls-remote -q origin in /home/yuan/src/go/pkg/mod/cache/vcs/917454838ed90b2f0e9868490d4b59302d7a7e8f8826d51d313bd68be346ecce: exit status 128:
        fatal: 无法访问 'https://github.com/kubernetes/api/'：GnuTLS recv error (-110): The TLS connection was non-properly terminated.
```

**Comment by aofei** [comment]
你好，根据你提供的报错信息来分析，这是由于你自己项目所依赖的 `k8s.io/kubernetes@v1.20.0` 这个模块版本它本身又依赖了另外一个 `k8s.io/api@v0.0.0` 模块版本，然而 `k8s.io/api@v0.0.0` 并非实际存在，所以产生的相应请求 https://goproxy.cn/k8s.io/api/@v/v0.0.0.info 自然也就响应给你了 `404 Not Found`，于是根据你的 `GOPROXY` 配置，你的 `go` 命令在接到 `404 Not Found` 后触发了 fallback 机制自动以 `direct` 直连的方式试图前往 `https://github.com/kubernetes/api` 寻找这个 `k8s.io/api@v0.0.0`  模块版本，而此时由于你本地网络无法与 `github.com` 正常互联，于是才报了这个错误。

需要注意 `k8s.io/kubernetes@v1.20.0` 这个模块版本的 [`go.mod`](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/go.mod)  文件中包含大量的 `replace` 指示符，其中就有你遇到的这个 `k8s.io/api@v0.0.0` 问题模块版本所对应的[条目](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/go.mod#L494)。也就是说哪怕你把你现在遇到的这个问题解决了，你还很有可能会遇到其他类似的情况。

最好的解决办法是，参考 `k8s.io/kubernetes@v1.20.0` 这个模块版本的 [`go.mod`](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/go.mod)  文件，把它里面的 `replace` 移植到你自己项目的 `go.mod` 文件中。

**Comment by IT-YUNMENGZE** [comment]
非常感谢您认真细致的回答，我已经使用这个方法完美地解决了这个问题。但我有一点不太明白，我本地网络一直是通过海外VPN代理连接到`github.com`的，平时都能正常访问，也就是说是正常互联的，会和这个问题有关嘛？

Anyway, 再次感谢您及时且详细的回答！:blush:

**Comment by aofei** [comment]
这也许是跟你终端环境变量配置有关吧，用的工具是否错误地配置了 `http_proxy` 和 `https_proxy` 环境变量？据了解国内绝大多数类似工具都会把它们配错。

**Comment by IT-YUNMENGZE** [comment]
好的，再次感谢
