### ISSUE TITLE
问题： dial tcp: i/o timeout

### ISSUE THREAD

**Issue by bylings** [goproxy/goproxy.cn#124]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
你好，请补充一下问题模版，至少提供一下 `go env` 的内容，不然光凭标题是无法判断问题出在哪里的。

**Comment by aofei** [comment]
由于长时间未更新，这个 issue 我就先关闭了，如果还有其他问题欢迎随时提问（下次记得填写 issue 模版）～

**Comment by jokereven** [comment]
go version：
go version go1.17.3 linux/amd64

go env：
[root@jokereven ~]# go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/www/server/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/www/wwwroot/Golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/www/wwwroot/Golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/www/server/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/www/server/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1679719090=/tmp/go-build -gno-record-gcc-switches"

我通过本地的vscode 使用remote 连接到远程的服务器安装go tools 的时候发生了以下错误:
go get: module github.com/cosmtrek/air: Get "https://proxy.golang.org/github.com/cosmtrek/air/@v/list": dial tcp 172.217.26.241:443: i/o timeout

我通过ssh远程连接到服务器和通过vscode terminal时通过 go get 也发生了这样的错误
