### ISSUE TITLE
Installing github.com/go-delve/delve/cmd/dlv@master FAILED

### ISSUE THREAD

**Issue by assdddddff** [goproxy/goproxy.cn#125]
## Are you sure that our [FAQ](https://goproxy.cn/faq) page doesn't have the question you want to ask?
yes

## What is the output when you execute the `go version` command?

<pre>
$ go version go1.17.1 windows/amd64

</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zy\AppData\Local\go-build
set GOENV=C:\Users\zy\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\zy\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\zy\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.1
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\zy\AppData\Local\Temp\go-build2641840809=/tmp/go-build -gno-record-gcc-switches

</pre>
</details>

## What did you 
安装一些插件

## What did you see instead?
报错语句如下：
dlv-dap: failed to install dlv-dap(github.com/go-delve/delve/cmd/dlv@master): Error: Command failed: C:\Program Files\Go\bin\go.exe get -v -d github.com/go-delve/delve/cmd/dlv@master
go get: github.com/go-delve/delve/cmd/dlv@master: invalid version: Get "https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/master.info": Method Not Allowed
 no output

**Comment by aofei** [comment]
出现 `Method Not Allowed` 就很奇怪了，你自己在其他地方（比如 PowerShell 什么的）单独执行 `go get -v -d github.com/go-delve/delve/cmd/dlv@master` 会出现什么情况？

**Comment by assdddddff** [comment]
> 
> 
> 出现 `Method Not Allowed` 就很奇怪了，你自己在其他地方（比如 PowerShell 什么的）单独执行 `go get -v -d github.com/go-delve/delve/cmd/dlv@master` 会出现什么情况？

试了，没有任何输出显示

**Comment by aofei** [comment]
> 试了，没有任何输出显示

No news is good news.

没有任何输出提升就说明成功了。

OP 中那个错误你是在哪个地方执行时看到的？

**Comment by assdddddff** [comment]
> 
> 
> > 试了，没有任何输出显示
> 
> No news is good news.
> 
> 没有任何输出提升就说明成功了。
> 
> OP 中那个错误你是在哪个地方执行时看到的？

在vscode中，有个提示信息说是dlv-dap没安装，我点击install，就出现报错信息了

**Comment by aofei** [comment]
此外，顺便说一下，你的 Go 版本已经是 `1.17.1` 了，所以安装二进制时不能再用 `go get` 了，而是应该改用 `go install`，比如 `go install github.com/go-delve/delve/cmd/dlv@latest`。

**Comment by aofei** [comment]
> > > 试了，没有任何输出显示
> > 
> > 
> > No news is good news.
> > 没有任何输出提升就说明成功了。
> > OP 中那个错误你是在哪个地方执行时看到的？
> 
> 在vscode中，有个提示信息说是dlv-dap没安装，我点击install，就出现报错信息了

VS Code 本身有升级吗？具体版本号是多少？

**Comment by assdddddff** [comment]
> 
> 
> > > > 试了，没有任何输出显示
> > > 
> > > 
> > > No news is good news.
> > > 没有任何输出提升就说明成功了。
> > > OP 中那个错误你是在哪个地方执行时看到的？
> > 
> > 
> > 在vscode中，有个提示信息说是dlv-dap没安装，我点击install，就出现报错信息了
> 
> VS Code 本身有升级吗？具体版本号是多少？

1.57

**Comment by aofei** [comment]
你的 VS Code 并不是最新版本，另外顺便问一下 vscode-go 的版本有升级吗？vscode-go 的最新版本是 v0.28.1 了。

**Comment by assdddddff** [comment]
> 
> 
> 你的 VS Code 并不是最新版本（最新是 1.60），另外顺便问一下 vscode-go 的版本有升级吗？vscode-go 的最新版本是 v0.28.1 了。

昨天使用的就是最新版，同样报错，所以我才换了之前的，没升级，版本是0.27的

**Comment by aofei** [comment]
你在 VS Code 自带的 Terminal 中手动执行一下 `C:\Program Files\Go\bin\go.exe get -v -d github.com/go-delve/delve/cmd/dlv@master`，看是否报错。

另外，在 VS Code 自带的 Terminal 中检查一下 `http_proxy` 和 `https_proxy` 两个环境变量是否有值。

**Comment by assdddddff** [comment]
> 
> 
> 你在 VS Code 自带的 Terminal 中手动执行一下 `C:\Program Files\Go\bin\go.exe get -v -d github.com/go-delve/delve/cmd/dlv@master`，看是否报错。
> 
> 另外，在 VS Code 自带的 Terminal 中检查一下 `http_proxy` 和 `https_proxy` 两个环境变量是否有值。
没报错，那俩环境变量没有值

**Comment by assdddddff** [comment]
> 
> 
> > 你在 VS Code 自带的 Terminal 中手动执行一下 `C:\Program Files\Go\bin\go.exe get -v -d github.com/go-delve/delve/cmd/dlv@master`，看是否报错。
> > 另外，在 VS Code 自带的 Terminal 中检查一下 `http_proxy` 和 `https_proxy` 两个环境变量是否有值。
> > 没报错，那俩环境变量没有值

我用的是阿里云的goproxy

**Comment by aofei** [comment]
你的意思是 OP 中 `go get: github.com/go-delve/delve/cmd/dlv@master: invalid version: Get "https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/master.info": Method Not Allowed` 里面的 `goproxy.cn` 你是手动替换成的？原本是阿里云的 goproxy？如果是这样的话建议以后不要这样提问哦，不然会误导我们怀疑自己的服务是否存在异常的。

此外阿里云的那个 goproxy 的确存在一些已知问题，我之前也给他们反馈过。如果是因为 goproxy 本身存在的缺陷导致的，那就只能通过联系相关负责人员来解决了（他们网站里有反馈方式）。我们 goproxy.cn 这里目前的确从未收到过类似 `Method Not Allowed` 的问题。

**Comment by assdddddff** [comment]
> 
> 
> 你的意思是 OP 中 `go get: github.com/go-delve/delve/cmd/dlv@master: invalid version: Get "https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/master.info": Method Not Allowed` 里面的 `goproxy.cn` 你是手动替换成的？原本是阿里云的 goproxy？如果是这样的话建议以后不要这样提问哦，不然会误导我们怀疑自己的服务是否存在异常的。
> 
> 此外阿里云的那个 goproxy 的确存在一些已知问题，我之前也给他们反馈过。如果是因为 goproxy 本身存在的缺陷导致的，那就只能通过联系相关负责人员来解决了（他们网站里有反馈方式）。我们 goproxy.cn 这里目前的确从未收到过类似 `Method Not Allowed` 的问题。

我把阿里云代理删了，安装成功了。。。那代理确实有问题~，谢谢您啦

**Comment by aofei** [comment]
嗯嗯，我刚有看到你在 https://github.com/golang/go/issues/48661 这里提问。下次记得 Go 语言官方 repo 的 issues 是用来讨论语言具体相关内容的，三方工具相关的并不在那里讨论。

由于问题已解决，这个 issue 我就先关闭了哈。
