### ISSUE TITLE
Bug:  x509: certificate is not valid for any names, but wanted to match goproxy.cn

### ISSUE THREAD

**Issue by sireg** [goproxy/goproxy.cn#126]
## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.15.6 linux/loong64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="loong64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS="-mod=vendor -insecure"
GOHOSTARCH="loong64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/rpmbuild/BUILD/minio-2021.02.18/.gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/rpmbuild/BUILD/minio-2021.02.18/.gopath:/usr/share/gocode"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_loong64"
GCCGO="gccgo"
GOLOONG64="hardfloat"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/rpmbuild/BUILD/minio-2021.02.18/go.mod"
CGO_CFLAGS="-O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2"
CGO_FFLAGS="-O2"
CGO_LDFLAGS="-O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=lp64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build007085651=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## What did you do?

go get cloud.google.com/go/storage

## What is the behavior of the bug?

go: cloud.google.com/go/storage@v1.10.0: Get "https://goproxy.cn/cloud.google.com/go/storage/@v/v1.10.0.mod": x509: certificate is not valid for any names, but wanted to match goproxy.cn

**Comment by aofei** [comment]
你好，看起来是你本地的证书校验存在问题。

麻烦提供一下你在同一环境的终端下执行 `curl -Ivk https://goproxy.cn/cloud.google.com/go/storage/@v/v1.10.0.mod` 的输出内容。

**Comment by aofei** [comment]
由于长时间未回复，这个 issue 我就先关闭了哈，如果还有其他问题欢迎随时开新 issue 来提问～

**Comment by lqzlt** [comment]
> 确实是本地证书校验的问题。感谢。

遇到同样的问题，请问是怎么解决的？
