### ISSUE TITLE
 dial tcp 142.251.43.17:443: connect: connection refused

### ISSUE THREAD

**Issue by jiaxian-lin** [goproxy/goproxy.cn#127]
我根据gitlab教程，通过源码安装gitlab，这是官方教程https://docs.gitlab.com/ee/install/installation.html#install-gitlab-shell

安装的时候执行到这一步时报了一个这个错
![image](https://user-images.githubusercontent.com/71680354/140016602-accc860d-7a2b-4602-a105-0b4c28e4b58d.png)

>go: github.com/mattn/go-shellwords@v0.0.0-20190425161501-2444a32a19f4: Get "https://proxy.golang.org/github.com/mattn/go-shellwords/@v/v0.0.0-20190425161501-2444a32a19f4.mod": dial tcp 142.251.43.17:443: connect: connection refused

完整log如下：

>root@ubuntu:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:shell:install RAILS_ENV=production
mkdir -p /home/git/.ssh: OK
chmod 700 /home/git/.ssh: OK
mkdir -p /home/git/repositories: OK
chmod ug+rwX,o-rwx /home/git/repositories: OK
GOBIN="/home/git/gitlab-shell/bin" go install -ldflags "-X main.Version=unknown -X main.BuildTime=20211103.061341" ./cmd/...
go: github.com/mattn/go-shellwords@v0.0.0-20190425161501-2444a32a19f4: Get "https://proxy.golang.org/github.com/mattn/go-shellwords/@v/v0.0.0-20190425161501-2444a32a19f4.mod": dial tcp 142.251.43.17:443: connect: connection refused
make: *** [Makefile:40: bin/gitlab-shell] Error 1
rake aborted!
command failed: make build
/home/git/gitlab/lib/tasks/gitlab/shell.rake:36:in `block (5 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:34:in `each'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:34:in `block (4 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:18:in `chdir'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:18:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => gitlab:shell:install
(See full trace by running task with --trace)

我尝试过这个 但并没有用
    sudo go env -w GOPROXY=https://goproxy.cn,direct

困扰一天了，谢谢您的帮助

**Comment by aofei** [comment]
这个错误说明你的环境变量配置并没有生效，可以尝试使用 `export GOPROXY=https://goproxy.cn,direct` 的方式设置。

此外，这个 issue 创建错了位置，我转移到这里来了。

**Comment by jiaxian-lin** [comment]
> 这个错误说明你的环境变量配置并没有生效，可以尝试使用 `export GOPROXY=https://goproxy.cn,direct` 的方式设置。
> 
> 此外，这个 issue 创建错了位置，我转移到这里来了。

感谢您的解答，但问题并没有解决
<go: github.com/mattn/go-shellwords@v0.0.0-20190425161501-2444a32a19f4: Get "https://proxy.golang.org/github.com/mattn/go-shellwords/@v/v0.0.0-20190425161501-2444a32a19f4.mod": dial tcp 216.58.200.49:443: connect: connection refused

报错的地址倒是变了，此外 我还尝试了
    export GOPROXY=https://goproxy.cn  
一样不行

**Comment by aofei** [comment]
也许是因为你 `sudo -u` 切换了用户导致的，你可以尝试一下用设置 `RAILS_ENV` 同样的方式把 `GOPROXY` 环境变量放在命令里看是否可行。

**Comment by jiaxian-lin** [comment]
> 也许是因为你 `sudo -u` 切换了用户导致的，你可以尝试一下用设置 `RAILS_ENV` 同样的方式把 `GOPROXY` 环境变量放在命令里看是否可行。

我的天，这样是可行的！ 我的所有命令都是在root用户下进行的，所以我没有考虑这个问题，感谢大佬

**Comment by aofei** [comment]
鉴于问题已解决，这个 issue 我就先关闭了哈，如果还有其他问题欢迎随时创建新 issue 提问，下次记得不要创建错了位置～
