### ISSUE TITLE
设置了GOPROXY后go mod tidy失败:dial tcp 47.246.23.197:443: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by EliotCao** [goproxy/goproxy.cn#128]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.17.3 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxx\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=V:\DevTools\golang\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=V:\DevTools\golang\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\xxx\Desktop\gotest\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build4192742706=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

go mod tidy

## 你期望看到的结果是什么？

download successfully

## 你实际看到的结果是什么？

go: finding module for package rsc.io/quote
example/hello imports
        rsc.io/quote: module rsc.io/quote: Get "https://goproxy.cn/rsc.io/quote/@v/list": dial tcp 47.246.23.197:443: connectex: No connection could be made because the target machine actively refused it.

**Comment by EliotCao** [comment]
set http_proxy=“http://user:passward@ip:port”
set https_proxy=“https://user:passward@ip:port”
go mod could download in windows.

**Comment by aofei** [comment]
```
dial tcp 47.246.23.197:443: connectex: No connection could be made because the target machine actively refused it.
```

这句话表明你的本地有其他的比如 https_proxy 之类的错误配置，导致 Go 无法正常发出 http 请求。
