### ISSUE TITLE
问题：x509: certificate is not valid for any names, but wanted to match goproxy.cn

### ISSUE THREAD

**Issue by lin16342103** [goproxy/goproxy.cn#130]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.17.6 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/data/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/data/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/tools/xp-gopher-master/myweb/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3125208066=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

通过go build编译
go build -o bin/xxx
## 你期望看到的结果是什么？

无输出，成功编译

## 你实际看到的结果是什么？

go: downloading github.com/spf13/cobra v1.2.1
go: downloading github.com/spf13/viper v1.9.0
go: downloading go.uber.org/zap v1.17.0
cmd/init.go:30:2: github.com/spf13/cobra@v1.2.1: Get "https://goproxy.cn/github.com/spf13/cobra/@v/v1.2.1.zip": x509: certificate is not valid for any names, but wanted to match goproxy.cn
cmd/root.go:23:2: github.com/spf13/viper@v1.9.0: Get "https://goproxy.cn/github.com/spf13/viper/@v/v1.9.0.zip": x509: certificate is not valid for any names, but wanted to match goproxy.cn
cmd/init.go:31:2: go.uber.org/zap@v1.17.0: Get "https://goproxy.cn/go.uber.org/zap/@v/v1.17.0.zip": x509: certificate is not valid for any names, but wanted to match goproxy.cn

**Comment by aofei** [comment]
你好，请问是什么系统环境？是在容器中吗？有尝试过更新系统环境的证书吗？比如执行 `update-ca-certificates` 命令。

**Comment by lin16342103** [comment]
是在centos虚拟机下，不在容器中。没尝试过更新证书。。emmm该命令找不到

**Comment by lin16342103** [comment]
> 你好，请问是什么系统环境？是在容器中吗？有尝试过更新系统环境的证书吗？比如执行 `update-ca-certificates` 命令。

是在centos虚拟机下，不在容器中。没尝试过更新证书。。emmm该命令找不到

**Comment by aofei** [comment]
centos 下的话可以尝试执行 `update-ca-trust`。

**Comment by lin16342103** [comment]
> centos 下的话可以尝试执行 `update-ca-trust`。

使用这个命令后没有输出，但是问题仍然存在qaq

**Comment by aofei** [comment]
麻烦在问题环境下执行一下这条命令：

```bash
$ curl -Iv https://goproxy.cn/github.com/spf13/cobra/@v/v1.2.1.zip
```

并把完整输出内容贴出来我看一下。

**Comment by lin16342103** [comment]
> 

你好，在排查后发现我的虚拟机并没有连通网络！因此在解决网络问题后此问题同样被解决！感谢帮助！

**Comment by aofei** [comment]
嗯嗯问题解决了就好，那这个 issue 我就先关闭了～
