### ISSUE TITLE
Question: Is it possible to get commits that are not on the master branch

### ISSUE THREAD

**Issue by DiscreteLogarithm** [goproxy/goproxy.cn#131]
First, let me thank you for providing us with this proxy. Thanks a lot for your work.

## Are you sure that our [FAQ](https://goproxy.cn/faq) page doesn't have the question you want to ask?

Yes

## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.16 linux/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/anea/.cache/go-build"
GOENV="/home/anea/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/anea/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/anea/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2480928572=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## What did you do?

go get github.com/osmosis-labs/osmosis@v6.x

## What did you expect to see?

go: downloading github.com/osmosis-labs/osmosis v1.0.3-0.20220120021246-f2a8bb0cdd31

## What did you see instead?

go get: github.com/osmosis-labs/osmosis@v6.x: invalid version: reading https://goproxy.cn/github.com/osmosis-labs/osmosis/@v/v6.x.info: 404 Not Found
        server response: not found: fetch timed out

## Additional info

* `v6.x` is a branch in `osmosis` repository.
* I tried usingthe commit hash and I got the same result.
* After using `export GOPROXY=` (disabling the proxy), I got the result I expected.

**Comment by aofei** [comment]
Sorry for taking so long to reply to this issue. Just in case you're still interested, the problem mentioned in the OP has now been resolved. And most importantly, the request processing speed has also been significantly improved.
