### ISSUE TITLE
问题：请问当前针对于全量同步是否限制了速率

### ISSUE THREAD

**Issue by rookiefiend** [goproxy/goproxy.cn#132]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.16.7 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3376893730=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

使用了 64 个并发，大量同步镜像缓存

## 你期望看到的结果是什么？

一直全速同步镜像

## 你实际看到的结果是什么？

最开始可以达到60M，但当前仅能达到2M

**Comment by aofei** [comment]
你好，正如官网所说的那样 goproxy.cn 并没有做任何网络带宽或请求速率方面的限制，建议你可以检查一下你的本地网络以及机器配置等是否能够满足你的需求。

**Comment by aofei** [comment]
由于长时间没有回复，这个 issue 我就默认为已解决先关闭了哈，如果还有其他问题的话欢迎随时开新 issue 提问～

**Comment by rookiefiend** [comment]
好的，谢谢
