### ISSUE TITLE
问题：Mac arm 架构 vscode下载go tools失败，显示dial tcp 142.251.42.241:443: i/o timeout\n"

### ISSUE THREAD

**Issue by JJackson1024** [goproxy/goproxy.cn#134]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

确定

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

$ go version

go version go1.17.6 darwin/arm64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/wangshizheng/Library/Caches/go-build"
GOENV="/Users/wangshizheng/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wangshizheng/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wangshizheng/go"
GOPRIVATE="git.mycompany.com,github.com/my/private"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h1/f_3pvm6d35ddwsy9mmykh8x80000gn/T/go-build2075614838=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？

我将网页上出现的代码写入终端后尝试用vscode再次下载go插件但仍然失败
我注意到issue里面有一个和我类似的问题https://github.com/goproxy/goproxy.cn/issues/127
我尝试了他的解决方案，但不起作用

## 你期望看到的结果是什么？
安装成功

## 你实际看到的结果是什么？

Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs FAILED
{
"killed": false,
"code": 1,
"signal": null,
"cmd": "/usr/local/go/bin/go get -v github.com/uudashr/gopkgs/v2/cmd/gopkgs",
"stdout": "",
"stderr": "go get: module github.com/uudashr/gopkgs/v2/cmd/gopkgs: Get "[https://proxy.golang.org/github.com/uudashr/gopkgs/v2/cmd/gopkgs/@v/list\](https://proxy.golang.org/github.com/uudashr/gopkgs/v2/cmd/gopkgs/@v/list%5C)": dial tcp 142.251.42.241:443: i/o timeout\n"
}
Installing github.com/ramya-rao-a/go-outline FAILED
{
"killed": false,
"code": 1,
"signal": null,
"cmd": "/usr/local/go/bin/go get -v github.com/ramya-rao-a/go-outline",
"stdout": "",
"stderr": "go get: module github.com/ramya-rao-a/go-outline: Get "[https://proxy.golang.org/github.com/ramya-rao-a/go-outline/@v/list\](https://proxy.golang.org/github.com/ramya-rao-a/go-outline/@v/list%5C)": dial tcp 142.251.42.241:443: i/o timeout\n"

**Comment by aofei** [comment]
> "stderr": "go get: module github.com/ramya-rao-a/go-outline: Get "[https://proxy.golang.org/github.com/ramya-rao-a/go-outline/@v/list](https://proxy.golang.org/github.com/ramya-rao-a/go-outline/@v/list%5C)": dial tcp 142.251.42.241:443: i/o timeout\n"

这行错误信息表示的意思是你的 `GOPROXY` 环境变量并没有配置正确。

虽然你的 `go env` 里的 `GOPROXY` 正常，但是需要注意的是类似 VS Code、GoLand 等 IDE 的内部还有它们自己的环境变量设置项，那些设置项是会覆盖你的系统设置的，也就是说你需要单独在你的 VS Code 内再配置一下 `GOPROXY` 环境变量。

**Comment by JJackson1024** [comment]
谢谢大佬，问题已经解决，非常感谢

**Comment by aofei** [comment]
鉴于问题已解决，这个 issue 我就先关闭了哈，如果还有其他问题欢迎开新 issue 来提问～
