### ISSUE TITLE
Bug: lookup o.elastic.co on 8.8.8.8:53: no such host

### ISSUE THREAD

**Issue by tbbrave** [goproxy/goproxy.cn#137]
## What is the output when you execute the `go version` command?

<pre>
$ go version
1.18.0
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mac/Library/Caches/go-build"
GOENV="/Users/mac/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mac/workspace/pkg/mod"
GONOPROXY="github.com/xx"
GONOSUMDB="github.com/xx"
GOOS="darwin"
GOPATH="/Users/mac/"
GOPRIVATE="github.com/xx"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8c/wlmb440n21d0k655ld8nzpgr0000gn/T/go-build3107186162=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## What did you do?
My go.mod:
```require     o.elastic.co/apm/module/apmelasticsearch/v2 v2.0.0 ```

## What is the behavior of the bug?
```
go: o.elastic.co/apm/module/apmelasticsearch/v2@v2.0.0: reading https://goproxy.cn/o.elastic.co/apm/module/apmelasticsearch/v2/@v/v2.0.0.mod: 404 Not Found
        server response: not found: o.elastic.co/apm/module/apmelasticsearch/v2@v2.0.0: unrecognized import path "o.elastic.co/apm/module/apmelasticsearch/v2": https fetch: Get "https://o.elastic.co/apm/module/apmelasticsearch/v2?go-get=1": dial tcp: lookup o.elastic.co on 8.8.8.8:53: no such host
```
## Do you have any guesses?

nope

**Comment by aofei** [comment]
经测试的确无法解析到 `o.elastic.co` 的 IP 地址，所以 `goproxy.cn` 的后端自然也无法解析到，请问这是你们公司的私有服务吗？如果是的话，你需要把 `o.elastic.co` 加入你的 `GOPRIVATE` 环境变量中，并且将你的 `GOPROXY` 改为 `https://goproxy.cn,direct` 才行（`direct` 的作用是用来 fallback）。

```bash
aofei@as-server:~$ dig @8.8.8.8 o.elastic.co

; <<>> DiG 9.18.1 <<>> @8.8.8.8 o.elastic.co
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 24312
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;o.elastic.co.                  IN      A

;; AUTHORITY SECTION:
elastic.co.             900     IN      SOA     ns-1168.awsdns-18.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 6 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Fri Apr 08 21:25:04 CST 2022
;; MSG SIZE  rcvd: 126
```

**Comment by tbbrave** [comment]
不是私有服务，应该是elastic这个公司的服务。下午我还可以编译运行。

**Comment by aofei** [comment]
你的模块路径写错了，应该是 `go.elastic.co/...` 才对，你漏了个 `g`。
