### ISSUE TITLE
Bug: github.com/go-openapi/spec@v0.20.5 module downloaded by go get with env GOPROXY="https://goproxy.cn" is incorrect.

### ISSUE THREAD

**Issue by cncal** [goproxy/goproxy.cn#139]
## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.17 darwin/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cn/Library/Caches/go-build"
GOENV="/Users/cn/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cn/Workspace/golang/pkg/mod"
GOOS="darwin"
GOPATH="/Users/cn/Workspace/golang"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/Users/cn/Workspace/gosdk/go1.17"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/Users/cn/Workspace/gosdk/go1.17/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/cn/Workspace/golang/src/segment/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9d/p9d0dmmj04zfrll8cm7rndsm0000gn/T/go-build1876570548=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## What did you do?

Download the module `github.com/go-openapi/spec@v0.20.5`:

```shell
GOPROXY="https://goproxy.cn" go get github.com/go-openapi/spec@v0.20.5 
```

and check the `go.sum` file of the module which located at `$GOPATH/pkg/mod/github.com/go-openapi/spec@v0.20.5`:

```text
github.com/PuerkitoBio/purell v1.1.1 h1:WEQqlqaGbrPkxLJWfBwQmfEAE1Z7ONdDLqrN38tNFfI=
github.com/PuerkitoBio/purell v1.1.1/go.mod h1:c11w/QuzBsJSee3cPx9rAFu61PvFxuPbtSwDGJws/X0=
github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 h1:d+Bc7a5rLufV/sSk/8dngufqelfh6jnri85riMAaF/M=
github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578/go.mod h1:uGdkoq3SwY9Y+13GIhn11/XLaGBb4BfwItxLd5jeuXE=
github.com/creack/pty v1.1.9/go.mod h1:oKZEueFk5CKHvIhNR5MUki03XCEU+Q6VDXinZuGJ33E=
github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
...
```

the `go.sum` file differs from https://github.com/go-openapi/spec/blob/v0.20.5/go.sum.

## What is the behavior of the bug?

Downloaded module by `go get` with env GOPROXY="https://goproxy.cn" is not the same with the source code.

## Do you have any guesses?

I think the possible situation is: the author of the `github.com/go-openapi/spec` tagged 0.20.5, and then it was pulled by goproxy.cn and cached. But the author found a small problem and fixed it the next day(https://github.com/go-openapi/spec/commits/v0.20.5), then re-tagged 0.20.5.

**Comment by cncal** [comment]
It can be downloaded successfully in my environment(in particular `GOSUMDB="sum.golang.google.cn"`) stating that the checksum for `github.com/go-openapi/spec@v0.20.5`  in `sum.golang.google.cn` is also based on the incorrect source code. :(

**Comment by aofei** [comment]
你好，这种情况只有一种解释，也就是你说的那样，作者强行篡改了已发布的模块版本。

注意模块代理被设计的初衷就是为了防止此类情况发生，比如某个知名模块被人以强行篡改的方式植入了恶意代码，或者有人删库跑路之类的。这是 Go modules 设计里保证 100% 可复现构建的一种方式。

此外，对于从 [goproxy.cn](https://goproxy.cn) 上拉取的模块版本数据是完全可信的，你只需要把 `GOSUMDB` 设置为 `sum.golang.org`（官方默认值），`go` 命令就会在本地帮你校验的，不匹配的数据是会报错的。也正因为每一份模块版本数据都被写入了 `sum.golang.org`，这样导致模块代理没法做到比如“删除代理中的缓存，重新回源抓一份这种”操作，因为 sumdb 从算法上是不可逆的。因此解决方案只有联系作者，告诉他这个情况，然后让他发个新的补丁版，并且告诉他以后错了就错了不要再强行篡改了。

**Comment by cncal** [comment]
If someone wants to get the "correct" source code, 

```shell
GOPROXY="https://goproxy.io" GOSUMDB=gosum.io+ce6e7565+AY5qEHUk/qmHc5btzW45JVoENfazw8LielDsaI+lEbq6 go get github.com/go-openapi/spec@v0.20.5 
```

works.

**Comment by aofei** [comment]
换一个代理的确可以解决这个问题，需要注意必须同时更换或关闭 GOSUMDB，否则会出现校验失败的情况。

鉴于这不是一个 bug，issue 我就先关闭啦，如果还有其他问题欢迎随时开新 issue 提问～
