### ISSUE TITLE
Question: docker build base on golang:1.16-alpine3.15 imgae report error

### ISSUE THREAD

**Issue by hjinbi** [goproxy/goproxy.cn#140]
## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.16.11 linux/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.11"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/usr/src/ricecooker-control-grpc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2991513838=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## What did you do?

docker build base on  golang:1.16-alpine3.15 imgae ，use go mod download

### os version :
CentOS Linux release 7.7.1908 (Core)

### docker verison:
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:38:53 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:37:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

## What did you expect to see?

go: downloading github.com/gin-gonic/gin v1.7.4

## What did you see instead?

go: github.com/gin-gonic/gin@v1.7.4: Get "https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod": stream error: stream ID 13; INTERNAL_ERROR; received from peer

**Comment by aofei** [comment]
你好，这个错误通常是跟 Go 标准库里的 HTTP/2 实现存在 bug 有关，你在[这里](https://github.com/golang/go/issues)也可以搜索到相关的 issues。遇到这种错误我们这边并不能提供多少帮助，毕竟错误是发生在你那边的本地客户端和 [goproxy.cn](https://goproxy.cn) 这边的 CDN 厂商服务器之间的，所以只能建议你在发生这种错误后重试一下。

此外，[goproxy.cn](https://goproxy.cn) 这个 repo 这里可以用中文的，因为它主要服务于大陆。

**Comment by hjinbi** [comment]
通过[goproxy.cn](https://goproxy.cn/)官网，能进行联系的渠道就是github的issue，同一网络下，windows系统没出现过这个问题。在镜像构建的途中，不管是以alpine、centos还是ubuntu都是必现的，经过50次重试，结果是一样的。

**Comment by hjinbi** [comment]
更换另外一个全球代理源不会出现以上的问题

**Comment by aofei** [comment]
从 [goproxy.cn](https://goproxy.cn) 的日志来分析，今天截止目前整个服务还并没有产生任何错误响应，也就是说你那边的错误请求并没有到达源站，还在 CDN 那里时就已经出问题了。

如果是 100% 可复现的，那希望你能提供一下这两种情况下的结果输出，便于这边向 CDN 厂商反馈：

```bash
$ GODEBUG=http2client=0 go get github.com/gin-gonic/gin@v1.7.4
```

```bash
$ GODEBUG=http2debug=2 go get github.com/gin-gonic/gin@v1.7.4
```

解释一下，第一种情况的意思是通过设置 `GODEBUG=http2client=0` 环境变量来临时禁用 Go 标准库里的 HTTP/2 客户端实现，只采用 HTTP/1.x 的实现；第二种情况的意思是启用 HTTP/2 客户端实现，并且尽可能多地打印信息。

**Comment by hjinbi** [comment]
第一种情况
```
$ GODEBUG=http2client=0 go get github.com/gin-gonic/gin@v1.7.4

go version go1.16.11 linux/amd64
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.11"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/usr/src/ricecooker-control-grpc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2536539934=/tmp/go-build -gno-record-gcc-switches"
go: github.com/gin-gonic/gin@v1.7.4: Get "https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod": EOF
```
第二种情况
```
$ GODEBUG=http2debug=2 go get github.com/gin-gonic/gin@v1.7.4
go version go1.16.11 linux/amd64
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.11"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/usr/src/ricecooker-control-grpc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build940084568=/tmp/go-build -gno-record-gcc-switches"
go: github.com/gin-gonic/gin@v1.7.4: Get "https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod": stream error: stream ID 19; INTERNAL_ERROR; received from peer
```

**Comment by aofei** [comment]
第一种情况 EOF 就很诡异了，麻烦你用 curl 测试一下你那边跟 CDN 厂商边缘服务器通信的详情：

```bash
$ curl -iv --http1.1 https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod
```

```bash
$ curl -iv --http2 https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod
```

**Comment by hjinbi** [comment]
curl http1.1
```
Step 5/14 : RUN curl -iv --http1.1 https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod
 ---> Running in bd1707e1c554
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 112.54.108.85:443...
* Connected to goproxy.cn (112.54.108.85) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [25 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2775 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.goproxy.cn
*  start date: Aug  2 00:00:00 2021 GMT
*  expire date: Aug 26 23:59:59 2022 GMT
*  subjectAltName: host "goproxy.cn" matched cert's "goproxy.cn"
*  issuer: C=CN; O=TrustAsia Technologies, Inc.; OU=Domain Validated SSL; CN=TrustAsia TLS RSA CA
*  SSL certificate verify ok.
} [5 bytes data]
> GET /github.com/gin-gonic/gin/@v/v1.7.4.mod HTTP/1.1
> Host: goproxy.cn
> User-Agent: curl/7.74.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [249 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [249 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* TLSv1.3 (IN), TLS alert, close notify (256):
{ [2 bytes data]
* Empty reply from server
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
} [5 bytes data]
* TLSv1.3 (OUT), TLS alert, close notify (256):
} [2 bytes data]
curl: (52) Empty reply from server
```
curl http2
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 112.54.108.85:443...
* Connected to goproxy.cn (112.54.108.85) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2775 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.goproxy.cn
*  start date: Aug  2 00:00:00 2021 GMT
*  expire date: Aug 26 23:59:59 2022 GMT
*  subjectAltName: host "goproxy.cn" matched cert's "goproxy.cn"
*  issuer: C=CN; O=TrustAsia Technologies, Inc.; OU=Domain Validated SSL; CN=TrustAsia TLS RSA CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x564eb51af560)
} [5 bytes data]
> GET /github.com/gin-gonic/gin/@v/v1.7.4.mod HTTP/2
> Host: goproxy.cn
> user-agent: curl/7.74.0
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [249 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [249 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host goproxy.cn left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by aofei** [comment]
经测试这边通过 `curl -iv --http1.1 --resolve goproxy.cn:443:112.54.108.81 https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod` 访问得到了同样的结果，所以初步判定是 CDN 边缘节点那边的问题。

此外，请提供一下 DNS 解析数据：

```bash
$ dig goproxy.cn
```

如果你不介意的话，麻烦也提供一下你那边的客户端公网 IP：

```bash
$ curl cip.cc
```

**Comment by hjinbi** [comment]
我有点疑惑，因为这个问题出现在docker 镜像构建过程中，如果是服务器本系统环境，不会出现。而这两者的公网ip是一致的

```
Step 7/15 : RUN dig goproxy.cn
 ---> Running in 3a7e7abceed6

; <<>> DiG 9.16.27 <<>> goproxy.cn
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60088
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;goproxy.cn.                    IN      A

;; ANSWER SECTION:
goproxy.cn.             217     IN      CNAME   goproxy.cn.qiniudns.com.
goproxy.cn.qiniudns.com. 63     IN      CNAME   qiniuopencdn.jomodns.com.
qiniuopencdn.jomodns.com. 63    IN      A       36.156.94.41
qiniuopencdn.jomodns.com. 63    IN      A       36.156.36.41

;; Query time: 47 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Fri Apr 29 08:43:23 UTC 2022
;; MSG SIZE  rcvd: 143
```

**Comment by aofei** [comment]
有可能你的 Docker 环境配置的 DNS 服务器和你宿主系统中的不一致，因此才导致了拿到的边缘节点 IP 也不一致，比如你现在拿到的这个 `36.156.94.41` 在我这边测试就是正常的：

```bash
$ curl -iv --http1.1 --resolve goproxy.cn:443:36.156.36.41 https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.4.mod
```

**Comment by aofei** [comment]
> module github.com/gin-gonic/gin
> 
> go 1.13
> 
> require (
>         github.com/gin-contrib/sse v0.1.0
>         github.com/go-playground/validator/v10 v10.4.1
>         github.com/golang/protobuf v1.3.3
>         github.com/json-iterator/go v1.1.9
>         github.com/mattn/go-isatty v0.0.12
>         github.com/stretchr/testify v1.4.0
>         github.com/ugorji/go/codec v1.1.7
>         gopkg.in/yaml.v2 v2.2.8
> )

嗯，通过这样子访问你的 Docker 构建时也能拿到正常的结果了，这说明诡异的 DNS 解析情况是只发生在你的 Go net.Dialer 了，那这样就要排除是 CDN 节点的问题了。

那就需要排查一下为什么你本地的 Go net.Dialer 和 dig、curl 等拿到的 DNS 解析结果不一致，比如你可以分别尝试：

```bash
$ GODEBUG=netdns=go+1 GODEBUG=http2client=0 go get github.com/gin-gonic/gin@v1.7.4
```

以及

```bash
$ GODEBUG=netdns=cgo+1 GODEBUG=http2client=0 go get github.com/gin-gonic/gin@v1.7.4
```

解释一下，第一种情况的意思是让 Go net.Dialer 使用纯 Go 实现的 DNS resolver，第二种情况是使用 CGO 实现的。其中的 `+1` 意思是尽可能多地打印调试信息。

**Comment by aofei** [comment]
梳理一下。

已知构建过程中所用的是宿主机中的 DNS 配置，从你在[这里](https://github.com/goproxy/goproxy.cn/issues/140#issuecomment-1113089513)提供的两条 `dig goproxy.cn` 结果可以看出直接通过宿主机的 DNS 配置可以拿到正常的节点 IP（节点是否正常可以直接通过 `curl --resolve` 来验证），那么说明所配置的 DNS 服务器（`114.114.114.114`）返回了正常的结果。

但是，构建时通过 `curl` 或 `go get` 访问却出现了异常，异常的原因是它们拿到的始终是一个固定的且**已经下线**了的 CDN 节点 IP（`112.54.108.81`）。（p.s. 稍微解释一下，CDN 的节点并非固定的，是存在比如故障、更新等变化的，因此才要依赖 DNS 机制来实现动态控制）

你分别通过 `dig`、`curl`、`go get` 拿到的节点 IP 并不一致，也就是说你的 `curl`、`go get` 并没有像 `dig` 那样使用你宿主机中配置的 DNS 服务器（`114.114.114.114`）来解析域名。这种情况可以有一种解释，就是你的环境在本地为 `goproxy.cn` 这个 host 强制指定了 IP，比如可以通过修改 `/etc/hosts` 来指定。这时候，类似 `curl`、`go get` 等工具会优先遵循 `files`（比如 `/etc/hosts`），其次才是 `dns`（比如 `/etc/resolv.conf`）。

这属于本地 DNS 问题，如果确定本地环境并不存在类似修改 `/etc/hosts` 等情况，那可以通过刷新本地 DNS 缓存来看是否能解决，除此之外暂时还没有想到别的解决办法。

**Comment by aofei** [comment]
你好，经过排查，七牛云在内部并不能找到你在 docker build 时拿到的这个 CDN 节点 IP `112.54.108.81`，换句话说，这个节点的确“已下线”。按理说节点下线都是有过渡期的，并不是立即下线，至少在相应 DNS 解析过期前（TTL 其实很短）是不会下线的。这些都是 CDN 的正常行为，所以不属于 bug。

至于你的在宿主机上访问和在 docker build 时访问为什么拿到了不同的节点 IP，我也非常好奇，如果还有后续的话希望你能再反馈一下（在这个 issue 里继续评论即可）。

由于跟服务本身无关，这个 issue 我就先关闭了，如果还有其他问题欢迎随时开新 issue 提问～
