### ISSUE TITLE
设置GOPROXY无效，安装依赖包出现 dial tcp 172.217.24.241:443: i/o timeout

### ISSUE THREAD

**Issue by x-xkang** [goproxy/goproxy.cn#142]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.17 darwin/amd64

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/videopls/Library/Caches/go-build"
GOENV="/Users/videopls/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/videopls/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/videopls/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n9/wznqvvfs0j1fpr8jz_q68_8w0000gn/T/go-build2655739206=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？
使用 `fyne-cross` 和 `docker` 编译  基于`fyne`的项目出现  `go: fyne.io/fyne/v2@v2.1.4: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.1.4.mod": dial tcp 172.217.24.241:443: i/o timeout`

已经设置了 `GO111MODULE` 和 `GOPROXY` 但是下载包还是调用的如上所示 `https://proxy.golang.org`

## 你期望看到的结果是什么？

安装成功

## 你实际看到的结果是什么？

安装超时，并且 GOPROXY被覆盖（看到其他的issure基本是1，未设置代理，2，代理被覆盖），但是我在`Goland` 和 `item2` 上 打印 `go env` 均为已设置代理和开启 `mod`，但还是出现超时的问题

**Comment by x-xkang** [comment]
找到问题了，是在容器里面出现的timeout，容器里面的go默认是没有修改代理的，需要在编译时添加代理参数，问题已解决，可以关闭了，谢谢

**Comment by aofei** [comment]
由于问题已得到解决，这个 issue 我就关闭了哈，如果还有其他问题欢迎再提问～
