### ISSUE TITLE
问题：请问如何快速的获取编译安装zabbix_agentd2时需要的go依赖包？

### ISSUE THREAD

**Issue by 1shenss** [goproxy/goproxy.cn#147]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
抱歉没能理解你想表达的意思。

**Comment by aofei** [comment]
由于太久没有回应，这个 issue 我就先关闭了，如果还有其他问题欢迎随时开新 issue 提问～
