### ISSUE TITLE
问题：从7月31号开始，使用go mod tidy拉取依赖时，概率失败，read: connection reset by peer

### ISSUE THREAD

**Issue by zengfc0** [goproxy/goproxy.cn#148]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.17.8 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jenkins/.cache/go-build"
GOENV="/home/jenkins/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/var/go/pkg/mod"
GONOPROXY="git.hyperchain.cn"
GONOSUMDB="git.hyperchain.cn"
GOOS="linux"
GOPATH="/var/go"
GOPRIVATE="git.hyperchain.cn"
GOPROXY="https://goproxy.cn/,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2695729524=/tmp/go-build -gno-record-gcc-switches"

## 你做了什么？

go mod tidy拉取依赖

## 你期望看到的结果是什么？

依赖拉取成功

## 你实际看到的结果是什么？

概率出现拉取失败，失败概率很高，高并发时失败率更高，是否有对连接数做限制？
失败日志有以下几种：
1.
github.com/prometheus/common/model: github.com/prometheus/common@v0.30.0: Get "https://goproxy.cn/github.com/prometheus/common/@v/v0.30.0.zip": read tcp 192.168.1.8:59248->101.71.80.132:443: read: connection reset by peer
2.
github.com/Hyperledger-TWGC/tjfoc-gm/sm2: github.com/Hyperledger-TWGC/tjfoc-gm@v1.4.0: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
3.
go: github.com/go-openapi/analysis@v0.21.2 requires
  	github.com/go-openapi/strfmt@v0.21.0 requires
  	go.mongodb.org/mongo-driver@v1.7.3 requires
  	github.com/gobuffalo/genny@v0.1.1 requires
  	github.com/gobuffalo/mapi@v1.0.2: Get "https://goproxy.cn/github.com/gobuffalo/mapi/@v/v1.0.2.mod": http2: client connection force closed via ClientConn.Close

**Comment by aofei** [comment]
其实类似这种问题就比较难调，因为难以 100% 复现。而且通常又因网络、设备、系统而异，比如我就从未遇见过。不过可以跟你确定的是我们并没有设置任何限制，无论是下行带宽还是请求速率我们都是完全放开了的。

```bash
$ curl -Is https://goproxy.cn/github.com/prometheus/common/@v/v0.30.0.zip | grep last-modified
last-modified: Mon, 26 Jul 2021 16:25:13 GMT
```

鉴于你贴出的这个失败请求所对应的是一个较老的文件，所以可以排除是我们后台服务的 bug 所导致的失败。因此，问题应该是出在了本地客户端与 CDN 边缘节点之间的通讯过程。Go 的 HTTP/2 客户端实现的确存在已知的 bug 在高并发时可能会导致你贴出的这个错误发生，所以究竟是本地客户端的问题还是 CDN 边缘节点的问题就变得比较难判断了。

稍后我把这个 issue 标记下，周末时我们这边尝试更改一下国内的 CDN 线路，看是否能够减少此类问题的产生。

**Comment by zengfc0** [comment]
> 其实类似这种问题就比较难调，因为难以 100% 复现。而且通常又因网络、设备、系统而异，比如我就从未遇见过。不过可以跟你确定的是我们并没有设置任何限制，无论是下行带宽还是请求速率我们都是完全放开了的。
> 
> ```shell
> $ curl -Is https://goproxy.cn/github.com/prometheus/common/@v/v0.30.0.zip | grep last-modified
> last-modified: Mon, 26 Jul 2021 16:25:13 GMT
> ```
> 
> 鉴于你贴出的这个失败请求所对应的是一个较老的文件，所以可以排除是我们后台服务的 bug 所导致的失败。因此，问题应该是出在了本地客户端与 CDN 边缘节点之间的通讯过程。Go 的 HTTP/2 客户端实现的确存在已知的 bug 在高并发时可能会导致你贴出的这个错误发生，所以究竟是本地客户端的问题还是 CDN 边缘节点的问题就变得比较难判断了。
> 
> 稍后我把这个 issue 标记下，周末时我们这边尝试更改一下国内的 CDN 线路，看是否能够减少此类问题的产生。

我们这边CI基本上90%会因为上面的原因失败，上面只贴出了一个请求，还有很多，后面我会列举一些。之前没有出现过这个问题，清理完go cache，执行go mod 基本上必现。增加cache的话基本上不太会失败。我们尝试了很多客户端结果都一样，很有可能是CDN的问题。
下面是部分其他失败的请求：
github.com/golang/protobuf/proto: github.com/golang/protobuf@v1.5.2: Get "https://goproxy.cn/github.com/golang/protobuf/@v/v1.5.2.zip": read tcp 192.168.1.7:60654->101.71.80.132:443: read: connection reset by peer
github.com/cespare/xxhash/v2: github.com/cespare/xxhash/v2@v2.1.2: Get "https://goproxy.cn/github.com/cespare/xxhash/v2/@v/v2.1.2.zip": read tcp 192.168.1.7:60654->101.71.80.132:443: read: connection reset by peer
github.com/VictoriaMetrics/fastcache: github.com/VictoriaMetrics/fastcache@v1.5.2: Get "https://goproxy.cn/github.com/%21victoria%21metrics/fastcache/@v/v1.5.2.zip": read tcp 192.168.1.7:60654->101.71.80.132:443: read: connection reset by peer
github.com/StackExchange/wmi@v0.0.0-20170410192909-ea383cf3ba6e: Get "https://goproxy.cn/github.com/%21stack%21exchange/wmi/@v/v0.0.0-20170410192909-ea383cf3ba6e.mod": read tcp 192.168.1.8:42006->101.69.194.219:443: read: connection reset by peer
github.com/yuin/gopher-lua@v0.0.0-20191220021717-ab39c6098bdb: Get "https://goproxy.cn/github.com/yuin/gopher-lua/@v/v0.0.0-20191220021717-ab39c6098bdb.mod": read tcp 192.168.1.48:39784->101.69.194.219:443: read: connection reset by peer
github.com/smartystreets/assertions: github.com/smartystreets/assertions@v1.2.0: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
github.com/BurntSushi/toml: github.com/BurntSushi/toml@v0.3.1: Get "https://goproxy.cn/github.com/%21burnt%21sushi/toml/@v/v0.3.1.zip": read tcp 192.168.0.4:39830->101.71.80.132:443: read: connection reset by peer
github.com/google/go-cmp/cmp: github.com/google/go-cmp@v0.5.6: Get "https://goproxy.cn/github.com/google/go-cmp/@v/v0.5.6.zip": read tcp 192.168.0.4:39830->101.71.80.132:443: read: connection reset by peer

**Comment by aofei** [comment]
麻烦那边有空帮忙测试一下，在 CI 里把 `goproxy.cn` 强制解析到我们的香港 CDN 节点 `163.181.33.228`，比如可以写进 `/etc/hosts` 里，然后再尝试一下看是否还会出现这种问题。

**Comment by zengfc0** [comment]
> 麻烦那边有空帮忙测试一下，在 CI 里把 `goproxy.cn` 强制解析到我们的香港 CDN 节点 `163.181.33.228`，比如可以写进 `/etc/hosts` 里，然后再尝试一下看是否还会出现这种问题。

使用默认的CDN节点`101.71.80.132`和`101.69.194.219`，各测试了3次都失败了;
使用CDN节点`112.240.62.41`，测试了3次，都成功了，没有问题
使用香港 CDN 节点`163.181.33.228`，测试了1次失败超时了，应该是网络延时和丢包比较高。
`ping 163.181.33.228 -c 10`
PING 163.181.33.228 (163.181.33.228) 56(84) bytes of data.
64 bytes from 163.181.33.228: icmp_seq=2 ttl=46 time=365 ms
64 bytes from 163.181.33.228: icmp_seq=4 ttl=46 time=364 ms
64 bytes from 163.181.33.228: icmp_seq=5 ttl=46 time=365 ms
64 bytes from 163.181.33.228: icmp_seq=6 ttl=46 time=369 ms
64 bytes from 163.181.33.228: icmp_seq=9 ttl=46 time=366 ms

--- 163.181.33.228 ping statistics ---
10 packets transmitted, 5 received, 50% packet loss, time 9008ms
rtt min/avg/max/mdev = 364.863/366.390/369.646/1.729 ms

你们可以测试下CDN节点`101.71.80.132`和`101.69.194.219`，这两个节点，可能需要修复或迁移。

**Comment by aofei** [comment]
> 你们可以测试下CDN节点`101.71.80.132`和`101.69.194.219`，这两个节点，可能需要修复或迁移。

一开始我就已经测试过 `101.71.80.132` 了，高并发并没有出现问题，稍后我再试试 `101.69.194.219`。不过这个有时候也可能跟请求方的运营商有关，所以不同的网络下可能表现并不一致。我看看能不能在多个运营商下都测试测试。

上面两个节点跟 `112.240.62.41` 同属一条线路，所以应该是 CDN 节点的锅没跑了。

**Comment by Kabochar** [comment]
你好，这边有同样  go mod tidy 拉取失败的问题，配合Dockerfile 有时候拉取有问题，有时候又没问题。特玄学：）

错误信息
```
pilipili/api imports
	github.com/gin-contrib/sessions: github.com/gin-contrib/sessions@v0.0.1: Get "https://goproxy.cn/github.com/gin-contrib/sessions/@v/v0.0.1.zip": dial tcp: lookup goproxy.cn on 119.29.29.29:53: no such host
pilipili/api imports
	github.com/gin-gonic/gin: github.com/gin-gonic/gin@v1.8.1: Get "https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.8.1.zip": dial tcp: lookup goproxy.cn on 119.29.29.29:53: no such host
```

## go verison
Dockerfile images lasted

## dockerfile片段
```
FROM golang as build

# 设置 Proxy
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

RUN curl -ik https://goproxy.cn/golang.org/x/text/@latest 

ADD . /pilipili

WORKDIR /pilipili

RUN go mod tidy

# 交叉编译
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api_server
````

构建过程中，curl 那里能正确返回，返回信息具体如下
```
Step 4/21 : RUN curl -ik https://goproxy.cn/golang.org/x/text/@latest
 ---> Running in 001048efd3e3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    50  100    50    0     0    126      0 --:--:-- --:--:-- --:--:--   127
HTTP/2 200 
server: openresty
date: Fri, 05 Aug 2022 10:00:14 GMT
content-type: application/json; charset=utf-8
content-length: 50
cache-control: public, max-age=60
strict-transport-security: max-age=31536000
age: 0
ctl-cache-status: MISS from js-changzhou7-ca10, MISS from gd-dongguan3-ca16
request-id: e1cfcecf51b67adbd9406cb5476d4692

{"Version":"v0.3.7","Time":"2021-08-10T18:28:16Z"}
```

**Comment by aofei** [comment]
@Kabochar 

你好你这报错信息是 DNS 问题了，你本地所用的 DNS 服务器（119.29.29.29）没法正常解析 goproxy.cn 这个域名。不过也挺好奇怪的，你用的这个是 DNSPod 的公共 DNS 服务器，而我们的域名所用的 DNS 也是在 DNSPod 上，居然还能 no such host，不知道具体原因，有可能是 DNSPod 又抽风了。

顺带提一下，公共 DNS 服务器的话，表示还是建议用阿里云家的 223.5.5.5 和 223.6.6.6，节点更多更靠谱。

**Comment by Kabochar** [comment]
@aofei

**Comment by aofei** [comment]
@Kabochar 这可能是系统问题导致 Go 标准库里的纯 Go DNS 实现不正常，可以尝试一下在容器里设置环境变量 GODEBUG=netdns=cgo 强制改成使用 cgo 实现。

**Comment by Kabochar** [comment]
@aofei 
设置这个 `GODEBUG=netdns=cgo` 还是不行。这边定位到具体原因了，Docker golang lasted images 有问题，强制改成 1.17 就好了
Dockerfile example
```
# FROM golangas build # 旧的定义
FROM golang:1.17 as build # 更改之后的定义

# 设置 Proxy
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

RUN curl -ik https://goproxy.cn/golang.org/x/text/@latest

ADD . /pilipili

WORKDIR /pilipili

RUN go mod tidy

# 交叉编译
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api_server
```
谢谢提供思路支持，祝周末愉快呢。😁

**Comment by aofei** [comment]
@zengfc0 

这边国内线路已调整完成，按照前面你在 https://github.com/goproxy/goproxy.cn/issues/148#issuecomment-1202265228 里提到的，现在 DNS 返回给你的 CDN 节点应该都是你用着正常的，如果没有，建议刷新本地 DNS 缓存什么的。

感谢反馈！❤️

**Comment by zengfc0** [comment]
好的，现在的节点没有问题，非常感谢


------------------ 原始邮件 ------------------
发件人: Aofei Sheng ***@***.***&gt;
发送时间: 2022年8月8日 12:10
收件人: goproxy/goproxy.cn ***@***.***&gt;
抄送: zengfc0 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[goproxy/goproxy.cn] 问题：从7月31号开始，使用go mod tidy拉取依赖时，概率失败，read: connection reset by peer (Issue #148)





 
@zengfc0
 
这边国内线路已调整完成，按照前面你在 #148 (comment) 里提到的，现在 DNS 返回给你的 CDN 节点应该都是你用着正常的，如果没有，建议刷新本地 DNS 缓存什么的。
 
感谢反馈！❤️

**Comment by aofei** [comment]
那这个 issue 我就先关闭了，如果还有其他问题欢迎随时反馈～

**Comment by walnut-tom** [comment]
现在还有这个问题
	github.com/apache/dubbo-go/config imports
	github.com/apache/dubbo-go/cluster/router imports
	github.com/RoaringBitmap/roaring: github.com/RoaringBitmap/roaring@v0.9.4: read "https://goproxy.cn/github.com/%21roaring%21bitmap/roaring/@v/v0.9.4.zip": http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""

**Comment by myysophia** [comment]
现在还有问题:
```
32.78 go: sigs.k8s.io/structured-merge-diff/v4@v4.6.0: read "https://goproxy.cn/sigs.k8s.io/structured-merge-diff/v4/@v/v4.6.0.zip": stream error: stream ID 881; INTERNAL_ERROR; received from peer
```

**Comment by myysophia** [comment]
关键是githubaction 跑的，应该网络不会是问题
