### ISSUE TITLE
问题：go-playground/locales 下载特别慢

### ISSUE THREAD

**Issue by chenobdo** [goproxy/goproxy.cn#151]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
抱歉提供的信息太少，没法为你解答，下次请填好事先准备好的 issue 模版，可以节省大家的时间。
