### ISSUE TITLE
问题：如何利用托管安装 go gin

### ISSUE THREAD

**Issue by s8628** [goproxy/goproxy.cn#152]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
你好，麻烦下次请先填好实现准备的 issue 模板，可以节约大家的时间，仅是标题中的几个字并不能有效地让人理解你具体想做什么。
