### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by DongzhouTImes** [goproxy/goproxy.cn#154]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.19.2 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>

<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zhouy/Library/Caches/go-build"
GOENV="/Users/zhouy/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zhouy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zhouy/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9q/nkh51qgn4bzfpn1n6v4wr34r0000gn/T/go-build982186441=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？
执行~/go/bin/fyne-cross windows进行编译，但是fyne-cross的工作方式是拉取镜像进行编译打包，但是镜像中的没有更改GOPROXY="https://goproxy.cn"代理配置，依然从https://proxy.golang.org获取版本，请问是否有办法在fyne-cross中使用代理

## 你期望看到的结果是什么？
fyne-cross使用https://goproxy.cn地址设置代理

## 你实际看到的结果是什么？

[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /Users/zhouy/go/src/Project/synTool/fyne-cross/bin/windows-amd64
[✓] "dist" dir cleaned: /Users/zhouy/go/src/Project/synTool/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /Users/zhouy/go/src/Project/synTool/fyne-cross/tmp/windows-amd64
[i] Checking for go.mod: /Users/zhouy/go/src/Project/synTool/go.mod
[✓] go.mod found
[i] Building binary...
go: downloading fyne.io/fyne/v2 v2.2.3
go: downloading github.com/fsnotify/fsnotify v1.6.0
ui/publishSyn.go:8:2: fyne.io/fyne/v2@v2.2.3: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.2.3.zip": dial tcp 142.251.42.241:443: i/o timeout
main.go:6:2: fyne.io/fyne/v2@v2.2.3: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.2.3.zip": dial tcp 142.251.42.241:443: i/o timeout
ui/publishSyn.go:9:2: fyne.io/fyne/v2@v2.2.3: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.2.3.zip": dial tcp 142.251.42.241:443: i/o timeout
ui/publishSyn.go:10:2: fyne.io/fyne/v2@v2.2.3: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.2.3.zip": dial tcp 142.251.42.241:443: i/o timeout
ui/publishSyn.go:14:2: fyne.io/fyne/v2@v2.2.3: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.2.3.zip": dial tcp 142.251.42.241:443: i/o timeout
ui/publishSyn.go:15:2: fyne.io/fyne/v2@v2.2.3: Get "https://proxy.golang.org/fyne.io/fyne/v2/@v/v2.2.3.zip": dial tcp 142.251.42.241:443: i/o timeout
util/LisenLog.go:5:2: github.com/fsnotify/fsnotify@v1.6.0: Get "https://proxy.golang.org/github.com/fsnotify/fsnotify/@v/v1.6.0.zip": dial tcp 142.251.42.241:443: i/o timeout
[✗] exit status 1

**Comment by aofei** [comment]
fyne-cross 跨平台编译的本质是包装了一下 docker，所以实际编译过程的环境和 host 的环境并不相同，你在 host 中的 GOPROXY 配置也就没有任何意义了。

解决办法是在执行 fyne-cross 命令时加上 --env 参数，即 `fyne-cross --env GOPROXY=https://goproxy.cn`。
