### ISSUE TITLE
问题：mod过期清除的策略

### ISSUE THREAD

**Issue by 404669366** [goproxy/goproxy.cn#155]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

是

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.18.1 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64 
set GOVCS=
set GOVERSION=go1.18.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Users\Desktop\game_backend\src\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build3175909172=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

就是想问问一个mod的过期清除的策略QAQ

## 你期望看到的结果是什么？

就是想问问一个mod的过期清除的策略QAQ

## 你实际看到的结果是什么？

就是想问问一个mod的过期清除的策略QAQ

**Comment by aofei** [comment]
抱歉我没太理解你的问题，具体是指哪里的清除策略？你期望看到的结果是什么？

**Comment by aofei** [comment]
由于太长时间没有任何回复，这个 issue 我就先关闭了，如果还有别的问题欢迎随时开新 issue 来提问～
