### ISSUE TITLE
问题：访问不存在的库时没有正确的返回 HTTP Status，返回 HTTP Status 500

### ISSUE THREAD

**Issue by sunfuze** [goproxy/goproxy.cn#157]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？
没有

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.19 darwin/arm64

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>

$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/xxx/go/bin"
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GONOPROXY=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jj/4_7w94_j6w37pf00m7c5cglm0000gn/T/go-build668542595=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre>
</details>

## 你做了什么？

执行

```
$ GOPROXY=https://goproxy.cn go get git.xxx.cm/abc
```

## 你期望看到的结果是什么？

返回 404

## 你实际看到的结果是什么？

报 500 错误，如下：

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/1171762/206640835-1a29fdce-d53d-418d-b0fc-c72dc264dd00.png">

**Comment by aofei** [comment]
已在 https://github.com/goproxy/goproxy.cn/issues/158#issuecomment-1343930899 更新此次事故。
