### ISSUE TITLE
问题：拉取镜像源出现500错误;

### ISSUE THREAD

**Issue by ltdo111** [goproxy/goproxy.cn#158]
使用 七牛云的源， 拉取不下来依赖包；
![image](https://user-images.githubusercontent.com/17394163/206641586-0b817104-568d-486e-ae6d-05d0d02e131b.png)

麻烦帮忙解决一下；感谢；

**Comment by cpusoft** [comment]
出现同样的问题，请查下问题
感谢

**Comment by aofei** [comment]
Go 语言的官方校验和数据库 [sum.golang.org 已宕](https://github.com/golang/go/issues/57185)，导致 goproxy.cn 后台服务器那边无法正常校验新拉取到的模块版本数据，已缓存的模块版本不受影响。故障源在 Google 那边，我们无法控制。

目前正尝试临时解决方案，不过即使 goproxy.cn 关闭了模块校验正常拉取到了新模块，本地端同样无法正常构建，因为 `go` 命令的 `GOSUMDB` 环境变量的默认值是 `sum.golang.org`，依然会受 sum.golang.org 故障事件的影响。

目前最好的解决方案是在本地端临时关闭 `GOPROXY`，即执行 `go env -w GOPROXY=direct`。

**Comment by zouchangfu** [comment]
我也下载不了

![image](https://user-images.githubusercontent.com/50908453/206646990-f18fbc01-c46f-4d72-8389-da68178d6236.png)

**Comment by zhoudun** [comment]
> 使用 七牛云的源， 拉取不下来依赖包； ![image](https://user-images.githubusercontent.com/17394163/206641586-0b817104-568d-486e-ae6d-05d0d02e131b.png)
> 
> 麻烦帮忙解决一下；感谢；

问题+1，上午就不太行了，只不过偶尔又可以，所以就没提，现在直接不行了

**Comment by zouchangfu** [comment]
@zhoudun 
window 先可以先关闭这个看看
go env -w  GOSUMDB=off

**Comment by zhoudun** [comment]
> 

linux呢

**Comment by zouchangfu** [comment]
应该也是这个吧

**Comment by zhoudun** [comment]
> 
@zouchangfu 
试了几次 关掉也是不太行 这应该使用哪个操纵系统没啥关系

**Comment by zouchangfu** [comment]
@zhoudun 
是这么设置的么

go env -w GOPROXY=direct
go env -w GOSUMDB=off

**Comment by zhoudun** [comment]
> go env -w GOPROXY=direct

@zouchangfu 
嗯 只不过不是500了 而是timeout了：dial tcp 142.251.36.17:443: i/o timeout

**Comment by zouchangfu** [comment]
@zhoudun 
那你得开魔法咯

**Comment by zhoudun** [comment]
> > go env -w GOPROXY=direct
> 
> @zouchangfu 嗯 只不过不是500了 而是timeout了：dial tcp 142.251.36.17:443: i/o timeout


> @zhoudun 那你得开魔法咯

开不了，不是我自己的机器。。。

**Comment by Using1174** [comment]
@zhoudun 
临时换成阿里的代理吧
```
go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/
```

**Comment by scjtqs2** [comment]
export GOSUMDB=off && export  GOPROXY=https://mirrors.aliyun.com/goproxy/  &&  go mod tidy

**Comment by scjtqs2** [comment]
> export GOSUMDB=off && export GOPROXY=https://mirrors.aliyun.com/goproxy/ && go mod tidy

或者用第三方的gosumdb
```
export GOSUMDB=gosum.io+ce6e7565+AY5qEHUk/qmHc5btzW45JVoENfazw8LielDsaI+lEbq6 && export  GOPROXY=https://mirrors.aliyun.com/goproxy,direct && go mod tidy
```

**Comment by aofei** [comment]
问题已解决，所有服务已恢复正常。

感谢反馈！
