### ISSUE TITLE
invalid pseudo-version: revision is shorter than canonical

### ISSUE THREAD

**Issue by skrbug** [goproxy/goproxy.cn#16]
拉取 github.com/micro/go-plugins/registry/kubernetes 失败 

go: finding github.com/gogo/protobuf v0.0.0-20190410021324-65acae22fc9
go: github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: unexpected status (https://goproxy.cn/github.com/gogo/protobuf/@v/v0.0.0-20190410021324-65acae22fc9.info): 404 Not Found

**Comment by aofei** [comment]
not found: github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: invalid pseudo-version: revision is shorter than canonical (65acae22fc9d)

请问这个模块版本是你手动添加进 go.mod 的吗？它尾部的哈希少了一个字符“d”，这个部分的长度必须是 12，而你的 go.mod 中指定的那个是 11。

**Comment by Gav1nZ** [comment]
不是的,我拉取的是  github.com/micro/go-plugins/registry/kubernetes
但是提醒我404,用get能拉下来,真奇怪了.

**Comment by aofei** [comment]
稍等，我现在用的手机，等我回去了用电脑仔细看一下你说的这个库再给你答复。

**Comment by Gav1nZ** [comment]
你好,我使用其他的代理可以拉取成功,这是proxycn内部错误吗?  https://athens.azurefd.net 更换成这个之后能拉取下来

**Comment by aofei** [comment]
不是的，这不属于服务器内部错误，这是由于待获取模块的版本号非法而产生的错误，属于客户端错误。

是这样的，[goproxy.cn](https://goproxy.cn) 用的是 Go 1.13-RC2，在 Go 1.13 中，此类检查项的严格程度会有所增加，所以才会触发你的这个错误。而你所说的 [athens.azurefd.net](https://athens.azurefd.net) 所在用的 Go 版本很可能是较老的，或者是现行的 Go 1.12.x，所以它才没有出现错误。

**Comment by Gav1nZ** [comment]
aofei你好,刚入坑没多久,我现在的Go版本为1.12.9,也就是说要升级到1.13才能避免这种情况是吗?  但是在Go官网中推荐的还是12,13属于不稳定版本.

**Comment by aofei** [comment]
是这样，绝大多数情况下，只要你用的是 Go 1.11 起的版本，且 go.mod 和 go.sum 也都是由 go 命令自动嗅探并生成的，然后修改也是通过的 go 命令，那么是不会出现这个问题的，因为这个伪造版本号的规则是在 Go 1.11 出来前就规定好了的。Go 1.13 的话是增强了很多针对 modules 的检查项，也丰富了很多功能，但并没有修改这个假定版本号的规则。

说实话我也是因为你今天提了才知道的这个问题，我怀疑你的那个依赖库的作者可能在手动编辑 go.mod 时出现失误删除了一个字符导致的，我还没仔细看。

**Comment by aofei** [comment]
@Gav1nZ 我去你的那个仓库那里提 issue 了，你可以跟进一下：https://github.com/micro/go-plugins/issues/392

**Comment by Gav1nZ** [comment]
好的,谢谢大佬

**Comment by li-keli** [comment]
入坑；从goproxy.io切换过来了；目前没毛病

**Comment by aofei** [comment]
> 入坑；从goproxy.io切换过来了；目前没毛病

谢谢支持！😊

不过讲道理goproxy.io也很棒的，造福了社区好一阵子，要是我做之前能知道它的话我就不会自己再做一个而是撮合它跟七牛云了……😂

**Comment by ysicing** [comment]
```
go get -u github.com/spf13/cobra

go get: upgrading cloud.google.com/go/bigquery@v1.0.1: unexpected status (https://goproxy.cn/cloud.google.com/go/bigquery/@v/list): 502 Bad Gateway
go: google.golang.org/genproto@v0.0.0-20190905072037-92dd089d5514: unexpected status (https://goproxy.cn/google.golang.org/genproto/@v/v0.0.0-20190905072037-92dd089d5514.mod): 502 Bad Gateway
```
这个是goproxycn的问题么😂

@aofei

**Comment by aofei** [comment]
@ysicing 你好，请问你那里是一直在报那个错嘛？我自己在本地试了一下，并没有出现问题。不过倒也有可能是你那里的 CDN 节点抽风了。

**Comment by ysicing** [comment]
@aofei  现在OK了，可能是CDN节点问题

**Comment by CandySunPlus** [comment]
@Gav1nZ @aofei 在micro 没解决问题之前，先在 go.mod 里面 replace 一下 k8s 的两个依赖

`replace(
    k8s.io/api => k8s.io/api kubernetes-1.17.0-alpha.0 
    k8s.io/apimachinery => k8s.io/apimachinery kubernetes-1.17.0-alpha.0 
)`

**Comment by coolyrat** [comment]
我这边遇到这个报错
`go: github.com/gogo/protobuf@v1.3.0: Get https://goproxy.cn/github.com/gogo/protobuf/@v/v1.3.0.mod: net/http: TLS handshake timeout`

@aofei 
这个也属于cdn抽风问题么？

**Comment by aofei** [comment]
@coolyrat 

你好，请问是频发的吗？如果不是频发的话，可以接受。如果是频发的，那可能就是你所在地方的 CDN 节点出了什么问题。

其实，怎么说呢，现在这个**特殊**时间点总会让我感觉不知道是谁的问题，我打算在过了十一大庆之后再看看会不会常出现 TLS 握手超时……

**Comment by coolyrat** [comment]
@aofei 我试了很多次都是同样的错。会不会因为是敏感期，所以下载不到外面的包？如果是cdn抽风这个真的很难排查，你那边对于这个有什么办法吗？

今天换成https://goproxy.io就可以 T_T

**Comment by aofei** [comment]
@coolyrat 

如果一直是同样的错误，那就是 CDN 节点出了问题（通常情况下 CDN 很少出问题），麻烦告知一下你的地理位置，还有电信运营商，我和七牛云联系排查一下。

然后就是 [goproxy.cn](https://goproxy.cn) 的服务器是在国内的，也由七牛云在工信部备案了，合规合法，所以应该不会受到网络监管系统的干扰，可以正常地拉取到所有互联网上公开的包，并不区分地域。至于这个 TLS 握手超时的问题，不同的地方、不同的客户端请求的结果都不一样，因为 [goproxy.cn](https://goproxy.cn) 挂载了全球 CDN 加速，指不定你当前的请求是哪个节点的服务器在处理（TLS 握手是发生在客户端和 CDN 节点之间的，与后端服务器无关），比如我这里（北京，电信）就从来没出现过哪怕一次 TLS 握手超时的情况。

此外，你还可以尝试一下刷新本地 DNS 缓存的方式，看看能不能解决？

并且，之所以 [goproxy.io](https://goproxy.io) 没有 TLS 握手超时的情况是因为它是单机服务器并没有挂载任何 CDN，所有人都是在直接和同一台后台服务器在进行 TLS 握手，所以通常情况下要么整个服务挂掉，要么就正常运行。

**Comment by aofei** [comment]
@coolyrat 

最好是还能告知一下你那里 `ping goproxy.cn` 得到的 IP 地址，也就是 CDN 地址，方便我们更直接地排查。😊

**Comment by coolyrat** [comment]
@aofei 
`ping goproxy.cn
PING globalcdndownload.qiniu.com.w.kunlunar.com (14.215.23.242): 56 data bytes
64 bytes from 14.215.23.242: icmp_seq=0 ttl=55 time=12.739 ms
64 bytes from 14.215.23.242: icmp_seq=1 ttl=55 time=12.865 ms`

执行刷新DNS
`sudo dscacheutil -flushcache`

再次ping发现ip变更了，但是测试build还是同样的错误。
`ping goproxy.cn
PING globalcdndownload.qiniu.com.w.kunlunar.com (14.215.23.248): 56 data bytes
64 bytes from 14.215.23.248: icmp_seq=0 ttl=55 time=13.142 ms
64 bytes from 14.215.23.248: icmp_seq=1 ttl=55 time=13.432 ms`

**Comment by aofei** [comment]
@coolyrat 

我测试了一下，这两个节点都是一切正常的，没有出现任何问题。所以可能还是需要你提供一下你的地理位置和电信运营商，我们看一下能不能有别的什么办法可以排查。😂

或者，能麻烦你换个网路，比如连个手机热点来帮助测试一下是不是正常的吗？现在不确定问题出在哪边儿。

14.215.23.242:

```
$ curl -i --resolve 'goproxy.cn:14.215.23.242' https://goproxy.cn/github.com/gogo/protobuf/@v/v1.3.0.mod
HTTP/2 200 
server: Tengine
content-type: text/plain; charset=utf-8
content-length: 139
date: Tue, 10 Sep 2019 02:06:54 GMT
accept-ranges: bytes
cache-control: public, max-age=31536000
etag: "ak6aLZFHsb/3O7MkknBd3Q=="
last-modified: Sun, 01 Sep 2019 12:19:01 GMT
x-m-log: QNM:xs478;QNM3
x-m-reqid: pisAAJBpmXiO8cIV
x-qnm-cache: Hit
ali-swift-global-savetime: 1568081214
via: cache17.l2cn1829[0,200-0,H], cache15.l2cn1829[0,0], vcache2.cn592[0,200-0,H], vcache8.cn592[6,0]
age: 1739911
x-cache: HIT TCP_HIT dirn:0:131978831
x-swift-savetime: Tue, 24 Sep 2019 06:19:42 GMT
x-swift-cachetime: 30311232
timing-allow-origin: *
eagleid: 7cefea9c15698211251127660e

module github.com/gogo/protobuf

require (
        github.com/kisielk/errcheck v1.2.0 // indirect
        github.com/kisielk/gotool v1.0.0 // indirect
)
```

14.215.23.248:

```
$ curl -i --resolve 'goproxy.cn:14.215.23.248' https://goproxy.cn/github.com/gogo/protobuf/@v/v1.3.0.mod
HTTP/2 200 
server: Tengine
content-type: text/plain; charset=utf-8
content-length: 139
date: Tue, 10 Sep 2019 02:06:54 GMT
accept-ranges: bytes
cache-control: public, max-age=31536000
etag: "ak6aLZFHsb/3O7MkknBd3Q=="
last-modified: Sun, 01 Sep 2019 12:19:01 GMT
x-m-log: QNM:xs478;QNM3
x-m-reqid: pisAAJBpmXiO8cIV
x-qnm-cache: Hit
ali-swift-global-savetime: 1568081214
via: cache17.l2cn1829[0,200-0,H], cache15.l2cn1829[0,0], vcache2.cn592[0,200-0,H], vcache5.cn592[1,0]
age: 1739997
x-cache: HIT TCP_MEM_HIT dirn:0:131978831
x-swift-savetime: Tue, 24 Sep 2019 06:19:42 GMT
x-swift-cachetime: 30311232
timing-allow-origin: *
eagleid: 7cefea9915698212112951716e

module github.com/gogo/protobuf

require (
        github.com/kisielk/errcheck v1.2.0 // indirect
        github.com/kisielk/gotool v1.0.0 // indirect
)
```

**Comment by coolyrat** [comment]
我试了手机热点也不行。我这边是广州 电信的网络。换了热点后，我也试了换成io也是可以的。
我这边是只要将环境变量.cn改为.io就能build成功

```
FROM golang:1.13.1-stretch AS dev-build

ENV GOPROXY=https://goproxy.cn \
    GO111MODULE=on \
    CGO_ENABLED=0

WORKDIR /go/src/PROJECT/DIR

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go build -o APP cmd/main.go

FROM scratch
EXPOSE 5050
COPY --from=dev-build /go/src/PROJECT/DIR/BUILD /APP
ENTRYPOINT [ "/APP" ]
```

这个是报错
```
Step 6/13 : RUN go mod download
 ---> Running in a6879b60977e
go: github.com/gogo/protobuf@v1.3.0: Get https://goproxy.cn/github.com/gogo/protobuf/@v/v1.3.0.mod: net/http: TLS handshake timeout
The command '/bin/sh -c go mod download' returned a non-zero code: 1
make: *** [build] Error 1

```

**Comment by CodFrm** [comment]
我也遇到了
```
go: github.com/micro/go-plugins@v1.3.0 requires
        k8s.io/api@v0.0.0-20190726022912-69e1bce1dad5 requires
        github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: invalid pseudo-version: revision is shorter than canonical (65acae22fc9d)
```

通过在go.mod里使用replace解决了
```
replace github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.0
```

**Comment by aofei** [comment]
由于当前这个 Issue 中提到的问题都属于 [micro/go-plugins](https://github.com/micro/go-plugins) 这个模块本身的问题，我刚看最近他们的 Issue 列表中也有许多类似的提问（比如：[micro/go-plugins#415 ](https://github.com/micro/go-plugins/issues/415)），只能等他们来修复了。至于 TLS 握手超时的问题就统一合并到 #26 去追踪了，所以这个 Issue 我就先关闭了，感谢大家的反馈！😊

另外当前这个问题的临时解决办法可以参考： https://github.com/goproxy/goproxy.cn/issues/16#issuecomment-528260239 和 https://github.com/goproxy/goproxy.cn/issues/16#issuecomment-539814530
