### ISSUE TITLE
问题：go get github.com/alexbrainman/odbc 报 500

### ISSUE THREAD

**Issue by fanybook** [goproxy/goproxy.cn#160]
go get -u github.com/alexbrainman/odbc
go get: module github.com/alexbrainman/odbc: reading https://goproxy.cn/github.com/alexbrainman/odbc/@v/list: 500 Internal Server Error
        server response: internal server error

**Comment by aofei** [comment]
已在 https://github.com/goproxy/goproxy.cn/issues/158#issuecomment-1343930899 更新此次事故。
