### ISSUE TITLE
问题：新发布了一个模块，可以下载使用，但是在https://pkg.go.dev/查询不到

### ISSUE THREAD

**Issue by mumingv** [goproxy/goproxy.cn#166]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

确定。

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version
go version go1.19.2 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/muming/go/bin"
GOCACHE="/Users/muming/Library/Caches/go-build"
GOENV="/Users/muming/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/muming/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/muming/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tx/qgxn53zx3s71177xx5r3cqlc0000gn/T/go-build1640927444=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre>
</details>

## 你做了什么？

参考文档：https://go.dev/doc/modules/publishing ，新建并发布了一个模块。
<pre>
$ go list -m github.com/mumingv/golib@v0.0.1
github.com/mumingv/golib v0.0.1
</pre>

新建一个目录，可以正常下载并使用刚才发布的模块。
<pre>
$ mkdir hello && cd hello
$ go mod init example/hello
go: creating new go.mod: module example/hello
$ go get github.com/mumingv/golib@v0.0.1
go: added github.com/mumingv/golib v0.0.1
</pre>

## 你期望看到的结果是什么？

发布的golib模块能够在 https://pkg.go.dev 被别的开发者搜索到。

## 你实际看到的结果是什么？

在 https://pkg.go.dev 无法搜到发布的golib模块。

**Comment by aofei** [comment]
现在已经有了，这个是有延迟的，因为 pkg.go.dev 是定时在拉取处理的。

https://pkg.go.dev/github.com/mumingv/golib

**Comment by aofei** [comment]
> Documentation not displayed due to license restrictions.

不过你的这个模块因为许可证问题 google 那边考虑到法律问题不能展示。

**Comment by mumingv** [comment]
> > Documentation not displayed due to license restrictions.
> 
> 不过你的这个模块因为许可证问题 google 那边考虑到法律问题不能展示。

是的，根据提示增加了LICENSE文件后就可以显示文档了。感谢。

**Comment by mumingv** [comment]
Thx！
