### ISSUE TITLE
问题：设置了GOPROXY还是出现chaincode install failed with status: 500

### ISSUE THREAD

**Issue by Turnsolell** [goproxy/goproxy.cn#168]
1.环境情况
bash-5.0# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build268802835=/tmp/go-build -gno-record-gcc-switches"
2.版本
cent0S7

3.我的问题：
bash-5.0# cd /opt/gopath/src/github.com/hyperledger/fabric/peer
bash-5.0# peer lifecycle chaincode package sacc.tar.gz \
>   --path github.com/hyperledger/fabric-cluster/chaincode/go/ \
>   --label sacc_1
bash-5.0# peer lifecycle chaincode install sacc.tar.gz
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image build failed: docker build failed: Error returned from build: 2 "github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/flags
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/set
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/sys/internal/unsafeheader
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/detrand
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/pragma
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/version
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/internal/timeseries
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/backoff
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/errors
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/sys/unix
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/grpclog
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/encoding/protowire
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/trace
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/grpclog
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/reflect/protoreflect
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/connectivity
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/attributes
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/credentials
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/serviceconfig
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/metadata
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/grpcrand
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/encoding/messageset
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/strs
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/genid
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/order
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/reflect/protoregistry
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/encoding/text
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/runtime/protoiface
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/descfmt
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/proto
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/descopts
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/encoding/defval
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/encoding/json
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/codes
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/encoding
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/backoff
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/balancerload
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/grpcutil
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/buffer
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/grpcsync
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/envconfig
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/text/transform
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/text/unicode/bidi
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/http2/hpack
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/encoding/prototext
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/filedesc
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/text/unicode/norm
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/text/secure/bidirule
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/syscall
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/keepalive
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/stats
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/tap
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/idna
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/encoding/tag
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/encoding/protojson
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/impl
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/http/httpguts
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/http2
# github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/http2
/chaincode/input/src/github.com/hyperledger/fabric-cluster/chaincode/go/vendor/golang.org/x/net/http2/transport.go:416:45: undefined: os.ErrDeadlineExceeded
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/internal/filetype
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/runtime/protoimpl
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/types/known/timestamppb
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/types/known/anypb
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/types/descriptorpb
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/types/known/durationpb
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/golang/protobuf/ptypes/timestamp
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/golang/protobuf/ptypes/duration
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/types/known/emptypb
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/golang/protobuf/ptypes/any
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/genproto/googleapis/rpc/status
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/protobuf/reflect/protodesc
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/golang/protobuf/proto
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/credentials
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/hyperledger/fabric-protos-go/ledger/rwset
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/hyperledger/fabric-protos-go/msp
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/golang/protobuf/jsonpb
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/encoding/proto
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/channelz
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/hyperledger/fabric-protos-go/common
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/credentials/insecure
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/golang/protobuf/ptypes
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/pretty
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/resolver
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/channelz
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/status
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/metadata
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/balancer
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/balancer/grpclb/state
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/balancer/base
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/status
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/serviceconfig
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/binarylog
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/resolver/dns
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/resolver
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/balancer/roundrobin
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/balancer/gracefulswitch
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/resolver/passthrough
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/transport/networktype
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/peer
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/github.com/hyperledger/fabric-protos-go/ledger/queryresult
github.com/hyperledger/fabric-cluster/chaincode/go/vendor/google.golang.org/grpc/internal/resolver/unix
"

**Comment by aofei** [comment]
抱歉晚回复了，你有尝试过额外设置 `GO111MODULE=on` 吗？

**Comment by aofei** [comment]
由于长时间未收到回复，这个 issue 我就先关闭了，如果还有其他问题欢迎随时提问。
