### ISSUE TITLE
问题：我想下载一个指定的模块，但我不知道它在网站的路径，我要怎样处理？

### ISSUE THREAD

**Issue by Alex-zry-2333** [goproxy/goproxy.cn#174]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

是的

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.18.9 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zryTest/.cache/go-build"
GOENV="/home/zryTest/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zryTest/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zryTest/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.9"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zryTest/test/golang/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build467997119=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

sudo /usr/bin/go get -u golang.org/x/sys/unix

## 你期望看到的结果是什么？

在 /usr/lib/golang/src/下出现 unix 文件夹

## 你实际看到的结果是什么？

安装失败，报告链接超时

**Comment by aofei** [comment]
注意，由于你执行的命令 `sudo /usr/bin/go get -u golang.org/x/sys/unix` 前有 `sudo`，因此命令的环境变量应换到了 `root` 用户，所以对于 `root` 用户来说 `GOPROXY` 环境变量多半是未配置的，你还需要再配置一次。
