### ISSUE TITLE
问题：可以ping通代理 https://goproxy.cn

### ISSUE THREAD

**Issue by xiaodaiit** [goproxy/goproxy.cn#177]
"https://goproxy.cn/github.com/gin-gonic/gin/@v/v1.7.6.mod": dial tcp: lookup goproxy.cn on 8.8.8.8:53: read udp 172.17.0.3:58153->8.8.8.8:53: i/o timeout
编译的时候下载失败，是为啥

**Comment by xiaodaiit** [comment]
ENV GOPROXY https://goproxy.cn
 ENV GO111MODULE on

**Comment by aofei** [comment]
> dial tcp: lookup goproxy.cn on 8.8.8.8:53: read udp 172.17.0.3:58153->8.8.8.8:53: i/o timeout

这个错误信息挺明确了，是你本地网络环境的问题，你本地所配置的 DNS 服务器是 Google 的 8.8.8.8，然而你的本地网络环境不允许你连接到 8.8.8.8，所以网络 I/O 超时最终导致 DNS 解析失败。

在国内的话建议配置成阿里的公共 DNS（223.5.5.5），或者腾讯的公共 DNS（119.29.29.29）。

**Comment by xiaodaiit** [comment]
docker 本身的网络问题 重启docker容器就好了   谢谢解答
