### ISSUE TITLE
问题：内网搭建 最近出现了 502 的报错

### ISSUE THREAD

**Issue by jjeejj** [goproxy/goproxy.cn#180]
## 当你执行 `go version` 命令后的输出结果是什么？

$ go version
go version go1.20.3 darwin/arm64

## 当你执行 `go env` 命令后的输出结果是什么？
$ go env
GOPROXY=http://192.168.100.101:8888
GOSUMDB="off"

## 你做了什么？
拉取依赖
<img width="971" alt="image" src="https://github.com/goproxy/goproxy.cn/assets/15176971/39145888-f962-42d1-9785-8a3322da4db6">

> 是不是因为海外的拉取不了

## 你期望看到的结果是什么？
正常拉取依赖

**Comment by aofei** [comment]
内网机器是纯内网环境吗？能不能访问外网？另外搭建时用的是什么？如果搭建的时候用的是 [Goproxy](https://github.com/goproxy/goproxy) 且能够访问外网的话，那你可以为你的 Goproxy 配置上游代理，给它配置成 `GOPROXY=https://goproxy.cn` 即可，同时也别忘了把你们的内部代码源配置进 `GOPRIVATE`。

**Comment by jjeejj** [comment]
> 内网机器是纯内网环境吗？能不能访问外网？另外搭建时用的是什么？如果搭建的时候用的是 [Goproxy](https://github.com/goproxy/goproxy) 且能够访问外网的话，那你可以为你的 Goproxy 配置上游代理，给它配置成 `GOPROXY=https://goproxy.cn` 即可，同时也别忘了把你们的内部代码源配置进 `GOPRIVATE`。

机器是可以访问外网的。 而且其他外网资源 比如：github  是可以正常拉取的

**Comment by aofei** [comment]
跑 Goproxy 服务的机器如果网络畅通，那可以选择直接为 Goproxy 进程配置 `GOPROXY=direct` 和 `GOSUMDB=off`。需要注意如果没有配置的话它们是有默认值的，默认值是 `GOPROXY=https://proxy.golang.org,direct` 和 `GOSUMDB=sum.golang.org`，所以最好是手动配置下。

**Comment by aofei** [comment]
鉴于长时间未回复，这个 issue 我就先关闭了，如果还有其他问题欢迎随时提问。
