### ISSUE TITLE
问题：找不到我发布的module

### ISSUE THREAD

**Issue by cafe-old-babe** [goproxy/goproxy.cn#182]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version
go version go1.20.4 darwin/arm64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/han/Library/Caches/go-build"
GOENV="/Users/han/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/opt/env/go/go_path/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/opt/env/go/go_path"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/opt/env/go/go1.20.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/env/go/go1.20.4/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/opt/work_space/Goland/go-leo-mmap/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l2/whcb179x5z9g9tnw0bd9b0jc0000gn/T/go-build3503020428=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？
```ssh
go get github.com/cafe-old-babe/glt@v0.1.0
go: github.com/cafe-old-babe/glt@v0.1.0: parsing go.mod:
        module declares its path as: github.com/ThankyouEverybody/glt
                but was required as: github.com/cafe-old-babe/glt

```
## 你期望看到的结果是什么？

我希望可以找到`github.com/cafe-old-babe/glt`

## 你实际看到的结果是什么？
```ssh
go: github.com/cafe-old-babe/glt@v0.1.0: parsing go.mod:
        module declares its path as: github.com/ThankyouEverybody/glt
                but was required as: github.com/cafe-old-babe/glt
```

**Comment by aofei** [comment]
版本一旦发布且被 module proxy 缓存下来就不能再更改了，因为被不可逆地写进了 sumdb，这么做的目的是尽可能地保证可复现构建，比如可以防止目标模块的作者植入恶意代码等。

你这个 github.com/cafe-old-babe/glt 模块明显已经发布过 v1.0.0 版本了（且发布时它的 go.mod 文件里的 module path 是 github.com/ThankyouEverybody/glt），所以你又 force push 了这个版本是没有任何意义的。
