### ISSUE TITLE
Question: goproxy.cn  504 gateway timeout today

### ISSUE THREAD

**Issue by genie88** [goproxy/goproxy.cn#186]
## What is the output when you execute the `go version` command?

<pre>
$ go version

</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by mydearzsy** [comment]
网站和代理都挂了...
<img width="273" alt="image" src="https://github.com/goproxy/goproxy.cn/assets/5027137/5d3685ee-6c44-4a16-9669-c444e6785c51">

```
go: module gopkg.in/yaml.v3: reading https://goproxy.cn/gopkg.in/yaml.v3/@v/list: 504 Gateway Timeout
        server response: Gateway Timeout
```

**Comment by cidosx** [comment]
咋了捏

**Comment by aofei** [comment]
问题已经解决，目前监测一切正常，感谢反馈！❤️
