### ISSUE TITLE
问题：是否可以使用curl去下载某个链接

### ISSUE THREAD

**Issue by ccmywish** [goproxy/goproxy.cn#187]
维护者你们好：

我和朋友在开发一个开源的镜像管理工具，预计1周后公开。

我想对 goproxy.cn 和 goproxy.io 测速，方法是通过 `curl` 下载某个链接，请问这样在Go镜像中可行吗？（我不是Go用户，不太了解）

如果可行，可否推荐一个较大的文件的URL。

为方便理解我的问题，请看这个例子：我要对Ruby包的镜像测速，那么我会找到Ruby的某个包的具体 URL，比如：https://gems.ruby-china.com/rubygems/gems/nokogiri-1.15.0-java.gem 这个包有9.9MB，可以使用 curl 下载下来。

我想要在Go镜像上同样达到这个目的。可以提供上述帮助吗？即推荐一个可用 curl 下载的较大的文件的URL。

**Comment by aofei** [comment]
[GOPROXY protocol](https://go.dev/ref/mod#goproxy-protocol) 是基于 HTTP 的，很简单，你只要看一眼大致就能了解该如何通过 cURL 之类的工具请求了。

比如：

```bash
$ curl -I https://goproxy.cn/github.com/aws/aws-sdk-go/@v/v1.45.2.zip
HTTP/2 200
content-type: application/zip
content-length: 31862485
...
```

另外说一下，goproxy.cn 可以在国内备案所以是配备了七牛 CDN 的，这样下载速度方面的测试比较就没有多大意义了，不出意外基本能跑满你们的带宽。

**Comment by ccmywish** [comment]
@aofei  了解了，感谢 👍
