### ISSUE TITLE
问题：github上上传了我的项目，并创建了release，需要多久才能从goproxy.cn获取到我上传的项目的依赖

### ISSUE THREAD

**Issue by mingmingshiliyu** [goproxy/goproxy.cn#190]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
并不存在主动同步，只有在某人通过 goproxy.cn 拉取过你的模块版本后，你的模块版本才会被缓存。

如果你希望某个模块版本能尽快被 goproxy.cn 缓存起来，那么你可以通过类似 `go get example.com/foo/bar@v1.0.0` 这样的命令来主动拉取一次。
