### ISSUE TITLE
问题：force push 同一版本号后如何刷新代理上的缓存

### ISSUE THREAD

**Issue by shenpuyu0** [goproxy/goproxy.cn#191]
同一个包如果发布新版本后又打了一个补丁, 而没有跟新版本号，无论是使用go get还是go get -u 都只会获取到缓存的没有打补丁的包
我等待了十分钟，但还是获取不到打补丁后的包
希望能明确一下缓存时长或者提供一个刷新包的方法

**Comment by aofei** [comment]
没有“缓存时长”一说，也没有“刷新包的方法”，因为 Go module proxy 被设计出来的目的就是为了尽可能保证可复现构建。退一步讲，即使在 Go module proxy 这边删除了某个模块版本的缓存也是没有意义的，因为还有 Go checksum database 的存在（就是 `GOSUMDB` 所指向的那个，默认是 [sum.golang.org](https://sum.golang.org)）。一旦某个模块版本的 checksum 被写进 Go checksum database，那么就无法再更改，因为它从设计上不可逆，这么做目的同样也是为了保证可复现构建。

作为模块作者，如果你发布的某个模块版本中存在问题，那你不能 fix 后重新 force push 同样的版本，你只应该通过发布新的 patch 版本来解决问题。对于使用者来说，人们不希望看到他们依赖的某个模块版本在某一天某一刻毫不知情地发生了变化，毕竟万一这个“变化”对使用者来说是个安全隐患呢。

**Comment by fyupeng** [comment]
首先感谢您提供的回复，其实这个之前我也了解过了，也就是说就算我重新发布了同一版本号的，也是无法覆盖原来版本的行为是吗？我必须发布版本号>v1.0.0来解决这个问题对嘛？

**Comment by aofei** [comment]
> 也就是说就算我重新发布了同一版本号的，也是无法覆盖原来版本的行为是吗？我必须发布版本号>v1.0.0来解决这个问题对嘛？

是的

**Comment by aofei** [comment]
鉴于 OP 长时间未回复，这个 issue 我就先关闭了，如果还有其他问题欢迎随时提问。
