### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by fyupeng** [goproxy/goproxy.cn#194]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.21.4 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\11608\AppData\Local\go-build
set GOENV=C:\Users\11608\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Users\fyp01\GoProject\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Users\fyp01\GoProject;D:\software\Go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn/,direct
set GOROOT=D:/software/Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\software\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\11608\GolandProjects\awesomeProject\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\11608\AppData\Local\Temp\go-build3511
264785=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

我在发布github版本时，错误发布了v1.0.0，1.0.0是预计年底发布的正式版本，现在发布的小版本，我已经删除了本地的tag和远程github的tag已经release包，原因该包go.mod存在问题

## 你期望看到的结果是什么？

使用go get github.com/fyupeng/rpc-go-netty@latest 能获取到 v0.1.7，但始终无法解决。

## 你实际看到的结果是什么？
想咨询下如何删除v1.0.0版本，我希望@latest版本在v0.1.x，目前的最新版本是v0.1.7，不适应总是使用@v0.1.7来下载，很不友好。

联系：fyp010311@126.com（或Issue）
感谢了！

**Comment by aofei** [comment]
你好，与 #191 重复了，详见 https://github.com/goproxy/goproxy.cn/issues/191#issuecomment-1726986320
