### ISSUE TITLE
Bug: Cant fetch https://github.com/klauspost/compress

### ISSUE THREAD

**Issue by c1pyerten** [goproxy/goproxy.cn#195]
## What is the output when you execute the `go version` command?

<pre>
$ go version 

go version go1.20.6 windows/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
你的使用有误，详见：https://go.dev/ref/mod#goproxy-protocol
