### ISSUE TITLE
问题：wget下载模块下的某个包

### ISSUE THREAD

**Issue by HFwas** [goproxy/goproxy.cn#199]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？
无

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.20.1 darwin/arm64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/hfwas/Library/Caches/go-build"
GOENV="/Users/hfwas/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/hfwas/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hfwas/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/59/xpgs0_2d4hx_v_vff5cds1dh0000gn/T/go-build3064726647=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？
wget https://goproxy.cn/github.com/Azure/azure-sdk-for-go/sdk/azcore/@v/v1.7.0.zip

## 你期望看到的结果是什么？
wget能够直接下载goproxy.cn对应的依赖包，因为现在内网没有依赖，所以现在要手动下载拷贝到内网

--2023-12-31 18:40:44--  https://goproxy.cn/cloud.google.com/go/storage/@v/v1.35.1.zip
正在解析主机 goproxy.cn (goproxy.cn)... 123.130.123.41
正在连接 goproxy.cn (goproxy.cn)|123.130.123.41|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：605696 (592K) [application/zip]
正在保存至: “v1.35.1.zip”

v1.35.1.zip                                                100%[========================================================================================================================================>] 591.50K  --.-KB/s  用时 0.08s

2023-12-31 18:40:44 (6.81 MB/s) - 已保存 “v1.35.1.zip” [605696/605696])

## 你实际看到的结果是什么？

/Volumes/PortableSSD/go > wget https://goproxy.cn/github.com/Azure/azure-sdk-for-go/sdk/azcore/@v/v1.7.0.zip                                                                                                                       18:56:35
--2024-01-01 18:56:35--  https://goproxy.cn/github.com/Azure/azure-sdk-for-go/sdk/azcore/@v/v1.7.0.zip
正在解析主机 goproxy.cn (goproxy.cn)... 123.129.234.41
正在连接 goproxy.cn (goproxy.cn)|123.129.234.41|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2024-01-01 18:56:36 错误 404：Not Found。

**Comment by aofei** [comment]
语法错误。Go modules 规定 path 和 version 中的大写字母需要转译，比如 `Azure` 需要转译成 `!azure`。

详见 https://go.dev/ref/mod#module-cache

> Capital letters in module paths and versions are escaped using exclamation points (Azure is escaped as !azure) to avoid conflicts on case-insensitive file systems.

**Comment by HFwas** [comment]
非常感谢，问题已解决！！
