### ISSUE TITLE
go get -u golang.org/x/*

### ISSUE THREAD

**Issue by abxd39** [goproxy/goproxy.cn#20]
$ go get -u golang.org/x/lint/golint
package golang.org/x/lint/golint: unrecognized import path "golang.org/x/lint/golint" (https fetch: Get https://golang.org/x/lint/golint?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

env 如下
set GOPATH=E:\WorkSpace
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=c:\go

这个该怎么用呢？

**Comment by aofei** [comment]
你好，请问你有设置过 GO111MODULE=on 吗？具体原因可以看一下 #17。

**Comment by abxd39** [comment]
$ go env
set GO111MODULE=auto
set GOARCH=amd64
这样子可以么？ 还是说一定要是on

**Comment by abxd39** [comment]
改成on 就OK了
export GO111MODULE=on
$ go get -u golang.org/x/lint/golint
go: finding golang.org/x/lint latest
go: downloading golang.org/x/lint v0.0.0-20190909230951-414d861bb4ac
go: extracting golang.org/x/lint v0.0.0-20190909230951-414d861bb4ac
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190909214602-067311248421
go: extracting golang.org/x/tools v0.0.0-20190909214602-067311248421

谢谢
