### ISSUE TITLE
问题：如何通过公司内网代理来访问？

### ISSUE THREAD

**Issue by xiaoxpai** [goproxy/goproxy.cn#200]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

公司必须走代理才能进行访问，go有这个设置内网代理方式吗？在cmd进行ping goproxy.cn 找不到主机地址，无法访问

**Comment by aofei** [comment]
通过内网代理访问 goproxy.cn 吗？内网代理是什么协议的呢？如果是 HTTP_PROXY 或 HTTPS_PROXY 的话设置好对应环境变量即可，`go` 命令在发起 HTTP 请求时会自动读取并使用它们的。

**Comment by xiaoxpai** [comment]
> 通过内网代理访问 goproxy.cn 吗？内网代理是什么协议的呢？如果是 HTTP_PROXY 或 HTTPS_PROXY 的话设置好对应环境变量即可，`go` 命令在发起 HTTP 请求时会自动读取并使用它们的。

是的，类似于`git`走代理，比如 `git config --global http.proxy http://username:pwd@127.0.0.1:7899`，请问`go`支持这样的代理吗

**Comment by aofei** [comment]
支持的，设置好相关环境变量即可，详见我上条评论。

鉴于问题已回答，这个 issue 我就先关闭了。
