### ISSUE TITLE
问题： verifying module: invalid GOSUMDB: malformed verifier id

### ISSUE THREAD

**Issue by caoyanyan37** [goproxy/goproxy.cn#201]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.21.7 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>

<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=E:\GoCache
set GOENV=C:\Users\XXX\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\GoWork\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GoWork
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Program\gvm\go
set GOSUMDB=sum.goproxy.cn
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Program\gvm\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.7
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\WWW\LumenIM\go-chat\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\CAOYAN~1\AppData\Local\Temp\go-build2748639914=/tmp/go-build -gno-record-gcc-switches
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=E:\GoCache
set GOENV=C:\Users\Caoyanyan\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\GoWork\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GoWork
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Program\gvm\go
set GOSUMDB=sum.goproxy.cn
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Program\gvm\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.7
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\WWW\LumenIM\go-chat\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\CAOYAN~1\AppData\Local\Temp\go-build2748639914=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

执行了go mod tidy

## 你期望看到的结果是什么？

正常执行, 自动下载和匹配组件

## 你实际看到的结果是什么？

        gopkg.in/natefinch/lumberjack.v2: gopkg.in/natefinch/lumberjack.v2@v2.2.1: verifying module: invalid GOSUMDB: malformed verifier id

**Comment by aofei** [comment]
```
set GOSUMDB=sum.goproxy.cn
```

不需要设置 `GOSUMDB` 这个环境变量，而且也没有 `sum.goproxy.cn` 这个东西。你把它置空，保留默认值 `sum.golang.org` 就好，`goproxy.cn` 无缝支持代理 `sum.golang.org`。

**Comment by aofei** [comment]
由于已给出答案且长时间没有新的回复，这个 issue 我就先关闭了。
