### ISSUE TITLE
问题：https://goproxy.cn/ 网站出问题了么  ，拉取go 模块网关报504，500 

### ISSUE THREAD

**Issue by Sunlight-li** [goproxy/goproxy.cn#204]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by anhoder** [comment]
+1

**Comment by nakes** [comment]
+1

**Comment by aac3476** [comment]
+1+1

**Comment by dockercore** [comment]
+2

**Comment by aofei** [comment]
感谢反馈，目前 goproxy.cn 正在遭受攻击，这边处理中。

**Comment by hiifong** [comment]
+1

**Comment by oyjjpp** [comment]
+1

**Comment by debuggy** [comment]
> 感谢反馈，目前 goproxy.cn 正在遭受攻击，这边处理中。

有预期恢复时间吗 😹

**Comment by lolymaequkabu** [comment]
DDoS 不好搞哦

**Comment by kevinmiao** [comment]
<img width="1009" alt="截屏2024-03-26 下午6 01 34" src="https://github.com/goproxy/goproxy.cn/assets/8663456/435ff5ef-1e75-4d72-af6b-dddb7ad0bf3e">

**Comment by aofei** [comment]
解决方案已部署，服务恢复中。

**Comment by kawhi-xl** [comment]
+1

**Comment by aofei** [comment]
解决方案奏效，不过攻击还在持续当中。监控显示现在基本没有错误再产生了，这边会继续监控下去直到攻击停止。

**Comment by cobain** [comment]
啥时候能用啊，现在没法编译打包了

**Comment by aofei** [comment]
> 啥时候能用啊，现在没法编译打包了

3 个小时前服务就已经完全恢复了，你遇到了什么错误呢？麻烦提供下错误信息。

**Comment by cobain** [comment]
> > 啥时候能用啊，现在没法编译打包了
> 
> 3 个小时前服务就已经完全恢复了，你遇到了什么错误呢？麻烦提供下错误信息。

现在好了。

**Comment by aofei** [comment]
攻击还在持续当中，但已不再对 goproxy.cn 造成任何影响。这个 issue 我就先关闭了，再次感谢大家的反馈！
