### ISSUE TITLE
问题：https://goproxy.cn/sumdb/sum.golang.org/supported 404

### ISSUE THREAD

**Issue by kuangrenxuezhe** [goproxy/goproxy.cn#206]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
与 #204 重复
