### ISSUE TITLE
问题：go: module gioui.org: Get "https://goproxy.cn/gioui.org/@v/list": net/http: TLS handshake timeout，总是报这个错

### ISSUE THREAD

**Issue by chenxiaoweish** [goproxy/goproxy.cn#207]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by chenxiaoweish** [comment]
go version go1.22.0 windows/amd64；
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\chenxiaowei\AppData\Local\go-build
set GOENV=C:\Users\chenxiaowei\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\chenxiaowei\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\chenxiaowei\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\code\go\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\CHENXI~1\AppData\Local\Temp\go-build147769996=/tmp/go-build -gno-record-gcc-switches

**Comment by aofei** [comment]
你好，这应该是本地网络环境的问题。请问还是持续报错吗？如果是的话麻烦提供一下你本地网络对 goproxy.cn 的 DNS 解析结果。

**Comment by aofei** [comment]
由于长时间未回复，且这个大概率属于本地网络环境问题，这个 issue 我就先关闭了，如果还有其他问题欢迎随时开新 issue 来提问。
