### ISSUE TITLE
问题：使用代理后无法go get google.golang.org/grpc

### ISSUE THREAD

**Issue by zijiewu3zZ** [goproxy/goproxy.cn#209]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.21.9 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
go: stripping unprintable or unescapable characters from %"GOCACHE"%
set GOCACHE=C:\Users\���������\AppData\Local\go-build
go: stripping unprintable or unescapable characters from %"GOENV"%
set GOENV=C:\Users\���������\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Environment\GoWorks\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Environment\GoWorks
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Environment\Go
set GOSUMDB=sum.golang.google.cn
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Environment\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.9
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
go: stripping unprintable or unescapable characters from %"GOGCCFLAGS"%
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\���������\AppData\Local\Temp\go-build4092800913=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

go get google.golang.org/grpc

## 你期望看到的结果是什么？

正常安装？

## 你实际看到的结果是什么？

package google.golang.org/grpc: unrecognized import path "google.golang.org/grpc": https fetch: Get "https://google.golang.org/grpc?go-get=1": dial tcp 142.250.66.209:443: i/o timeout

**Comment by aofei** [comment]
你这个是直连到 google.golang.org 了，似乎是对 GOPROXY 的配置并没有生效，麻烦贴出下面命令的输出结果：

```
go get -x google.golang.org/grpc
```

**Comment by zijiewu3zZ** [comment]
输出结果如下：
D:\Environment\src\HelloWorld\hello-server\proto>go get -x google.golang.org/grpc
go: error reading ..\..\go.mod: missing module declaration. To specify the module path:
        go mod edit -module=example.com/mod

**Comment by aofei** [comment]
> 输出结果如下： D:\Environment\src\HelloWorld\hello-server\proto>go get -x google.golang.org/grpc go: error reading ....\go.mod: missing module declaration. To specify the module path: go mod edit -module=example.com/mod

你这个错误跟 GOPROXY 无关，是你项目的 go.mod 文件有问题。按着错误提示解决，解决完后再执行我给你的命令。

**Comment by aofei** [comment]
由于长时间未回复，这个 issue 我就先关闭了，如果还有其他问题欢迎随时开新 issue 提问。
