### ISSUE TITLE
问题：无法获取最新的go-delve模块对go程序进行调试

### ISSUE THREAD

**Issue by Leizhixin** [goproxy/goproxy.cn#212]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\leizx\AppData\Local\go-build
set GOENV=C:\Users\leizx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\leizx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\leizx\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=E:\golang-exe
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=E:\golang-exe\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\leizx\AppData\Local\Temp\go-build89823262=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？
 go get -v github.com/go-delve/delve/cmd/dlv

go: module github.com/go-delve/delve/cmd/dlv: Get "https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/list": dial tcp 220.181.173.41:443: connectex: A connection attempt failed because the connected party did not properly respo
nd after a period of time, or established connection failed because connected host has failed to respond.

**Comment by aofei** [comment]
这个看着应该是本地网络环境的问题，可以刷新下本地 dns 缓存试试

**Comment by aofei** [comment]
由于长时间未回复，这个 issue 我就先关闭了。如果还有其他问题欢迎随时提问。
