### ISSUE TITLE
问题：GOPSUTIL 库没有同步，而且 goproxy.cn 没有提供一个数据库来查看可用版本

### ISSUE THREAD

**Issue by ZenkieBear** [goproxy/goproxy.cn#216]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

确定

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.23.1 darwin/arm64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/zenkiebear/Library/Caches/go-build'
GOENV='/Users/zenkiebear/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/zenkiebear/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/zenkiebear/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.1'
GODEBUG=''
GOTELEMETRY='on'
GOTELEMETRYDIR='/Users/zenkiebear/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/pw/hwq7cxcx50b3kzcy8qwwyfhw0000gn/T/go-build601414844=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre>
</details>

## 你做了什么？

```sh
go get -u github.com/shirou/gopsutil
```

## 你期望看到的结果是什么？

成功安装 `gopsutil@4.24.8` 版本

## 你实际看到的结果是什么？

安装了 `v3.21.11+incompatible` 版本

## 补充：
实际上 v3.22.27 已于 2022年8月3日 发布，但 goproxy.cn 上**最新**只能拉取到 `v3.21.11+incompatible` 版本：
```sh
go list -m --versions github.com/shirou/gopsutil
github.com/shirou/gopsutil v2.0.0+incompatible v2.16.10+incompatible v2.16.11+incompatible v2.16.12+incompatible v2.17.10+incompatible v2.17.11+incompatible v2.17.12+incompatible v2.18.10+incompatible v2.18.11+incompatible v2.18.12+incompatible v2.19.6+incompatible v2.19.7+incompatible v2.19.8+incompatible v2.19.9+incompatible v2.19.10+incompatible v2.19.11+incompatible v2.19.12+incompatible v2.20.1+incompatible v2.20.2+incompatible v2.20.3+incompatible v2.20.4+incompatible v2.20.5+incompatible v2.20.6+incompatible v2.20.7+incompatible v2.20.8+incompatible v2.20.9+incompatible v2.21.11+incompatible v3.20.10+incompatible v3.20.11+incompatible v3.20.12+incompatible v3.21.1+incompatible v3.21.2+incompatible v3.21.3+incompatible v3.21.4+incompatible v3.21.5+incompatible v3.21.6+incompatible v3.21.7+incompatible v3.21.8+incompatible v3.21.9+incompatible v3.21.10+incompatible v3.21.11+incompatible
```

**Comment by aofei** [comment]
> 成功安装 `gopsutil@4.24.8` 版本

它的 module path 变成了 `github.com/shirou/gopsutil/v4`：https://github.com/shirou/gopsutil/blob/6c06ac987e81e185f27afa7d161e5fc127b878ce/go.mod#L1

所以你应该 `go get github.com/shirou/gopsutil/v4` 才对。

```bash
$ go list -m -versions github.com/shirou/gopsutil/v4
github.com/shirou/gopsutil/v4 v4.24.0-alpha.1 v4.24.0-beta v4.24.5 v4.24.6 v4.24.7 v4.24.8
```

相关 Go Modules 知识点，详见：https://go.dev/ref/mod#major-version-suffixes

**Comment by ZenkieBear** [comment]
是的，我忘记了跨版本需要切换 path



ZENKIE


------------------ 原始邮件 ------------------
From: Aofei Sheng ***@***.***&gt;
发送时间: 09/24/2024, 11:39
To: goproxy/goproxy.cn ***@***.***&gt;
抄送: Zachary Bear ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [goproxy/goproxy.cn] 问题：GOPSUTIL 库没有同步，而且 goproxy.cn 没有提供一个数据库来查看可用版本 (Issue #216)





  
成功安装 ***@***.*** 版本
  
它的 module path 变成了 github.com/shirou/gopsutil/v4：https://github.com/shirou/gopsutil/blob/6c06ac987e81e185f27afa7d161e5fc127b878ce/go.mod#L1
 
所以你应该 go get github.com/shirou/gopsutil/v4 才对。
 $ go list -m -versions github.com/shirou/gopsutil/v4 github.com/shirou/gopsutil/v4 v4.24.0-alpha.1 v4.24.0-beta v4.24.5 v4.24.6 v4.24.7 v4.24.8
 
相关 Go Modules 知识点，详见：https://go.dev/ref/mod#major-version-suffixes
