### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by 1801517241** [goproxy/goproxy.cn#217]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.23.1 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\18015\AppData\Local\go-build
set GOENV=C:\Users\18015\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Software\Environment\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Software\Environment\GOPATH
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Software\Environment\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Software\Environment\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.1
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\18015\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\18015\AppData\Local\Temp\go-build301104592=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你期望看到的结果是什么？

我期望go get -u github.com/gin-gonic/gin可以正常使用

## 你实际看到的结果是什么？

实际上goland会出现
m/stretchr/objx/@v/v0.5.0.info": proxyconnect tcp: dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.
go: golang.org/x/term@v0.24.0: Get "https://goproxy.cn/golang.org/x/term/@v/v0.24.0.info": proxyconnect tcp: dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.
这个错误

**Comment by aofei** [comment]
> proxyconnect tcp: dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.

看起来是本地的 http proxy 配置错误。详见：https://github.com/goproxy/goproxy.cn/issues/71#issuecomment-599986830

**Comment by 1801517241** [comment]
已经解决了，我之前配置了代理，导致不能下载

**Comment by aofei** [comment]
既然问题已解决，那这个 issue 我就先关闭了。如果还有其他问题欢迎随时开新 issue 提问～

**Comment by 1801517241** [comment]
能否帮我删除这个issues
