### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by kuengroc** [goproxy/goproxy.cn#218]
近期频繁出现429响应，是开始限流了吗？

**Comment by aofei** [comment]
根据 CDN 日志分析结果来看，过去一个月没有出现任何 429 响应。请问你那边是不是存在什么其他中间层，比如系统级代理之类的？

**Comment by kuengroc** [comment]
> 根据 CDN 日志分析结果来看，过去一个月没有出现任何 429 响应。请问你那边是不是存在什么其他中间层，比如系统级代理之类的？
没有其他代理层的 今天之前还是正常的
# dig goproxy.cn

; <<>> DiG 9.11.36-RedHat-9.11.36-5.el8_7.2 <<>> goproxy.cn
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1660
;; flags: qr rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;goproxy.cn.			IN	A

;; ANSWER SECTION:
goproxy.cn.		600	IN	CNAME	goproxy.cn.qiniudns.com.
goproxy.cn.qiniudns.com. 600	IN	CNAME	opencdnqiniustaticv6.jomodns.com.
opencdnqiniustaticv6.jomodns.com. 60 IN	A	182.61.128.177

;; Query time: 18 msec
;; WHEN: Wed Oct 09 16:53:33 CST 2024
;; MSG SIZE  rcvd: 135

**Comment by aofei** [comment]
如果 CDN 供应商的日志采集服务没有异常，那么可以确定的是今天截止评论发出时确实没有 429 响应产生。另外你 `dig goproxy.cn` 拿到的节点 IP 我刚并发打了些请求测试了一下，没出现问题。

如果你那边可以复现的话，看能不能提供一个 `curl -iv https://goproxy.cn/github.com/go-playground/assert/v2/@v/v2.2.0.mod` 的 429 输出结果，也许会有帮助。

**Comment by yzcwf** [comment]
我这边build的时候也频繁出现429 Too Many Requests

**Comment by aofei** [comment]
刚又看了一下 CDN 日志分析结果，过去 30 天内确实没有 429 响应产生。这个情况就比较奇怪了。

我先把这个 issue 置顶吧，看还有没有更多人遇到这个情况。

**Comment by aofei** [comment]
这两天 CDN 线路做了一些调整，但不确定是否顺便解决了这个问题。

我再保持这个 issue 打开一段时间，如果有人再遇到这个问题麻烦说一下。

**Comment by aofei** [comment]
由于最近一个多月没有新的反馈，那这个 issue 我就先关闭了，如果还有其他问题欢迎随时开新 issue 提问。

再次感谢各位的反馈！🙏
