### ISSUE TITLE
Question: go get 有时候会报错 http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by KaraBilly** [goproxy/goproxy.cn#219]
$ go get sigs.k8s.io/controller-runtime@v0.19.0 
go: sigs.k8s.io/controller-runtime@v0.19.0: Get "https://goproxy.cn/sigs.k8s.io/controller-runtime/@v/v0.19.0.mod": http: server gave HTTP response to HTTPS client

## What is the output when you execute the `go version` command?

<pre>
$ go version go version go1.23.3 darwin/arm64

</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GOPROXY='https://goproxy.cn,direct'
</pre>
</details>

**Comment by aofei** [comment]
抱歉回复晚了。

这两天 CDN 线路做了一些调整，但不确定是否顺便解决了你说的这个问题。我先保持这个 issue 打开一段时间，如果你再遇到这个问题麻烦说一下。

**Comment by KaraBilly** [comment]
感谢花时间查看这个问题。
后来我发现可能是公司外网的问题，在家里试了下是可以完成的。
我认为这个issue 可以close了
