### ISSUE TITLE
问题：https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip  无法正常获取到包

### ISSUE THREAD

**Issue by tiancheng92** [goproxy/goproxy.cn#220]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

没有

https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip 无法下载

```
go: downloading github.com/bytedance/sonic v1.12.5
/cache/gopath/pkg/mod/github.com/!yostardev/json@v1.0.8/sonic.go:5:8: github.com/bytedance/sonic@v1.12.5: read "https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip": stream error: stream ID 1; INTERNAL_ERROR; received from peer
time="2024-11-25T03:28:04.629Z" level=info msg="sub-process exited" argo=true error=""
Error: exit status 1
```

https://proxy.golang.org/github.com/bytedance/sonic/@v/v1.12.5.zip 可正常下载

**Comment by aofei** [comment]
你好，这个问题在你那边是持续存在的吗？看起来应该只是网络问题导致的，重试应该可以解决。

**Comment by tiancheng92** [comment]
> 你好，这个问题在你那边是持续存在的吗？看起来应该只是网络问题导致的，重试应该可以解决。

一直不行 直接用浏览器打开连接就提示下载错误

**Comment by aofei** [comment]
麻烦执行一下这条命令，看看输出结果是什么：

```
curl -Iv https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip
```

**Comment by tiancheng92** [comment]
> 麻烦执行一下这条命令，看看输出结果是什么：
> 
> ```
> curl -Iv https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip
> ```

❯ curl -Iv https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip
* Host goproxy.cn:443 was resolved.
* IPv6: (none)
* IPv4: 114.80.149.72, 114.80.149.73, 180.163.200.97, 180.163.200.96
*   Trying 114.80.149.72:443...
* Connected to goproxy.cn (114.80.149.72) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.goproxy.cn
*  start date: Aug 22 00:00:00 2024 GMT
*  expire date: Sep  7 23:59:59 2025 GMT
*  subjectAltName: host "goproxy.cn" matched cert's "goproxy.cn"
*  issuer: C=CN; O=TrustAsia Technologies, Inc.; CN=TrustAsia RSA DV TLS CA G3
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip
* [HTTP/2] [1] [:method: HEAD]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: goproxy.cn]
* [HTTP/2] [1] [:path: /github.com/bytedance/sonic/@v/v1.12.5.zip]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> HEAD /github.com/bytedance/sonic/@v/v1.12.5.zip HTTP/2
> Host: goproxy.cn
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/2 200
HTTP/2 200
< server: openresty
server: openresty
< date: Wed, 27 Nov 2024 02:23:13 GMT
date: Wed, 27 Nov 2024 02:23:13 GMT
< content-type: application/zip
content-type: application/zip
< content-length: 3418244
content-length: 3418244
< accept-ranges: bytes
accept-ranges: bytes
< cache-control: public, max-age=604800
cache-control: public, max-age=604800
< strict-transport-security: max-age=31536000
strict-transport-security: max-age=31536000
< age: 173671
age: 173671
< ctl-cache-status: HIT from he-shijiazhuang13-ca12, MISS from sh-pudongxin12-ca84
ctl-cache-status: HIT from he-shijiazhuang13-ca12, MISS from sh-pudongxin12-ca84
< request-id: 951067468291725077678370271a6fc4
request-id: 951067468291725077678370271a6fc4
<

* Connection #0 to host goproxy.cn left intact

**Comment by tiancheng92** [comment]
> 麻烦执行一下这条命令，看看输出结果是什么：
> 
> ```
> curl -Iv https://goproxy.cn/github.com/bytedance/sonic/@v/v1.12.5.zip
> ```

<img width="1985" alt="image" src="https://github.com/user-attachments/assets/4f7e3b87-19a9-4a7c-a8f9-bc5995beb78e">

这是异常的与正常请求的对比

**Comment by aofei** [comment]
这个问题模块周五就已修复，忘记回复了。

造成这个问题的原因是 CDN 运营商那边的缓存机制存在一些不合理的处理逻辑，现已解决。

感谢反馈！这个 issue 我就先关闭了，如果还有别的问题欢迎随时开新 issue 提问。
