### ISSUE TITLE
问题：用proxy.cn 拉取镜像包会出现Get "https://goproxy.cn/github.com/smartystreets/goconvey/@v/v1.8.1.zip": read tcp 172.17.0.4:45862->163.181.140.200:443: read: connection reset by peer

### ISSUE THREAD

**Issue by suxwang** [goproxy/goproxy.cn#221]
## go version
go.1.22

## 问题描述
拉取包时一部分的报拉取不下来

1.095 go: downloading github.com/spf13/pflag v1.0.5                                                                                                                                                       
1.096 go: downloading go.uber.org/zap v1.27.0                                                                                                                                                             
1.096 go: downloading k8s.io/apimachinery v0.31.0                                                                                                                                                         
1.096 go: downloading github.com/smartystreets/goconvey v1.8.1                                                                                                                                            
1.096 go: downloading k8s.io/api v0.31.0
1.096 go: downloading k8s.io/apiserver v0.31.0
1.097 go: downloading github.com/google/go-cmp v0.6.0
1.097 go: downloading k8s.io/component-helpers v0.31.0
1.098 go: downloading k8s.io/client-go v0.31.0
1.098 go: downloading github.com/robfig/cron/v3 v3.0.1
1.098 go: downloading k8s.io/component-base v0.31.0
1.098 go: downloading k8s.io/klog/v2 v2.130.1
1.098 go: downloading k8s.io/utils v0.0.0-20240711033017-18e509b52bc8
1.100 go: downloading golang.org/x/sync v0.8.0
1.101 go: downloading github.com/swaggo/swag v1.16.3
1.101 go: downloading github.com/swaggo/files v1.0.1
1.109 go: downloading github.com/swaggo/gin-swagger v1.6.0
1.124 go: downloading k8s.io/code-generator v0.31.0
36.41 go: downloading github.com/grafana/grafana-plugin-sdk-go v0.259.2
36.41 go: downloading github.com/grafana/dskit v0.0.0-20241105154643-a6b453a88040
36.41 go: downloading github.com/grafana/grafana/pkg/promlib v0.0.6
36.41 go: downloading github.com/json-iterator/go v1.1.12
36.41 go: downloading go.opentelemetry.io/otel/trace v1.31.0
36.41 go: downloading github.com/gin-contrib/cors v1.7.2
36.41 go: downloading github.com/gin-gonic/gin v1.9.1
36.41 go: downloading github.com/prometheus/client_golang v1.20.5
36.41 go: downloading gopkg.in/yaml.v2 v2.4.0
36.41 go: downloading github.com/spf13/cobra v1.8.1
36.41 go: downloading k8s.io/klog v1.0.0
36.41 go: downloading github.com/spf13/viper v1.19.0
36.41 go: downloading gorm.io/gorm v1.25.11
36.41 go: downloading github.com/prometheus/common v0.60.1
36.41 go: downloading gorm.io/driver/mysql v1.5.7
36.41 go: downloading github.com/ClickHouse/clickhouse-go/v2 v2.30.0
36.41 go: downloading google.golang.org/grpc v1.67.1
36.41 go: downloading google.golang.org/protobuf v1.35.1
36.42 go: downloading k8s.io/apiextensions-apiserver v0.31.0
36.42 go: downloading sigs.k8s.io/controller-runtime v0.19.0
36.42 go: downloading github.com/google/uuid v1.6.0
36.46 go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
85.66 go: downloading gorm.io/datatypes v1.2.1
85.66 go: downloading gopkg.in/natefinch/lumberjack.v2 v2.2.1
85.66 go: downloading github.com/xuri/excelize/v2 v2.8.1
85.66 go: downloading github.com/jordan-wright/email v4.0.1-0.20210109023952-943e75fe5223+incompatible
85.66 go: downloading github.com/aliyun/aliyun-log-go-sdk v0.1.83
85.66 go: downloading github.com/hashicorp/golang-lru/v2 v2.0.7
140.5 go: gitlab.txx..com/infrahi/odre/apis/client-go/informers/externalversions imports
140.5 	k8s.io/apimachinery/pkg/apis/meta/v1: k8s.io/apimachinery@v0.31.0: read "https://goproxy.cn/k8s.io/apimachinery/@v/v0.31.0.zip": read tcp 172.17.0.4:45862->163.181.140.200:443: read: connection reset by peer
140.5 go: gitlab.txx.com/infrahi/odre/apis/client-go/informers/externalversions imports
140.5 	k8s.io/apimachinery/pkg/runtime: k8s.io/apimachinery@v0.31.0: read 

### 尝试方案
用curl -Is 命令查看
> curl -Is https://goproxy.cn/k8s.io/apimachinery/@v/v0.31.0.zip

```shell
HTTP/2 200 
server: openresty
date: Thu, 05 Dec 2024 08:48:11 GMT
content-type: application/zip
content-length: 1080242
accept-ranges: bytes
content-md5: ZN1AsLBuGVJEms3TIpb3Tg==
content-transfer-encoding: binary
last-modified: Tue, 13 Aug 2024 15:48:50 GMT
vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
x-reqid: Ah0AAAB5fAuGlAkY
cache-control: public, max-age=604800
x-amz-request-id: Ah0AAAB5fAuGlAkY
x-log: X-Log
ctl-cache-status: HIT from ah-xuancheng1-ca28, HIT from zj-wenzhou10-ca63
request-id: e017675168cb27afe0cab2bdd9763af7
etag: "64dd40b0b06e1952449acdd32296f74e"
age: 19551
```

用curl -iv 查看

> curl -iv https://goproxy.cn/k8s.io/apimachinery/@v/v0.31.0.zip

```shell
*   Trying 39.175.224.42:443...
* TCP_NODELAY set
* Connected to goproxy.cn (39.175.224.42) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.goproxy.cn
*  start date: Aug 22 00:00:00 2024 GMT
*  expire date: Sep  7 23:59:59 2025 GMT
*  subjectAltName: host "goproxy.cn" matched cert's "goproxy.cn"
*  issuer: C=CN; O=TrustAsia Technologies, Inc.; CN=TrustAsia RSA DV TLS CA G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55dae4fb1e30)
> GET /k8s.io/apimachinery/@v/v0.31.0.zip HTTP/2
> Host: goproxy.cn
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
HTTP/2 200 
< server: openresty
server: openresty
< date: Thu, 05 Dec 2024 09:03:24 GMT
date: Thu, 05 Dec 2024 09:03:24 GMT
< content-type: application/zip
content-type: application/zip
< content-length: 1080242
content-length: 1080242
< accept-ranges: bytes
accept-ranges: bytes
< content-md5: ZN1AsLBuGVJEms3TIpb3Tg==
content-md5: ZN1AsLBuGVJEms3TIpb3Tg==
< content-transfer-encoding: binary
content-transfer-encoding: binary
< last-modified: Tue, 13 Aug 2024 15:48:50 GMT
last-modified: Tue, 13 Aug 2024 15:48:50 GMT
< vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
< x-reqid: Ah0AAAB5fAuGlAkY
x-reqid: Ah0AAAB5fAuGlAkY
< cache-control: public, max-age=604800
cache-control: public, max-age=604800
< x-amz-request-id: Ah0AAAB5fAuGlAkY
x-amz-request-id: Ah0AAAB5fAuGlAkY
< x-log: X-Log
x-log: X-Log
< ctl-cache-status: HIT from ah-xuancheng1-ca28, HIT from zj-wenzhou10-ca63
ctl-cache-status: HIT from ah-xuancheng1-ca28, HIT from zj-wenzhou10-ca63
< request-id: e06767516c5c27af00bd174208d6df97
request-id: e06767516c5c27af00bd174208d6df97
< etag: "64dd40b0b06e1952449acdd32296f74e"
etag: "64dd40b0b06e1952449acdd32296f74e"
< age: 20464
age: 20464

< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 3360)
* stopped the pause stream!
* Connection #0 to host goproxy.cn left intact

```

**Comment by aofei** [comment]
> "https://goproxy.cn/k8s.io/apimachinery/@v/v0.31.0.zip": read tcp 172.17.0.4:45862->163.181.140.200:443: read: connection reset by peer

这个 `163.181.140.200` 应该是海外节点，从国内直连海外节点出现类似 `read: connection reset by peer` 的问题是预期的。

请问你的本地 DNS 服务器配置是怎样的，为什么拿到了我们的海外 CDN 节点 IP 呢？另外，你用 `curl` 测试的输出显示你拿到的却又是国内 CDN 节点 IP。

**Comment by suxwang** [comment]
> > "https://goproxy.cn/k8s.io/apimachinery/@v/v0.31.0.zip": read tcp 172.17.0.4:45862->163.181.140.200:443: read: connection reset by peer
> 
> 这个 `163.181.140.200` 应该是海外节点，从国内直连海外节点出现类似 `read: connection reset by peer` 的问题是预期的。
> 
> 请问你的本地 DNS 服务器配置是怎样的，为什么拿到了我们的海外 CDN 节点 IP 呢？另外，你用 `curl` 测试的输出显示你拿到的却又是国内 CDN 节点 IP。

感谢你的回答， 我其实是写了一个dockerfile , 镜像是依赖于官方的golang:1.22.5这个版本，可能刚才我测试方法有问题， 我curl的方式是在宿主机上的， 而那个日志是通过dockerfile打包产生的

dockerfile文件如下：

```
FROM golang:1.22.5 AS builder

WORKDIR /u01/work
COPY . .
ENV GOPROXY=https://goproxy.cn,direct
# RUN go mod tidy
RUN go mod vendor
# RUN git diff --exit-code || (echo "Error: git modifications detected after go mod vendor" && exit 1)

RUN make build-dte
```

**Comment by aofei** [comment]
应该是你本地环境里的 DNS 配置有问题。可以在 Dockerfile 里加一条 `RUN cat /etc/resolv.conf` 看看它是什么。

**Comment by aofei** [comment]
其实就算是配置了 8.8.8.8 也应该可以正常解析到国内节点，我估计是你本地访问 8.8.8.8 时的出口 IP 是境外导致的。

那这个 issue 我就先关闭了，如果还有其他问题欢迎随时开新 issue 提问。
