### ISSUE TITLE
问题：502 Bad Gateway

### ISSUE THREAD

**Issue by wakaka6** [goproxy/goproxy.cn#222]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.22.4 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.io,direct'
GOROOT='/usr/local/src/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/src/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build774933[71](https://git.relaxcloud.cn/ai/auto-ht/-/jobs/22086#L71)1=/tmp/go-build -gno-record-gcc-switches'
</pre>
</details>

## 你实际看到的结果是什么？
go: github.com/tmaxmax/go-sse@v0.9.0-pre.2: reading https://goproxy.io/github.com/tmaxmax/go-sse/@v/v0.9.0-pre.2.info: 502 Bad Gateway
	server response: error code: 502

![image](https://github.com/user-attachments/assets/c5b12f95-e2e3-4615-9d19-976d231e5078)

**Comment by aofei** [comment]
你好，找错地方了，这里是 [goproxy.cn](https://goproxy.cn) 哦
