### ISSUE TITLE
问题：设置了goproxy代理，在编译go的时候，依然出现timeout

### ISSUE THREAD

**Issue by dajiang31835008** [goproxy/goproxy.cn#223]
mac环境，在终端配置文件和终端命令行里都设置了goproxy，但在安装airbyte到了build环节，还是出现go相关依赖库timeout的情况，请问是哪里没配置好？
 % export GO111MODULE=on
 export GOPROXY=https://goproxy.cn
 curl -LsfS https://get.airbyte.com | bash -
Installing for Darwin...
==> Fetching airbytehq/tap/abctl
==> Cloning https://github.com/airbytehq/abctl.git
Updating /Users/zhengdajiang/Library/Caches/Homebrew/abctl--git
==> Checking out tag v0.24.0
HEAD is now at 4dd803e fix: unstick helm commands by removing helm secrets (#154)
HEAD is now at 4dd803e fix: unstick helm commands by removing helm secrets (#154)
==> Installing abctl from airbytehq/tap
==> make build
Last 15 lines from /Users/zhengdajiang/Library/Logs/Homebrew/abctl/01.make:
internal/cmd/local/k8s/log.go:7:2: k8s.io/client-go@v0.31.3: Get "https://proxy.golang.org/k8s.io/client-go/@v/v0.31.3.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/k8s/cluster.go:16:2: sigs.k8s.io/kind@v0.25.0: Get "https://proxy.golang.org/sigs.k8s.io/kind/@v/v0.25.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/k8s/load_images.go:17:2: sigs.k8s.io/kind@v0.25.0: Get "https://proxy.golang.org/sigs.k8s.io/kind/@v/v0.25.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/k8s/load_images.go:18:2: sigs.k8s.io/kind@v0.25.0: Get "https://proxy.golang.org/sigs.k8s.io/kind/@v/v0.25.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/k8s/cluster.go:17:2: sigs.k8s.io/kind@v0.25.0: Get "https://proxy.golang.org/sigs.k8s.io/kind/@v/v0.25.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/k8s/load_images.go:20:2: sigs.k8s.io/kind@v0.25.0: Get "https://proxy.golang.org/sigs.k8s.io/kind/@v/v0.25.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/k8s/provider.go:13:2: sigs.k8s.io/kind@v0.25.0: Get "https://proxy.golang.org/sigs.k8s.io/kind/@v/v0.25.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/migrate/migrate.go:20:2: github.com/docker/docker@v27.4.0+incompatible: Get "https://proxy.golang.org/github.com/docker/docker/@v/v27.4.0+incompatible.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/migrate/migrate.go:21:2: github.com/docker/docker@v27.4.0+incompatible: Get "https://proxy.golang.org/github.com/docker/docker/@v/v27.4.0+incompatible.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/local/cmd.go:18:2: github.com/cli/browser@v1.3.0: Get "https://proxy.golang.org/github.com/cli/browser/@v/v1.3.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/local/status.go:9:2: go.opencensus.io@v0.24.0: Get "https://proxy.golang.org/go.opencensus.io/@v/v0.24.0.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/local/install.go:33:2: k8s.io/api@v0.31.3: Get "https://proxy.golang.org/k8s.io/api/@v/v0.31.3.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/local/local/install.go:35:2: k8s.io/apimachinery@v0.31.3: Get "https://proxy.golang.org/k8s.io/apimachinery/@v/v0.31.3.zip": dial tcp 142.251.215.241:443: i/o timeout
internal/cmd/cmd.go:10:2: github.com/alecthomas/kong@v1.6.0: Get "https://proxy.golang.org/github.com/alecthomas/kong/@v/v1.6.0.zip": dial tcp 142.251.215.241:443: i/o timeout
make: *** [build] Error 1

**Comment by aofei** [comment]
看起来是走了 make，具体里面是否有什么会导致你的环境变量配置被忽略我就不清楚了，总之结果反映确实是没延用你的配置。

可以尝试一下改用 `go env -w GOPROXY=https://goproxy.cn` 来配置。
