### ISSUE TITLE
Bug: go get 502 Bad Gateway

### ISSUE THREAD

**Issue by zmberg** [goproxy/goproxy.cn#224]
```
 % go version
go version go1.22.10 darwin/arm64
 % go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/xxxxx/Library/Caches/go-build'
GOENV='/Users/xxxxxx/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/xxxxxxxx/workspace/go/pkg/mod'
GONOPROXY='*gitlab.xxxxx-inc.com'
GONOSUMDB='*gitlab.xxxx-inc.com'
GOOS='darwin'
GOPATH='/Users/xxxxxxxxxx/workspace/go'
GOPRIVATE='*gitlab.xxxxx-inc.com'
GOPROXY='https://goproxy.io,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.10'
```

go get github.com/alibaba/pouch
go: downloading github.com/containerd/containerd/api v1.8.0
go: downloading github.com/RackSec/srslog v0.0.0-20180709174129-a4725f04ec91
go: downloading github.com/containernetworking/plugins v1.6.1
go: downloading github.com/containernetworking/cni v1.2.3
go: downloading github.com/docker/spdystream v0.5.0
go: downloading github.com/docker/go-events v0.0.0-20241114183025-9940093291f5
go: downloading github.com/moby/buildkit v0.18.2
go: downloading github.com/tchap/go-patricia v1.0.1
go: downloading k8s.io/kubernetes v1.32.0
go: github.com/RackSec/srslog@v0.0.0-20180709174129-a4725f04ec91: reading https://goproxy.io/github.com/%21rack%21sec/srslog/@v/v0.0.0-20180709174129-a4725f04ec91.zip: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/api/events: reading https://goproxy.io/github.com/containerd/containerd/api/events/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/api/types: reading https://goproxy.io/github.com/containerd/containerd/api/types/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/archive: reading https://goproxy.io/github.com/containerd/containerd/archive/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/contrib: reading https://goproxy.io/github.com/containerd/containerd/contrib/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/defaults: reading https://goproxy.io/github.com/containerd/containerd/defaults/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/diff: reading https://goproxy.io/github.com/containerd/containerd/diff/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/errdefs: reading https://goproxy.io/github.com/containerd/containerd/errdefs/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/events: reading https://goproxy.io/github.com/containerd/containerd/events/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/images/archive: reading https://goproxy.io/github.com/containerd/containerd/images/archive/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/images/oci: reading https://goproxy.io/github.com/containerd/containerd/images/oci/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/leases: reading https://goproxy.io/github.com/containerd/containerd/leases/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/mount: reading https://goproxy.io/github.com/containerd/containerd/mount/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/namespaces: reading https://goproxy.io/github.com/containerd/containerd/namespaces/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/pkg/progress: reading https://goproxy.io/github.com/containerd/containerd/pkg/progress/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/plugin: reading https://goproxy.io/github.com/containerd/containerd/plugin/@v/list: 502 Bad Gateway
	server response: error code: 502
go: module github.com/containerd/containerd/remotes: reading https://goproxy.io/github.com/containerd/containerd/remotes/@v/list: 502 Bad Gateway

**Comment by aofei** [comment]
你好走错了，这里是 [goproxy.cn](https://goproxy.cn) 哦
