### ISSUE TITLE
请问这里的代理包多久更新一次

### ISSUE THREAD

**Issue by CrazyPandas** [goproxy/goproxy.cn#23]
```sh
go.mod:8: require github.com/casbin/gorm-adapter: reading https://goproxy.cn/github.com/casbin/gorm-adapter/@v/v2.0.0.info: 404 Not Found
```
有好一些包获取到的都不是最新版本的，用`latest`标记获取到的也是一些较老的包

**Comment by aofei** [comment]
你好，是实时更新的。

你的 import path 写错了，你的 import path 只会使 go 拉取 v1.x.x，如果你想要拉取 v2.x.x 那么你得写成 github.com/casbin/gorm-adapter/v2，也就是有个 "/v2" 的后缀。

**Comment by aofei** [comment]
推荐阅读一下这个：https://github.com/golang/go/wiki/Modules#why-must-major-version-numbers-appear-in-import-paths

**Comment by aofei** [comment]
你按照你的这个目标模块的 `go.mod` 文件里首行的 module path 写你的 import path 就好：https://github.com/casbin/gorm-adapter/blob/4bda0062ff0c658b45459352ae75440d2b866fa7/go.mod#L1

**Comment by CrazyPandas** [comment]
谢谢你的帮助。
我也刚好看到了https://github.com/casbin/casbin/issues/267#issuecomment-510859978 这个
