### ISSUE TITLE
go mod download 404 Not Found  github.com/aliyun/aliyun-oss-go-sdk v2.0.2

### ISSUE THREAD

**Issue by stayfoo** [goproxy/goproxy.cn#24]
➜  chat git:(master) ✗ go mod download
go: finding github.com/aliyun/aliyun-oss-go-sdk v2.0.2
go: errors parsing go.mod:
/Users/mengyueping/go/my-demo/src/chat/go.mod:6: require github.com/aliyun/aliyun-oss-go-sdk: reading https://goproxy.cn/github.com/aliyun/aliyun-oss-go-sdk/@v/v2.0.2.info: 404 Not Found

**Comment by stayfoo** [comment]
添加 https://goproxy.cn,direct 后没有问题，问题和  https://github.com/goproxy/goproxy.cn/issues/25  一样。

**Comment by aofei** [comment]
你好，你这个跟 #25 不属于同一类，你这个是健康的 404 结果，因为它的确不存在，你应该用的包其实是这个 repo 下的一个子文件夹，也就是 `github.com/aliyun/aliyun-oss-go-sdk/oss`。你打开 `go` 打印的那个 URL 就可以看到具体的错误信息（ https://goproxy.cn/github.com/aliyun/aliyun-oss-go-sdk/@v/v2.0.2.info ）：

```
Not Found: unrecognized version
```

事实上，很多其他的模块代理就这一类场景会正常响应一个 `.info` 文件，而当到了用户请求 `.mod` 或者 `.zip` 文件时那些模块代理就又没有办法了，只能响应 404，这种模块代理的表现是不一致的，因为从一开始它就应该被 404 掉。

**Comment by stayfoo** [comment]
之前项目go.mod 是这样配置里面配置  github.com/aliyun/aliyun-oss-go-sdk v2.0.0+incompatible  是没问题的，可以把包拉下来；

这次使用  github.com/aliyun/aliyun-oss-go-sdk v2.0.2+incompatible 或者 github.com/aliyun/aliyun-oss-go-sdk/oss v2.0.2 都会报 404 。

配置代理 https://goproxy.cn,direct 后 github.com/aliyun/aliyun-oss-go-sdk v2.0.0+incompatible 能正常下载包。

**Comment by aofei** [comment]
这个问题似乎已经得到了解决，所以我就先关闭这个 Issue 了，如果还有问题欢迎随时提问，我会尽快响应的～😊
