### ISSUE TITLE
你好，我设置了GOPROXY为goproxy.cn后，go get 下载gorm出现依赖下载404

### ISSUE THREAD

**Issue by SJYeon** [goproxy/goproxy.cn#25]
![image](https://user-images.githubusercontent.com/11901423/65214500-c0928980-dadc-11e9-83ad-0d56c69950a7.png)

在公司因为公司网可以直接翻墙，将GOPROXY设置为空后，下载就正常了。
帮忙看一下是什么问题吧~ 
3Q~

**Comment by aofei** [comment]
你好，这是一个 bug，原因是 [jcmturner/rpc](https://github.com/jcmturner/rpc) 这个模块的作者事先发布了 v1.1.1 版本，接着被模块代理给缓存了，然后作者又删除了它才导致的这个错误发生，我们正在协商修复当中，具体请看 https://github.com/golang/go/issues/34141

在这个 bug 被修复之前，暂时的解决办法是更新时忽略掉这个模块，如果你是 Go 1.13 的话可以将 GOPROXY 设置为 `https://goproxy.cn,direct`，这样子就可以解决这个问题了，原理是当代理返回 404 时就去源头抓取。

**Comment by aofei** [comment]
不好意思，发错 issue 了，应该是这个：https://github.com/golang/go/issues/34033

**Comment by SJYeon** [comment]
没事 我的问题也帮忙看一下吧  哈哈哈

**Comment by aofei** [comment]
我的意思是我引用错 issue 了，我最上面回答的内容就是针对你的这个问题的。😅

**Comment by aofei** [comment]
你好，当前这个 Bug 已经被修复了，所以我就关闭这个 Issue 了哈，如果有后续问题可以继续反馈。😊
