### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by donnol** [goproxy/goproxy.cn#26]
```
go get -v github.com/rcrowley/go-metrics
```

> go get github.com/rcrowley/go-metrics: module github.com/rcrowley/go-metrics: Get 
> https://goproxy.cn/github.com/rcrowley/go-metrics/@v/list: net/http: TLS handshake timeout

```
go env
```

> ...
> GOPROXY="https://goproxy.cn,direct"
> ...

**Comment by donnol** [comment]
今天再试了一下，没有timeout了，不过出现了下面的问题：

``` 
GOPROXY=https://goproxy.cn,direct go get -v github.com/rcrowley/go-metrics
```

> go get github.com/rcrowley/go-metrics: module github.com/rcrowley/go-metrics: 
> Get https://goproxy.cn/github.com/rcrowley/go-metrics/@v/list: EOF

**Comment by donnol** [comment]
好像只在拉这个包才会有上面的问题，我拉golang.org/x/tools/gopls是没问题的。

**Comment by houz42** [comment]
我这比较频繁, 每次跑 ci 总有几个任务在这里出问题, 难道是 CDN 不够稳定吗

**Comment by aofei** [comment]
@houz42 麻烦简单说一下你的网络环境，比如哪家运营商，什么带宽之类的。

顺便说一下，这一阵子是特殊时期，虽然 [goproxy.cn](https://goproxy.cn) 完全合法，且服务器也在国内，但仍然无法避免由于网络审查而造成的网络不稳定的情况发生。目测此次审查力度前所未有地大，而且还是无差别审查，国内服务多少都会受到影响。

**Comment by clearcodecn** [comment]
☁  apiserver [75-fix-nagative-value] ⚡  go get gonum.org/v1/plot/...                             
go get gonum.org/v1/plot/...: module gonum.org/v1/plot: reading https://goproxy.cn/gonum.org/v1/plot/@v/list: 502 Bad Gateway

**Comment by aofei** [comment]
@clearcodecn 你好，请问你一直在遇见 502 错误吗？我刚才检查了一下日志，你评论的前后 1 小时内的确出现了几次 502，但并不是太多。

**Comment by clearcodecn** [comment]
@aofei 我昨天用的时候也是502，更换了代理后 今天又尝试使用了一下，
问题依旧，我还有为是代理挂了，原来只有我一个人下载不到。:cry:

**Comment by aofei** [comment]
@clearcodecn 那就神奇了，不应该的呀，你能提供以下你的网络环境嘛？地理位置，电信运营商等等。

**Comment by clearcodecn** [comment]
四川成都，中国电信网络.

**Comment by mercury7720** [comment]
同成都电信，不管 get 什么包都是
```
package golang.org/x/crypto/ssh: unrecognized import path "golang.org/x/crypto/ssh" (https fetch: Get https://golang.org/x/crypto/ssh?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```

**Comment by aofei** [comment]
@mercury7720 

你好，你这个错误跟他们并不一样，你这个错误说明你并没有在用 Go modules，所以也就谈不上在用 goproxy.cn 了。

你可以把 GO111MODULE 改成 on 再试试。

**Comment by mercury7720** [comment]
感谢，已解决

**Comment by mercury7720** [comment]
> @mercury7720
> 
> 你好，你这个错误跟他们并不一样，你这个错误说明你并没有在用 Go modules，所以也就谈不上在用 goproxy.cn 了。
> 
> 你可以把 GO111MODULE 改成 on 再试试。

感谢，已解决

**Comment by aofei** [comment]
你好，我想问一下各位遇见 TLS 握手超时错误的老哥，你们在遇到这个错误时的环境是什么？是处于 Docker 环境中吗？如果是的话，那可能就是你们的网络问题了，因为昨天晚上恰好有一个朋友也遇到了并在微信群里问了，通过截图我才了解到他是处在 Docker 环境中。

至于为什么网络差会导致 Docker 环境中出现类似问题是因为 Docker 大多是干净的环境，Go modules 在初始化构建时会**并行地**发出大量的请求，依据项目依赖的模块量不同发出的请求数量也不等，如果此时恰好 Docker 环境所在的网络较差，那很可能出现有一个或多个请求到达 TLS 握手超时时间限制而导致整体构建失败掉。

而在 Docker 环境之外，由于咱们有本地缓存，所以即使是构建一个新的项目也并不一定会去把那个项目所有依赖的模块都去拉取一遍，这样请求数少了出现 TLS 握手超时时间的概率也就低了。

实际上，在这个 Issue 被提两个多月以来，我一直在关注着 TLS 握手超时错误，但我一次也没有遇见过（可能是我自己的网络比较好的缘故），我周边的人也一次都没有跟我反馈过，直到昨晚微信群里的一个朋友遇到了一次。所以，这个错误我完全没有思路该怎么解决。🥺

麻烦老哥们帮我回忆确认一下出现 TLS 握手超时的时候你们是否正处于 Docker 环境且恰好有一个比较差的网络？🙏

**Comment by clearcodecn** [comment]
@aofei 我是在公司自己本子上下载的，公司网络环境不太好，
但是最近没有出现这种情况。

**Comment by donnol** [comment]
我这边出现这个问题的时候，没有在Docker环境里呢。我用的是wsl的终端做的操作。

**Comment by aofei** [comment]
@clearcodecn @donnol 感谢两位老哥的回复！

破案了破案了！这里 TLS 握手超时的具体原因我已经找到了，是因为大家当时的网络较差所导致的，因为 Go modules 目前在用的 `http.Client` 是[这个](https://github.com/golang/go/blob/8a5af7910a9b157c02736c3e0998a587bb8511c1/src/cmd/go/internal/web/http.go#L44)，它所用的 `http.Transport` 是 `http.DefaultTransport`，也就是[这个](https://github.com/golang/go/blob/980f0c00bb07b01d2150a5b858573d9ba0a15890/src/net/http/transport.go#L42)，其中所指定的 `TLSHandshakeTimeout` 是 10 秒，这对于正常的网络来说是非常充足的，但对于较差的网络可能就不够了。就像我在上面说的，Go modules 在拉取模块文件时会**并行地**发出大量的 HTTPS 请求，此时如果其中的任意一条 TLS 握手超时都会导致整体构建失败，而恰好大家当时的网络可能比较差，所以有那么一两条 TLS 握手超时掉了，于是大家就得到了那个错误。

那么以后大家再遇到这个问题该怎么解决呢？要么跟老板投诉让给大家改善一下工作环境的网络，要么多尝试几次，依靠 Go modules 的缓存机制一部分一部分地拉取，直到所有的都拉取成功（讲道理还是投诉给老板方便些）。

那么，鉴于问题已解决，那我就关闭这个 Issue 了哦～哈哈开心😊~不是 [goproxy.cn](https://goproxy.cn) 的锅就非常舒服了～✌️

如果大家以后再遇到别的问题欢迎随时反馈哦～我还是会继续保持尽快回应的～💪
