### ISSUE TITLE
proxy returned info for version XXX instead of requested version

### ISSUE THREAD

**Issue by maooyer** [goproxy/goproxy.cn#27]
>go mod download
>go: finding github.com/prometheus/client_model v0.0.0-20190220174349-fd36f4220a90
>github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90: proxy returned info for version v0.0.0-20190129233127-fd36f4220a90 instead of requested version

===========================
使用 `goproxy.cn` 下载会出现上述错误，使用 `direct` 模式或阿里云镜像则下载正常

go version: 1.13

**Comment by aofei** [comment]
你好，首先，[goproxy.cn](https://goproxy.cn) 做错了，错在不应该为 https://goproxy.cn/github.com/prometheus/client_model/@v/v0.0.0-20190220174349-fd36f4220a90.info 返回下述响应：

```
{"Version":"v0.0.0-20190129233127-fd36f4220a90","Time":"2019-01-29T23:31:27Z"}
```

而是应该报 404 错误，因为这个模块的版本信息是你写错了的，假定版本号里的时间戳和目标 commit 的时间出不符合，[goproxy.cn](https://goproxy.cn) 返回的这个 `2019012923312` 才是正确的时间戳，而你的 `go.mod` 文件中用的是 `20190220174349`，用错了。相见：https://github.com/prometheus/client_model/commit/fd36f4220a901265f90734c3183c5f0c91daa0b8

其次是并不像你想的那样儿，阿里云的模块代理在这里是整个就做错了，你能正常使用它是因为它帮你掩饰了这个错误，因为它居然返回了一个拥有错误信息的但却和请求 https://mirrors.aliyun.com/goproxy/github.com/prometheus/client_model/@v/v0.0.0-20190220174349-fd36f4220a90.info 完全相匹配的假定版本号：

```
{"Version":"v0.0.0-20190220174349-fd36f4220a90","Time":"2019-01-29T23:31:27Z"}
```

注意看它的时间戳是错的。

你用 `direct` 之所以可以成功，是因为 `go` 在 `direct` 模式下抓取模块时会自己推算假定版本号，推算过程中没有验证你的时间戳，只验证了你的 `go.sum` 文件中的哈希值，故而导致你的错误时间戳“瞒”过了 `go`。这实际上也是有问题的，因为 `go` 在 `direct` 下也应该报错才是，Go modules 现在还不够完善，有些小问题也可以理解。

目前来说，所有的模块代理，无论是 [goproxy.cn](https://goproxy.cn) 还是阿里云的那个，都应该为你的这个请求返回 404 错误，然后如果你的环境变量是 `GOPROXY=https://goproxy.cn,direct` 这种包含 fallback 到 `direct` 的设定，那么在模块代理返回 404 错误时 `go` 就会自动去尝试 `direct`，然后就能成功了。

我马上就为 [goproxy.cn](https://goproxy.cn) 删除缓存中所有 .info 文件中的版本信息和请求中的版本信息不匹配的模块版本，等删除完后我通知你。

而你需要做的是，检查一下为什么你的 `go.mod` 或 `go.sum` 文件中会有这个错误的假定版本信息，是手动修改的还是自动生成的，如果是自动生成的那就是 `go` 的 bug，如果是手动修改的，那……我就不清楚为什么要这么做了。

**Comment by maooyer** [comment]
感谢回复，我检查后发现是引用的第三方库的 `go.mod` 有错误
https://github.com/bilibili/kratos/blob/b6d8968cd3d4685599223974b98b6d33c4ca4a6f/go.mod#L33

**Comment by aofei** [comment]
你好，有误的 .info 文件缓存已经清理完毕了，你现在请求 https://goproxy.cn/github.com/prometheus/client_model/@v/v0.0.0-20190220174349-fd36f4220a90.info 会得到一个 404 响应了，也就是目前我们期望的正确响应：

```
Not Found: github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90: invalid pseudo-version: does not match version-control timestamp (2019-01-29T23:31:27Z)
```

至于这个 Kratos 模块存在的错误 `go.mod` 文件，希望你能去它的仓库提个 issue，如果你方便的话。😊

**Comment by maooyer** [comment]
验证现在可以正常下载，同时问题也反馈给 Kratos 了

**Comment by aofei** [comment]
👍 好的，由于问题已解决那么我就关闭这个 issue 了，感谢你前来反馈这个问题！🙏
