### ISSUE TITLE
go get sigs.k8s.io/kubebuilder@v2.0.1: unexpected status (https://goproxy.cn/sigs.k8s.io/kubebuilder/@v/v2.0.1.info): 404 Not Found

### ISSUE THREAD

**Issue by 644262163** [goproxy/goproxy.cn#28]
go version go1.12.7 linux/amd64

使用 export GOPROXY=https://goproxy.cn 拉这个包会报错
go get sigs.k8s.io/kubebuilder@v2.0.1: unexpected status (https://goproxy.cn/sigs.k8s.io/kubebuilder/@v/v2.0.1.info): 404 Not Found

去掉代理后 export GOPROXY= go get是正常的

**Comment by aofei** [comment]
你好，你访问 `go` 打印的那个错误的 URL 就可以看到详细错误信息的：

https://goproxy.cn/sigs.k8s.io/kubebuilder/@v/v2.0.1.info

```
Not Found: sigs.k8s.io/kubebuilder@v2.0.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

所以这是一个健康的 404，出错的原因是你的这个目标模块版本中存在的 `go.mod` 文件并不是你在用的这个 `sigs.k8s.io/kubebuilder`，而是别的，所以需要你纠正你的 import path。

**Comment by 644262163** [comment]
你好，感谢回复。

我这里没太理解纠正你的 import path的意思，还是不太清楚怎样可以正常拉到这个包？是类似这样嘛```go get sigs.k8s.io/kubebuilder/v2@v2.0.1```可是也都失败了。

而且我看了下sigs.k8s.io/kubebuilder@v2.0.1中的的go.mod中就是```module sigs.k8s.io/kubebuilder```

还有个不太明白的地方是如果不配置代理go get是正常的没有404

**Comment by aofei** [comment]
抱歉，先前没注意你用的是 Go 1.12.7。

是这样的，[goproxy.cn](https://goproxy.cn) 总是用的最新版本的 Go（目前是 Go 1.13），而此类项在 Go 1.13 中检查变得更加严格，所以你用 Go 1.12.7 可以通过是因为 Go 1.12.7 检查还是相对较弱的。如果可以的话你升级到 Go 1.13 中在测试一下就知道了，会报同样的错错误：

```go
$ GOPROXY=direct GOSUMDB=off go get sigs.k8s.io/kubebuilder@v2.0.1
```

此外我也发现你的这个目标模块版本的 `go.mod` 文件中的模块路径的确是 `module sigs.k8s.io/kubebuilder`，但是似乎这个目标仓库并不打算作为一个模块来让人使用，看它的 `README.md` 文件里有说到：

> ## Installation
> 
> It is strongly recommended that you use a released version. Release binaries are available on the [releases](https://github.com/kubernetes-sigs/kubebuilder/releases) page. Follow the [instructions](https://book.kubebuilder.io/quick-start.html#installation) to install Kubebuilder.

所以建议你换个姿势操作这个仓库。

**Comment by 644262163** [comment]
感谢 是那个仓库的问题 https://github.com/kubernetes-sigs/kubebuilder/issues/1042#issuecomment-536804621
