### ISSUE TITLE
golang.org/x/crypto/bcrypt  安装失败

### ISSUE THREAD

**Issue by hezhizheng** [goproxy/goproxy.cn#30]
![](https://ws1.sinaimg.cn/large/006c53jqgy1g7gjbl2q7pj31fp04ogm7.jpg)

**Comment by aofei** [comment]
你好，这说明你并没有配置好 GOPROXY 或者并没有启用 Go modules 呢，麻烦你看看 https://github.com/goproxy/goproxy.cn/issues/29 试一下能不能解决你的问题吧～

**Comment by hezhizheng** [comment]
开启Go modules 之后也解决不了这个问题，github 上的包都能够正常安装，是不是只有 golang.org 上的包才会出现这个问题，看了网上好多解决方案都是搭梯子设置代理 ？
```
set http_proxy=127.0.0.1:1080
set https_proxy=127.0.0.1:1080
```

**Comment by aofei** [comment]
首先，可以确认的是，这个问题肯定是可以通过使用 GOPROXY 来解决的，不需要用别的代理方案。

这样子，你发一下你的 go env 截图给我看看，我帮你探究一下。

**Comment by hezhizheng** [comment]
有劳！
![Snipaste_2019-09-29_22-32-32.png](https://i.loli.net/2019/09/29/A8XvaoEI15eqTN7.png)

**Comment by aofei** [comment]
我注意到你还是 Go 1.12.9 呢，所以你不能用 `go env -w GO111MODULE=on` 的写法来启用 Go modules，你得手动为 Go 设置系统环境变量，也就是按照你设置 GOPROXY 这个环境变量时的方法来设置 GO111MODULE，比如用 `export GO111MODULE=on` 就可以启用了。

另外，强力建议升级到 Go 1.13，因为解决了很多很多跟 Go modules 相关的 Bug，也推出了很多相关的新特性。全面了解 Go 1.13 中的 Go modules，建议有时间的话就观看我这周四在【Go 夜读】做的在线直播分享，讲得相对比较全面：https://github.com/developer-learning/night-reading-go/issues/468

**Comment by hezhizheng** [comment]
> 我注意到你还是 Go 1.12.9 呢，所以你不能用 `go env -w GO111MODULE=on` 的写法来启用 Go modules，你得手动为 Go 设置系统环境变量，也就是按照你设置 GOPROXY 这个环境变量时的方法来设置 GO111MODULE，比如用 `export GO111MODULE=on` 就可以启用了。
> 
> 另外，强力建议升级到 Go 1.13，因为解决了很多很多跟 Go modules 相关的 Bug，也推出了很多相关的新特性。全面了解 Go 1.13 中的 Go modules，建议有时间的话就观看我这周四在【Go 夜读】做的在线直播分享，讲得相对比较全面：[developer-learning/night-reading-go#468](https://github.com/developer-learning/night-reading-go/issues/468)

感谢，我在尝试一下
