### ISSUE TITLE
go get github.com/gohugoio/hugo失败

### ISSUE THREAD

**Issue by keob** [goproxy/goproxy.cn#33]
##### verifying cloud.google.com/go@v0.46.3/go.mod: cloud.google.com/go@v0.46.3/go.mod: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/cloud.google.com/go@v0.46.3: 502 Bad Gateway

**Comment by aofei** [comment]
难得的 502 呢，谢谢反馈！我一会儿去后台找找看是哪台服务器。

你可以再试一次应该就行了，目前的话，我在我这里测试是没有出现问题的，https://goproxy.cn/sumdb/sum.golang.org/lookup/cloud.google.com/go@v0.46.3

**Comment by keob** [comment]
谢谢了

**Comment by keob** [comment]
@aofei 我试了阿里的也错了，但是错误不一样😀

**Comment by aofei** [comment]
因为阿里的那个不支持代理 sum.golang.org（被墙了），所以通常就是用了就无法检验模块版本了，除非你的系统使用了其他代理手段

**Comment by keob** [comment]
@aofei 明白了🤞

**Comment by keob** [comment]
### 环境 Windows10
### go版本 1.31.1
### 错误
go get github.com/gohugoio/hugo: module github.com/gohugoio: reading https://goproxy.cn/github.com/gohugoio/@v/list: 502 Bad Gateway
##### 看来你是睡不了觉了

**Comment by keob** [comment]
##### 建议你先试一下，我不保证后面还有，我不是很急着用，你可以慢慢来🤞

**Comment by aofei** [comment]
诶？你那里还是不行嘛？奇怪了，502 错误的话理应是服务器的问题了，但是我刚检查了服务器是正常的呢，而且我刚自己又在我这执行了一下 `go get -u -v github.com/gohugoio/hugo` 也是一切正常，报了个正常的错误（这个错误是目标模块自己本身的错误）：

```
build github.com/gohugoio/hugo: cannot load github.com/nicksnyder/go-i18n/i18n/bundle: module github.com/nicksnyder/go-i18n@latest (v2.0.2+incompatible) found, but does not contain package github.com/nicksnyder/go-i18n/i18n/bundle
```

这样，麻烦你 `ping goproxy.cn` 一下，然后告诉我你拿到的那台 CDN 节点的 IP，我看能不能排查一下。

**Comment by aofei** [comment]
如果方便的话地理位置和电信运营商也麻烦告知一下。😊

**Comment by keob** [comment]
地理位置是湖北黄石运营商是中国电信

**Comment by aofei** [comment]
执行 `ping goproxy.cn` 拿到了哪个 IP？还有你顺便可以刷新一下本地 DNS 缓存后再试试看能不能成功。先 `ping` 一下把现在的 IP 告知我我好排查，刷新本地 DNS 缓存后可能会变的。

**Comment by keob** [comment]
@aofei 刷新前是124.239.234.244,不成功，但是不是404
build github.com/gohugoio/hugo: cannot load github.com/nicksnyder/go-i18n/i18n/bundle: module github.com/nicksnyder/go-i18n@latest (v2.0.2+incompatible) found, but does not contain package github.com/nicksnyder/go-i18n/i18n/bundle看着应该是项目本身的问题。

**Comment by keob** [comment]
看一一下github.com/nicksnyder/go-i18n/i18n/bundle已经更行了，得换一下导入的路径或者版本

**Comment by aofei** [comment]
这个错误是正常的，不属于代理这边的错误了，是项目本身的问题。不过你去掉 `-u` 也就是不执行更新模块版本的操作的话是可以成功的，也就是：`go get -v github.com/gohugoio/hugo`

无论如何再次感谢你，我去排查一下那个节点。

**Comment by keob** [comment]
嗯，但是github.com/nicksnyder/go-i18n/i18n/bundle在新版确实有问题，第三方仓库改的太激进了，删了文件夹

**Comment by keob** [comment]
好了，感谢帮帮忙，辛苦了。从错误中学到了新的知识，谢谢。🤞

**Comment by aofei** [comment]
嗯嗯，不客气，另外这个 CDN 节点我也刚排查完了，并没有出现任何问题，我在服务器后台日志中也没有找到对应时段的错误，实际上 24 小时前到现在日志里都没有出现过一条异常的服务器端错误，奇怪了……不过我记下了，我明天再深入调查一下，先休息了。感谢反馈～😊

**Comment by aofei** [comment]
最新的程序版本已提交到服务器，并作了一些优化，这个问题应该已经得到改善了，所以就暂时关闭这个 Issue 了。如果还有其他问题欢迎随时提问，我会尽快响应的！并且接下来我也会持续追踪日志中的 502 情况，并持续优化下去，辛苦你的反馈！😊

**Comment by keob** [comment]
谢谢了
