### ISSUE TITLE
build command-line-arguments: cannot load golang.org/x/crypto/acme/autocert: module golang.org/x/crypto: reading https://goproxy.cn/golang.org/x/crypto/@latest: 503 Service Unavailable

### ISSUE THREAD

**Issue by Zhangzijing** [goproxy/goproxy.cn#34]

**Comment by aofei** [comment]
你好，请问一直在出嘛？我刚才试了一下，发现我这边儿没有出现呢。要不你试试刷新一下你电脑的 DNS 缓存？

**Comment by Zhangzijing** [comment]
现在已经好了。可能是临时出现的难以复现的问题

**Comment by JonasAi** [comment]
我也遇到这样的问题
build command-line-arguments: cannot load github.com/labstack/echo: module github.com/labstack/echo: Get https://goproxy.cn/github.com/labstack/echo/@v/list: net/http: TLS handshake timeout

**Comment by JonasAi** [comment]
> 我也遇到这样的问题
> build command-line-arguments: cannot load github.com/labstack/echo: module github.com/labstack/echo: Get https://goproxy.cn/github.com/labstack/echo/@v/list: net/http: TLS handshake timeout

刷新DNS缓存还是无效,怀疑是写 `.zshrc `文件未生效导致的,在vscode 中 `source ~/.zshrc `也不行,最后在 vscode 的终端中 `exit`,然后重新开一个在执行 `go run ...`就可以了,但是还是没最终确定是不是 vscode 的坑

**Comment by aofei** [comment]
@JonasAi 

TLS 握手超时的问题我们正在排查，虽然我们自己一次没有遇见过，但最近确实有不少人来反馈了这个问题，所以我们也很想知道原因。谢谢你的反馈！

另外，如果是 IDE 使用中出现了问题，建议首先去终端环境尝试一遍以检查 `GO111MODULE` 和 `GOPROXY` 两个环境变量是否都配置正确，检查方式可以在终端执行一条简单的命令：

```bash
$ go list -m -json golang.org/x/text@latest
```

然后看能不能正常打印结果。如果终端环境一切正常，那么说明是 IDE 中的配置出现了问题。

**Comment by aofei** [comment]
经最近几天的日志反映来看并没有再出现过 503 的情况，所以这个 Issue 我就先关闭了哈，如果有其他问题欢迎随时提问，我会尽快响应的～😊

**Comment by duanzhao-dz** [comment]
build command-line-arguments: cannot load github.com/labstack/echo: module github.com/labstack/echo: Get https://proxy.golang.org/github.com/labstack/echo/@v/list: dial tcp 172.217.160.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
同样的问题

**Comment by aofei** [comment]
@duanzhao-dz 你好，你并没有在使用 [goproxy.cn](https://goproxy.cn) 哦，你还是在使用默认的被墙了的 [proxy.golang.org](https://proxy.golang.org)，所以你连接失败了。

正确的配置方法请参考[这里](https://github.com/goproxy/goproxy.cn/blob/master/README.zh-CN.md#用法)。
