### ISSUE TITLE
go get github.com/micro/go-plugins: zip: not a valid zip file

### ISSUE THREAD

**Issue by zuimei0603** [goproxy/goproxy.cn#37]
go get github.com/micro/go-plugins
go: downloading github.com/micro/go-plugins v1.4.0
go get github.com/micro/go-plugins: zip: not a valid zip file

**Comment by aofei** [comment]
你好，已经临时修复了，你现在应该可以正常获取了。

不过蛮奇怪的，这种情况不应该发生才是，我已经记录了，一会儿要好好调查一下，非常感谢你的反馈！😊

**Comment by zzjin** [comment]
同样的错误
```shell
go get -u github.com/iGoogle-ink/gopay
go: downloading github.com/iGoogle-ink/gopay v1.4.1
go get: zip: not a valid zip file
```

**Comment by aofei** [comment]
@zzjin 嗯嗯，谢谢你，我刚才刷新了一下缓存，你现在应该就可以正常获取了～😊

此外，这个问题我前两天已经追踪到原因了，已经修复好了，会尽快提交的。

**Comment by zzjin** [comment]
还是不行
still output same  error

**Comment by aofei** [comment]
@zzjin 

我刚才在我这里试了一下已经正常了的，所以那个资源本身已经被修复了。你那边儿如果还是有这个问题的话就只可能是 CDN 缓存导致的了，不过奇怪的是我昨天已经刷新过一次 CDN 缓存了。无论如何，我刚才又针对那个资源进行了 CDN 缓存刷新，麻烦你过几分钟后再尝试一两次可以嘛？如果还有问题的话可以先试一下执行 `go clean -modcache` 然后再拉取，还是不行的话再反馈给我我看一下原因。幸苦老哥了！😊

**Comment by zzjin** [comment]
@aofei 
还是不行 
执行`go clean -modcache`之后还是一样报错

**Comment by aofei** [comment]
@zzjin 最新的代码已提交，服务器程序已更新，当前这个问题应该算是解决了，麻烦老哥你确认一下是不是可以正常获取了，可以正常获取的话我就可以关闭这个 Issue 了。😊

**Comment by zzjin** [comment]
好了.
done.
Thx for quick resp.

**Comment by aofei** [comment]
那我就关闭这个 Issue 了哈，如果再次遇到的话可以随时反馈，我会尽快响应的～😊
