### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by lnnujxxy** [goproxy/goproxy.cn#38]
cloud.google.com/go@v0.37.4: reading https://goproxy.cn/cloud.google.com/go/@v/v0.37.4.zip: 502 Bad Gateway

配置了，偶尔提示这个错误

**Comment by aofei** [comment]
你好，我想我还是分享一下原由吧。

是这样子的，昨天下午我更新了后台服务器的程序，想着为了能更好地服务大家我就刷新了 CDN 缓存，我没料想到现在 [goproxy.cn](https://goproxy.cn) 请求量如此之大，大量的请求回源到了后台服务器，后台服务器一下没反应过来故而没扛住。随后我做了一些调整有了一定地改善，现在已经逐步恢复到了平常的状态。另外我刚才分析了一下今天的日志，502 次数已经明显下降（平均三百条请求能出一次），估计再过几个小时就基本不会再出了。接下来我们会持续改进后台服务的架构，为大家提供更好的服务。

所以，临时的解决办法是多执行几次出 502 的那条命令就可以了，因为服务器在轮询提供服务。

总之，我的操作失误，往后会避免再次出现这种失误，抱歉了！☹️

**Comment by Liv1020** [comment]
同志是好同志，就是操作有点骚。

**Comment by fanlide** [comment]
502有点伤啊，今天依然有出现。尤其执行`go get -u`，中间总有那么几个会出现502……
