### ISSUE TITLE
如何避免内网gitlab包走goproxy.cn

### ISSUE THREAD

**Issue by Dongss** [goproxy/goproxy.cn#39]
如何避免内网gitlab包走goproxy.cn？大家有合适的实践吗

**Comment by aofei** [comment]
假设你们公司的内网 GitLab 地址是 `gitlab1.example.com` 和 `gitlab2.example.com`，且你的 Go  >= 1.13，那么你可以进行如下步骤：

1. 设置环境变量：`export GOPROXY=https://goproxy.cn,direct`（需要保证包含 `,direct` 后缀）
2. 设置环境变量：`export GOPRIVATE=gitlab1.example.com,gitlab2.example.com`
3. 参考 https://golang.org/doc/faq#git_https 将你的 `~/.gitconfig` 文件中追加如下内容：
```gitconfig
[url "ssh://git@gitlab1.example.com/"]
	insteadOf = gitlab1.example.com/
[url "ssh://git@gitlab2.example.com/"]
	insteadOf = gitlab2.example.com/
```
4. 参考 https://docs.gitlab.com/ee/gitlab-basics/create-your-ssh-keys.html 以保证你的当前用户的 SSH key 拥有对 `gitlab1.example.com` 和 `gitlab2.example.com` 对应库的读取权限

这样就足够了。

**Comment by Dongss** [comment]
THX! @aofei

**Comment by eryajf** [comment]
配置部署了一下，内网的包可以拉取了，不过有一个问题想请教一下，是否支持将拉到的包缓存到本地的功能，看起来似乎不支持。

**Comment by aofei** [comment]
@eryajf 

你好，设置 `GOPRIVATE` 来绕过 `GOPROXY` 依然是走 Go 模块功能的正常流程，也就是说同样可以默认缓存数据到 `$GOPATH[0]/pkg/mod` 目录中。

此外，如果你想使用其他缓存机制，比如缓存到某个对象存储服务中，或者自定义缓存方式，那你可以参考 [goproxy.cn](https://goproxy.cn) 首页底部提到的“自托管 Go 模块代理”来搭建一个你们自己的本地 Go 模块代理，[Goproxy](https://github.com/goproxy/goproxy) 这个项目是支持自定义 [`goproxy.Cacher`](https://pkg.go.dev/github.com/goproxy/goproxy#Cacher) 的。例如下述代码表示缓存到本地磁盘：

```go
package main

import (
	"net/http"
	"os"

	"github.com/goproxy/goproxy"
	"github.com/goproxy/goproxy/cacher"
)

func main() {
	g := goproxy.New()
	g.GoBinEnv = append(
		os.Environ(),
		"GOPROXY=https://goproxy.cn,direct", // 使用 goproxy.cn 作为上游代理
		"GOPRIVATE=git.example.com",         // 解决私有模块的拉取问题（比如可以配置成公司内部的代码源）
	)
	g.Cacher = &cacher.Disk {
		Root: "/some/dir/path",
	}
	g.ProxiedSUMDBs = []string{"sum.golang.org https://goproxy.cn/sumdb/sum.golang.org"} // 代理默认的校验和数据库
	http.ListenAndServe("localhost:8080", g)
}
```

**Comment by eryajf** [comment]
感谢回复，经过测试这是可以的
