### ISSUE TITLE
get golang.org/x/还是下载不下来.

### ISSUE THREAD

**Issue by 2030405043** [goproxy/goproxy.cn#40]
go version: 1.13 
goproxy: https://goproxy.cn,direct

请问这是什么原因?

**Comment by aofei** [comment]
你好，请问具体报的什么错呢？还有麻烦顺便提供一下你的 go env 内容，以便参考。

**Comment by aofei** [comment]
由于长时间没有回应所以我就先关闭这个 Issue 啦哈，如果有其他问题老哥可以随时重新开启或者开新的 Issue～😊

**Comment by ego008** [comment]
我这遇到的错误

```
fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Operation timed out
```

**Comment by aofei** [comment]
@ego008 你好，你这个错误说明你并没有在用 Go modules，所以也就谈不上在用 goproxy.cn 了。

你现在需要做的是先把你的 GO111MODULE 环境变量设置成 on 后再试一次。
