### ISSUE TITLE
请教一个问题 使用god+goproxy编译已有项目时经常会遇到echo无法正常驱动

### ISSUE THREAD

**Issue by wulorn** [goproxy/goproxy.cn#42]
go: finding github.com/labstack/echo v0.0.0-20190621131255-858270f6f5e4
go: github.com/labstack/echo@v0.0.0-20190621131255-858270f6f5e4: unexpected status (https://goproxy.cn/github.com/labstack/echo/@v/v0.0.0-20190621131255-858270f6f5e4.info): 404 Not Found
go: error loading module requirements

请教一个问题 使用god+goproxy编译已有项目时经常会遇到echo无法正常驱动，但是通过本地包replace替换之后，再次取消replace ，又可以正常工作了

**Comment by aofei** [comment]
你好，你只要打开这个错误链接 https://goproxy.cn/github.com/labstack/echo/@v/v0.0.0-20190621131255-858270f6f5e4.info 就能看到具体的错误信息的：

```
Not Found: github.com/labstack/echo@v0.0.0-20190621131255-858270f6f5e4: invalid version: go.mod has post-v0 module path "github.com/labstack/echo/v4" at revision 858270f6f5e4
```

这个错误的意思是，你所用的这个模块版本的模块路径是 `github.com/labstack/echo/v4`（详见：[这里](https://github.com/labstack/echo/blob/5c7c87d09e23a8943f71f3057030919fb28f1349/go.mod#L1)），而你的 `go.mod` 文件中写的是 `github.com/labstack/echo`，所以不匹配导致了错误。

你现在需要做的是修改你的 `go.mod` 文件中对应的模块路径，并把代码中所有对应的导入路径一并替换，这样就可以了。😊

**Comment by wulorn** [comment]
非常感谢，我通过replace更换为本地的v4版本是可以的😊

**Comment by aofei** [comment]
因为问题解决了所以我就关闭这个 Issue 啦哈，如果有其他问题老哥可以随时开新的 Issue～😊
