### ISSUE TITLE
错误代码 478

### ISSUE THREAD

**Issue by cragsxie** [goproxy/goproxy.cn#43]
verifying github.com/fsnotify/fsnotify@v1.4.7: github.com/fsnotify/fsnotify@v1.4.7: readi
ng https://goproxy.cn/sumdb/sum.golang.org/lookup/github.com/fsnotify/fsnotify@v1.4.7: 50
0 Internal Server Error

**Comment by cragsxie** [comment]
重试成功了，又有新错误
go: downloading github.com/pquerna/ffjson v0.0.0-20181028064349-e517b90714f7
verifying github.com/micro/go-micro@v1.9.0: github.com/micro/go-micro@v1.9.0: reading htt
ps://goproxy.cn/sumdb/sum.golang.org/tile/8/0/573: 502 Bad Gateway

**Comment by aofei** [comment]
抱歉哈，刚才后台这边儿在调整配置，所以出了些问题，现在应该已经正常了，我这里试着是可以正常访问了，你再试试看？

**Comment by aofei** [comment]
502 的问题等调整完服务器后就可以解决啦，目前的话你可以暂时多试几次 502 的那条请求😁

**Comment by terryding77** [comment]
这几天有好几次失败了= =，建议在网站里挂个healthcheck的页面，方便大家确认是服务端的问题还是我们自己内部网络问题～

**Comment by cragsxie** [comment]
verifying github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967: github.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/g
ithub.com/robfig/cron@v0.0.0-20180505203441-b41be1df6967: 478
新的错误？

**Comment by aofei** [comment]
@terryding77 这次的改动就是因为这一阵子 goproxy.cn 访问量变大了，所以后台得作出相应的调整，不然会 hold 不住访问量然后 502 增多。

**Comment by cragsxie** [comment]
重试了好几次，目前都是478错误

**Comment by aofei** [comment]
@cragsxie 

这个错误代码 478 我们排查了一下，结论是对象存储的回源链路出了些问题，不过现在七牛那边儿已经让运维调整好了，我这会儿看日志反映上 478 出现得已经很少很少了，所以今天的这个故障基本算是解决了。此外我们还在继续排查看有没有其他的问题，因为 goproxy.cn 的访问量每天都在增加，所以无论如何我们都会继续优化下去的，这个老哥们可以放心，会让大家继续愉快地搬砖的～😁

另外这个 Issue 就先不要关闭了，我再多观察一天，明天如果没出现什么问题的话再关闭，谢谢老哥们啦！😊

有问题的话欢迎随时反馈！会尽快回答的～💪

**Comment by aofei** [comment]
刚看了一下日志，近一百万条请求里面除了 404 这类健康的错误（在 Go module proxy 的设计中 404 是被认为健康的错误）之外没有出现过一条其他的属服务端的错误响应，所以这个 Issue 我就关闭啦哈，如果之后再遇到的话可以随时再开启或者发新的 Issue。

再次感谢各位老哥的反馈！😊
