### ISSUE TITLE
can not get latest client-go

### ISSUE THREAD

**Issue by ponypaver** [goproxy/goproxy.cn#44]
```
go get -u k8s.io/client-go@v12.0.0
go: finding k8s.io/client-go v12.0.0
go: finding k8s.io v12.0.0
go get k8s.io/client-go@v12.0.0: unexpected status (https://goproxy.cn/k8s.io/client-go/@v/v12.0.0.info): 404 Not Found
```

**Comment by aofei** [comment]
你好，404 的话再 Go 模块代理里面是被归类为健康状态码的。

目前有几种情况可能会导致 404：

* 目标模块版本的确不存在
* 目标模块版本刚发布，Go 模块代理的缓存还没有到期（通常是几分钟就好了）
* 目标模块版本存在错误（比如版本号非法）
* 目标模块版本的 `go.mod` 文件中规定的模块路径和请求中解析到的不符（多是因为模块版本的使用者用错）

还有很多种其他情况，但大多都是这四种。

目前你的这个错误原因是：

```
invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v12
```

意思是你的项目的 `go.mod` 文件中对应的模块路径 `k8s.io/client-go` 是错误的，因为那个模块版本中的 `go.mod` 文件规定的是 `k8s.io/client-go/v12`，你只需要改一下你的 `go.mod` 文件和对应代码中的导入路径就好了。😊

**Comment by ponypaver** [comment]
不好意思哈， 我还是没明白这是什么问题，可能我提供的信息不足
```
➜  test git:(master) go get k8s.io/client-go@v12.0.0
go: finding k8s.io/client-go v12.0.0
go: finding k8s.io v12.0.0
go get k8s.io/client-go@v12.0.0: unexpected status (https://goproxy.cn/k8s.io/client-go/@v/v12.0.0.info): 404 Not Found
➜  test git:(master) go get k8s.io/client-go@v12
go get k8s.io/client-go@v12: no matching versions for query "v12"
➜  test git:(master) grep client-go go.mod
	k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
➜  test git:(master)
```

**Comment by aofei** [comment]
这个模块存在一些问题，你可以看一下这个：https://github.com/kubernetes/client-go/issues/670#issue-490014093

**Comment by ponypaver** [comment]
我本地的 go 版本是 1.12，如果我不使用 goproxy.cn，直接开代理去 go get 是成功的
```
➜  test git:(master) go version
go version go1.12.10 darwin/amd64
➜  test http_proxy=socks5://127.0.0.1:1086 go get -u k8s.io/client-go@v12.0.0
go: finding k8s.io/client-go v12.0.0
go: finding golang.org/x/oauth2 latest
...
```

**Comment by aofei** [comment]
嗯嗯，是的了，Go 1.13 为了确保 Go moduels 的健康做出了很多新的限制，所以会比较严格，然后 goproxy.cn 的话必须一直用最新版本的 Go 才行，不只是保证大家的使用正常，还有一方面是 goproxy.cn 支持代理 Go 1.13 发布的 `GOSUMDB` 的默认值 sum.golang.org，所以在验证上必须保持一致才行，否则就会出现 goproxy.cn 放过但 sum.golang.org 却没过的情况发生。

**Comment by ponypaver** [comment]
了解了， 多谢

**Comment by aofei** [comment]
因为问题解决了所以我就关闭这个 Issue 啦哈，如果有其他问题老哥可以随时开新的 Issue～😊
