### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by Racaly** [goproxy/goproxy.cn#45]
golint:
Error: Command failed: /usr/local/bin/go get -v golang.org/x/lint/golint
go get golang.org/x/lint/golint: module golang.org/x/lint/golint: Get https://proxy.golang.org/golang.org/x/lint/golint/@v/list: dial tcp 172.217.24.17:443: i/o timeout
go get golang.org/x/lint/golint: module golang.org/x/lint/golint: Get https://proxy.golang.org/golang.org/x/lint/golint/@v/list: dial tcp 172.217.24.17:443: i/o timeout

**Comment by aofei** [comment]
这说明你并没有在用 Go modules 呢，所以自然也就谈不上在用 goproxy.cn 了。

你把你的 GO111MODULE 设置为 on 再试一次？

**Comment by aofei** [comment]
哦，不好意思，刚才眼花看错了，你现在是在使用 Go modules 没错，只是没有在使用 goproxy.cn 而是使用的 GOPROXY 的默认值 proxy.golang.org 罢了。

所以你现在要做的是修改你的 GOPROXY 环境变量，将它修改成 `GOPROXY=https://goproxy.cn,direct`（如果你的 Go 版本 >= 1.13）或者 `GOPROXY=https://goproxy.cn`（如果你的 Go 版本 < 1.13）。

**Comment by Racaly** [comment]
没有的哦，go env 输出的GOPROXY就是https://goproxy.cn。但是你这个错误是我在vscode里得到的。我尝试在终端go get的时候是正常了（不是环境变量的问题哦，已经重启过很多次）。然后我刚才在终端 install 以后 都已经正常了，vscode也可以了，真的是很奇怪，😂

**Comment by renzheng0403** [comment]
![image](https://user-images.githubusercontent.com/20588534/100182305-4139ea80-2f17-11eb-82ea-2c86350ed44e.png)
遇到了同样的问题，在终端用的就是代理，在ide里用的就是默认访问不到的地址，应该是ide有个设置GOPROXY的地方吧
