### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by iKuiki** [goproxy/goproxy.cn#46]
verifying github.com/kataras/iris/v12@v12.0.1/go.mod: checksum mismatch
downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
go.sum: h1:udK4vLQKkdDqMGJJVd/msuMtN6hpYJhg/lSzuxjhO+U=

since 2019-11-18 22:33:18

**Comment by cfeeling** [comment]
I also met this problem in our project with `GOPROXY="goproxy.cn,direct"`.

Could anyone help me to resolve this issue under this damn network? Thanks.

**Comment by aofei** [comment]
goproxy.cn 这个项目主要针对咱们国内开发者，所以老哥们用中文交流就好啦～😊

另外，我正在检查这个模块版本，得出结论后反馈到这，稍等。

**Comment by hhtest1** [comment]
同样遇到这个问题，改成goproxy.io才可以正常编译

**Comment by aofei** [comment]
你好，我在一个干净的环境中试了一下，是可以通过的，有试过先 `go clean -modcache` 然后再获取嘛？

**Comment by cfeeling** [comment]
在第一次遇到该问题的时候，第一反应就是 go clean -modcache，但是无效。

不过刚才重新 clean 以后测试，没问题了。

**Comment by aofei** [comment]
@cfeeling 麻烦老哥回忆一下，出这个问题前获取模块版本的方式是走的代理还是走的直连？方便我排查是不是代理这边的问题😊

**Comment by hhtest1** [comment]
好吧，现在可以了，之前再怎么go clean -modcache都没用，之前用的 GOPROXY="goproxy.cn,direct"

**Comment by aofei** [comment]
似乎这个包被重新打包过，我再确认。

是这样的，稍微解释一下，由于 Go checksum database 在设计上有不可撤销这么一个设定，所以如果一个模块已经发布了，然后被 GOSUMDB 的默认值 sum.golang.org 缓存住了，那么作者再重新打包并重新发布某个 tag 的时候就可能会导致这种问题出现。因为重新打包的结果的哈希值变了，所以校验失败。

**Comment by aofei** [comment]
再问一下，大家都是在用 github.com/kataras/iris/v12@v12.0.1 这个模块版本的时候遇到的这个问题嘛？

**Comment by hhtest1** [comment]
> 再问一下，大家都是在用 github.com/kataras/iris/v12@v12.0.1 这个模块版本的时候遇到的这个问题嘛？

是的

**Comment by iKuiki** [comment]
> 再问一下，大家都是在用 github.com/kataras/iris/v12@v12.0.1 这个模块版本的时候遇到的这个问题嘛？

是的
是昨晚（11月18）10点多开始，构建服务器就因为这个错无法编译，构建用的基础镜像是go1.13.3，然后把代码丢进去build过一遍带上依赖的，构建过程把code重新丢进这个基础镜像编译

我试过删除gopath/pkg目录问题依旧，暂时切换到goproxy. io后问题修复

**Comment by aofei** [comment]
goproxy.cn 缓存这个模块版本的时间是 `2019-10-26T17:43:18Z`，一经缓存就不会再修改了。然后大家执行 go 命令获取此模块版本时会首先把 https://goproxy.cn/github.com/kataras/iris/v12/@v/v12.0.1.mod 这个文件下载到本地（因为稍后要用它来推算间接依赖），接着使用大家的 GOSUMDB 的配置来校验刚下载的那个文件的哈希值是否匹配，具体校验用到了 https://goproxy.cn/sumdb/sum.golang.org/lookup/github.com/kataras/iris/v12@v12.0.1 这个文件（如果你是使用 goproxy.cn 来代理，并且你的 GOSUMDB 是 sum.golang.org 时），不匹配就报 `verifying github.com/kataras/iris/v12@v12.0.1/go.mod: checksum mismatch` 的错误。这就是大体的校验过程。

可是现在奇怪的是，我想不明白为什么大家的校验会失败，因为 goproxy.cn、proxy.golang.org 以及 goproxy.io 返回得是完全一致的文件，也就是本来就必须一致的文件。事实上这个本就不应该在代理之间存在差异才是。

大家可以在控制台尝试如下命令：

```bash
$ curl -s https://goproxy.cn/github.com/kataras/iris/v12/@v/v12.0.1.mod | sha256sum
bf41b26909c613afdee7a01083528bd66a82bbef8527df1fd93bfbf486c08fc9  -
```

```bash
$ curl -s https://proxy.golang.org/github.com/kataras/iris/v12/@v/v12.0.1.mod | sha256sum
bf41b26909c613afdee7a01083528bd66a82bbef8527df1fd93bfbf486c08fc9  -
```

```bash
$ curl -s https://goproxy.io/github.com/kataras/iris/v12/@v/v12.0.1.mod | sha256sum
bf41b26909c613afdee7a01083528bd66a82bbef8527df1fd93bfbf486c08fc9  -
```

同理把上面三条命令的 URL 的后缀从 `.mod` 换成 `.zip` 来比对大家会发现也是完全一致的。

就像前面 @hhtest1 和 @cfeeling 两位老哥说的那样儿，@iKuiki 你也可以现在再 `go clean -modcache` 一次试试看能否成功，因为他俩都能成功了。其实理应是可以的了，因为我换了多个环境来用 goproxy.cn 获取并校验这个模块版本，都没有出过错。

因为事情比较诡异，而且就这一个模块版本有这个问题，所以我就先保持这个 Issue 开启两天，看有没有其他人在用别的模块时也遇到了这个错误，如果有的话咱们再想别的办法调查一下。

总之无论如何，我稍后把这个模块版本的 CDN 缓存刷新一下，虽然完全无关，但总有那么一种感觉比如网络问题导致数据传输不完整什么的，希望能有所帮助吧（寄期望于玄学的我）…… 😩

**Comment by iKuiki** [comment]
> goproxy.cn 缓存这个模块版本的时间是 `2019-10-26T17:43:18Z`，一经缓存就不会再修改了。然后大家执行 go 命令获取此模块版本时会首先把 https://goproxy.cn/github.com/kataras/iris/v12/@v/v12.0.1.mod 这个文件下载到本地（因为稍后要用它来推算间接依赖），接着使用大家的 GOSUMDB 的配置来校验刚下载的那个文件的哈希值是否匹配，具体校验用到了 https://goproxy.cn/sumdb/sum.golang.org/lookup/github.com/kataras/iris/v12@v12.0.1 这个文件（如果你是使用 goproxy.cn 来代理，并且你的 GOSUMDB 是 sum.golang.org 时），不匹配就报 `verifying github.com/kataras/iris/v12@v12.0.1/go.mod: checksum mismatch` 的错误。这就是大体的校验过程。
> 
> 可是现在奇怪的是，我想不明白为什么大家的校验会失败，因为 goproxy.cn、proxy.golang.org 以及 goproxy.io 返回得是完全一致的文件，也就是本来就必须一致的文件。事实上这个本就不应该在代理之间存在差异才是。
> 
> 大家可以在控制台尝试如下命令：
> 
> ```shell
> $ curl -s https://goproxy.cn/github.com/kataras/iris/v12/@v/v12.0.1.mod | sha256sum
> bf41b26909c613afdee7a01083528bd66a82bbef8527df1fd93bfbf486c08fc9  -
> ```
> 
> ```shell
> $ curl -s https://proxy.golang.org/github.com/kataras/iris/v12/@v/v12.0.1.mod | sha256sum
> bf41b26909c613afdee7a01083528bd66a82bbef8527df1fd93bfbf486c08fc9  -
> ```
> 
> ```shell
> $ curl -s https://goproxy.io/github.com/kataras/iris/v12/@v/v12.0.1.mod | sha256sum
> bf41b26909c613afdee7a01083528bd66a82bbef8527df1fd93bfbf486c08fc9  -
> ```
> 
> 同理把上面三条命令的 URL 的后缀从 `.mod` 换成 `.zip` 来比对大家会发现也是完全一致的。
> 
> 就像前面 @hhtest1 和 @cfeeling 两位老哥说的那样儿，@iKuiki 你也可以现在再 `go clean -modcache` 一次试试看能否成功，因为他俩都能成功了。其实理应是可以的了，因为我换了多个环境来用 goproxy.cn 获取并校验这个模块版本，都没有出过错。
> 
> 因为事情比较诡异，而且就这一个模块版本有这个问题，所以我就先保持这个 Issue 开启两天，看有没有其他人在用别的模块时也遇到了这个错误，如果有的话咱们再想别的办法调查一下。
> 
> 总之无论如何，我稍后把这个模块版本的 CDN 缓存刷新一下，虽然完全无关，但总有那么一种感觉比如网络问题导致数据传输不完整什么的，希望能有所帮助吧（寄期望于玄学的我）…… 😩

今天早上重新build好像mou得问题了，有点玄学
然后check项目的sum中```iris/v12 v12.0.1/go.mod h1:udK4vLQKkdDqMGJJVd/msuMtN6hpYJhg/lSzuxjhO+U=```没有修改过。。。觉得可能真的是之前从goproxy.cn拿的sum有问题喔，毕竟昨天我也从头build过的

**Comment by cfeeling** [comment]
> @cfeeling 麻烦老哥回忆一下，出这个问题前获取模块版本的方式是走的代理还是走的直连？方便我排查是不是代理这边的问题😊

在出现该问题前，获取模块版本的方式是走代理：`GOPROXY=goproxy.cn,direct`
直连和走代理都试过，都出现了这个问题。
直连时，分别尝试了通过SSR和直接连接；走代理时，使用的是 `GOPROXY=goproxy.cn,direct`。

**Comment by CodFrm** [comment]
在docker镜像构建时也出现了类似问题,使用io代理没有报错,使用cn代理报错了:

![image](https://user-images.githubusercontent.com/22783163/70585704-048abb80-1c00-11ea-98bc-1c13e83dec4b.png)
```
verifying gopkg.in/src-d/go-git.v4@v4.13.1/go.mod: checksum mismatch
	downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
	go.sum:     h1:nx5NYcxdKxq5fpltdHnPa2Exj4Sx0EclMWZQbYDu2z8=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
![image](https://user-images.githubusercontent.com/22783163/70585661-d4431d00-1bff-11ea-9630-d7db85625181.png)

**Comment by aofei** [comment]
`GO111MODULE=on GOPROXY=https://goproxy.cn,direct GOSUMDB=sum.golang.org go get gopkg.in/src-d/go-git.v4@v4.13.1`

这条命令么？奇怪了，我这里倒是没有报错……🤔

@CodFrm 老哥你可以帮我再测试一下嘛？先执行 `go clean -modcache` 然后再跑一次那条命令看看还会不会报这个错误。

**Comment by aofei** [comment]
@CodFrm 如果你能再顺便跑一下这条命令然后告诉我输出结果就更好了😊：

```bash
$ curl -s https://proxy.golang.org/gopkg.in/src-d/go-git.v4/@v/v4.13.1.mod | md5
```

**Comment by CodFrm** [comment]
@aofei 这是docker环境,应该不会有缓存的吧,在线上构建出现的

我在本地用的cn代理,没有出现这个问题，本地docker构建镜像使用cn代理没有出现

而且诡异的是今天放到线上构建才出现...前几天都没有问题的😥,确定包版本没有变化。都是golang1.13

本地docker构建：
![image](https://user-images.githubusercontent.com/22783163/70587035-d27b5880-1c03-11ea-935f-5640d0e034ef.png)

我这里没有md5，本地sha256如下：
![image](https://user-images.githubusercontent.com/22783163/70586719-d78bd800-1c02-11ea-9abd-8c7b4c4d924a.png)

在ci服务器运行结果如下：（ci服务器没代理，proxy.golang.org 跑不了）
![image](https://user-images.githubusercontent.com/22783163/70586901-67ca1d00-1c03-11ea-9473-6318daaa54d7.png)

**Comment by aofei** [comment]
我这里也是 `902f07204d7f775bb726c8d783f51300776e402649df9c180a015d5578839a9d`，奇怪了，那说明并没有任何问题，我看你前面贴的那个错误信息里提到的 `go.mod` 的校验和也跟我拿到的完全一致（`gopkg.in/src-d/go-git.v4 v4.13.1/go.mod h1:nx5NYcxdKxq5fpltdHnPa2Exj4Sx0EclMWZQbYDu2z8=`）：

>verifying gopkg.in/src-d/go-git.v4@v4.13.1/go.mod: checksum mismatch
>	downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
>	go.sum:     h1:nx5NYcxdKxq5fpltdHnPa2Exj4Sx0EclMWZQbYDu2z8=
>
>SECURITY ERROR
>This download does NOT match an earlier download recorded in go.sum.
>The bits may have been replaced on the origin server, or an attacker may
>have intercepted the download attempt.
>
>For more information, see 'go help module-auth'.

**Comment by CodFrm** [comment]
刚刚在dockerfile中加入了
```
RUN curl -s https://goproxy.cn/gopkg.in/src-d/go-git.v4/@v/v4.13.1.mod | sha256sum && \
    curl -s https://goproxy.io/gopkg.in/src-d/go-git.v4/@v/v4.13.1.mod | sha256sum
```

结果是一样的，但是`go mod tidy`时，io代理可以，cn代理不行，想不明白了
![image](https://user-images.githubusercontent.com/22783163/70591317-b205cb00-1c10-11ea-9b91-00e611dcbab1.png)

![image](https://user-images.githubusercontent.com/22783163/70591211-54717e80-1c10-11ea-95c5-d3755ad1572a.png)

**Comment by aofei** [comment]
@CodFrm 如果不用 go mod tidy 而是用 go mod download 呢？

**Comment by CodFrm** [comment]
一样的结果

![image](https://user-images.githubusercontent.com/22783163/70591938-debae200-1c12-11ea-9d2b-51f84bfe9913.png)

**Comment by aofei** [comment]
@CodFrm 你这是用的 go-micro 吧？方便告诉一下用的版本么？我确实很想知道为什么偏偏用 goproxy.cn 时会出错，就像咱俩刚确认的它们校验和都是一致的。

不过你刚才提到前几天你们那里没出过错，如果你们项目的 `go.sum` 几天内都没有发生过变化，那理应今天的构建结果也和几天前一致才对。

**Comment by CodFrm** [comment]
@aofei  go-micro是我们用的框架，版本v1.16.0

![image](https://user-images.githubusercontent.com/22783163/70592857-12e3d200-1c16-11ea-8edb-2dc5007f333c.png)

刚刚跑了一下昨天的ci任务，再次确认应该不是我操作的问题：
![image](https://user-images.githubusercontent.com/22783163/70593083-b9c86e00-1c16-11ea-8e5c-e6359767b4d5.png)

**Comment by aofei** [comment]
@CodFrm 我在不同的地方尝试从零获取它们都是 OK 的，然后我也和 proxy.golang.org 比对了所有相关文件的校验和，也是完全一致的……现在搞不懂问题出在哪里，首先因为你打印的那些校验和和我拿到的都是一致的，其次你用的这些也都是老版本，不是近期才发布的，我看那些相关文件也是很早就被 goproxy.cn 缓存了的，所以更不会存在篡改问题，最后你也提到了前几天都是成功的，所以双方都没有什么毛病。我现在能做出的最好的猜测就只有你哪里得到的 CDN 节点出现了什么奇怪的现象了，但是又不能肯定，毕竟 CDN 都是成熟的商业化了的，出这种篡改内容问题的可能性几乎为零。所以，如果方便的话麻烦你尝试一下刷新 CI 宿主机的 DNS 缓存，拿到一个不同的 CDN 节点后再试一次看看能不能行。

**Comment by CodFrm** [comment]
@aofei 

这是我在dockerfile中加入ping，两次结果都不同
![image](https://user-images.githubusercontent.com/22783163/70596821-c4d4cb80-1c21-11ea-83fb-65ddfe5f2824.png)

![image](https://user-images.githubusercontent.com/22783163/70596832-cacaac80-1c21-11ea-8285-2cfb3eea72c2.png)

-----
宿主ping的ip和dockerfile构建时的ip不同，宿主dns清理了
![image](https://user-images.githubusercontent.com/22783163/70597112-74aa3900-1c22-11ea-9271-4720e2631458.png)

**Comment by CodFrm** [comment]
@aofei 好像有点新进展了。。。

这是我在宿主直接跑docker
![image](https://user-images.githubusercontent.com/22783163/70597552-9a840d80-1c23-11ea-844d-d29933d5b939.png)

**Comment by CodFrm** [comment]
@aofei io的代理跑了一遍，成功 😥
![image](https://user-images.githubusercontent.com/22783163/70597925-99071500-1c24-11ea-99fc-4be34ef5c6fa.png)

**Comment by aofei** [comment]
@CodFrm  问题找到了，我强行改 `/etc/hosts` 让 goproxy.cn 走你截图里的那个节点 IP 183.6.231.9 也报错了，是 SUMDB 代理的锅（我们的 CDN 缓存时间过长导致的 SUMDB 时序不一致，如果你强行用比如我这里拿到的节点 IP 47.246.5.219 就不会有这个问题，因为没缓存过），这是我们的 Bug，实在是不好意思了，我现在正在着手解决中。

临时的解决方案是暂时关闭 SUMDB，方法是：`export GOSUMDB=off`。或者等我修复完也可以，预计半小时内修复这个 Bug。

**Comment by CodFrm** [comment]
嗯，强改`/etc/hosts`可以了，等大佬更新完我再试试

**Comment by aofei** [comment]
@CodFrm 这个 Bug 我已经修复了，并且全网 CDN 刷新已生效，你那边儿现在应该就是可以了的，麻烦老哥你再确认一次。

**Comment by CodFrm** [comment]
@aofei 没有哦

![image](https://user-images.githubusercontent.com/22783163/70601115-55180e00-1c2c-11ea-8be9-4ac71f6da49c.png)

![image](https://user-images.githubusercontent.com/22783163/70601099-4cbfd300-1c2c-11ea-9d63-374e79fb2535.png)

**Comment by aofei** [comment]
@CodFrm 那就先续上几分钟再试试看吧，可能你那里的 CDN 缓存还没被刷新到😂

**Comment by CodFrm** [comment]
@aofei 一小时了 😂

```
/go/test # GO111MODULE=on GOPROXY=https://goproxy.cn,direct GOSUMDB=sum.golang.org go get gopkg.in/src-d/go-git.v4@v4.13.1
go: finding gopkg.in v4.13.1
go: finding gopkg.in/src-d/go-git.v4 v4.13.1
go: downloading gopkg.in/src-d/go-git.v4 v4.13.1
go: extracting gopkg.in/src-d/go-git.v4 v4.13.1
verifying gopkg.in/src-d/go-git.v4@v4.13.1/go.mod: checksum mismatch
	downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
	sum.golang.org: h1:nx5NYcxdKxq5fpltdHnPa2Exj4Sx0EclMWZQbYDu2z8=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
/go/test # ping goproxy.cn
PING goproxy.cn (124.236.20.140): 56 data bytes
64 bytes from 124.236.20.140: seq=0 ttl=38 time=39.074 ms
64 bytes from 124.236.20.140: seq=1 ttl=38 time=39.121 ms
64 bytes from 124.236.20.140: seq=2 ttl=38 time=39.113 ms
^C
--- goproxy.cn ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 39.074/39.102/39.121 ms
/go/test # 

```

**Comment by CodFrm** [comment]
不过应该是cdn缓存的原因

机器是阿里云杭州的

强改我公司ping到的ip是没有错误了

**Comment by aofei** [comment]
@CodFrm 你改一下 GOSUMDB 环境变量试试：

```bash
$ export GOSUMDB=sum.golang.google.cn
```

如果没有报错的话就能说明之前的问题是 CDN 缓存导致的了。

**Comment by CodFrm** [comment]
报错了。。。
![image](https://user-images.githubusercontent.com/22783163/70605628-d45e0f80-1c35-11ea-9d4c-3a0e6358040d.png)

![image](https://user-images.githubusercontent.com/22783163/70605680-e8097600-1c35-11ea-87ff-8105c4c300dd.png)

**Comment by aofei** [comment]
@CodFrm 不能那样操作，把上一条命令删除了，因为上一条执行完本地就有缓存了，执行下一条的时候就不会再去抓取了。

**Comment by CodFrm** [comment]
我又重新启动了docker容器，依旧报错

![image](https://user-images.githubusercontent.com/22783163/70605977-7bdb4200-1c36-11ea-9026-3b8d70c8b177.png)

**Comment by aofei** [comment]
@CodFrm 但是我这里强行改 `/etc/hosts` 指定 goproxy.cn 走你截图里的这个 CDN 节点 IP 219.147.157.99 并没有报错了啊？🤔

**Comment by CodFrm** [comment]
@aofei  现在可以了,感谢

**Comment by aofei** [comment]
> @aofei 现在可以了,感谢

😂估计刚才是全网 CDN 缓存刷新没有生效吧……这生效速度也是够慢的……
