### ISSUE TITLE
Bug: 刚更新的代码,goproxy.cn无法感知,更换goproxy.io可以

### ISSUE THREAD

**Issue by yjbdsky** [goproxy/goproxy.cn#48]
在github.com上的项目,我更新了一波代码,,,另一个项目依赖他,,go get -u 死活都是更之前的老代码,,
换了goproxy.io就好了,,,被坑了3小时

**Comment by yjbdsky** [comment]
重新更新后,,发现goproxy.io也一样,,,估计都是有缓存

**Comment by aofei** [comment]
缓存理论一到两分钟，偶尔也会出现延迟过久一些的情况发生比如将近十分钟什么的（虽然想不到什么会导致这种情况），但绝对不会上小时级别，老哥有可能操作失误了呢。

另外新版本发布后可以参考我在 FAQ 中提到的方式来立即（无任何延迟地）拿到你想要的那个版本：具体老哥你可以看[这里](https://github.com/goproxy/goproxy.cn/blob/master/README.zh-CN.md#我对一个库提交了新的修改为什么在我运行-go-get--u-或-go-list--m--versions-时它却没有出现)。

**Comment by xuwuruoshui** [comment]
我被坑惨了，我一直以为电脑缓存

**Comment by yjbdsky** [comment]
自己的项目的话，，我现在都直接用replace了
