### ISSUE TITLE
问题：使用goproxy引用包404

### ISSUE THREAD

**Issue by zouyx** [goproxy/goproxy.cn#49]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

## 你做了什么？

是否能帮忙看看这是什么问题？(使用goproxy引用包404)[https://github.com/zouyx/agollo/issues/84]

我访问的goproxy.cn的ip是:47.246.16.225。我是没问题的，这个issue里的兄弟是不行的

```
>ping goproxy.cn

正在 Ping qiniuopencdn.jomodns.com [47.246.16.225] 具有 32 字节的数据:
来自 47.246.16.225 的回复: 字节=32 时间=20ms TTL=111
来自 47.246.16.225 的回复: 字节=32 时间=12ms TTL=111
```

**Comment by aofei** [comment]
已在 https://github.com/zouyx/agollo/issues/84#issuecomment-562423993 回复，所以这个 Issue 我就关闭啦哈。😊
