### ISSUE TITLE
Bug: 无法找到包 gopkg.in/asn1-ber.v1

### ISSUE THREAD

**Issue by arrow2012** [goproxy/goproxy.cn#50]
go get gopkg.in/asn1-ber.v1
go get gopkg.in/asn1-ber.v1: module gopkg.in/asn1-ber.v1: reading https://goproxy.cn/gopkg.in/asn1-ber.v1/@v/list: 404 Not Found

**Comment by aofei** [comment]
这个跟 Go 模块代理无关，在 Go 模块代理中 404 被认为是健康的状态，因为 Go 模块需要依靠 404 来实现很多功能（比如模块路径的推算等）。

目前为止，世界上所有代理只有 [goproxy.cn](https://goproxy.cn) 和 [proxy.golang.org](https://proxy.golang.org) 支持直接打开那条 404 的 URL 并得到详细错误信息：

https://goproxy.cn/gopkg.in/asn1-ber.v1/@v/list

```
Not Found: gopkg.in/asn1-ber.v1@v1.3.1: invalid version: go.mod has non-....v1 module path "github.com/go-asn1-ber/asn1-ber" at revision v1.3.1
```

**Comment by aofei** [comment]
404 基本全都是自己使用失误或者模块作者操作失误，偶尔也会有为了防止缓存击穿而做的一分钟cdn延迟导致的 404，不过这个情况还是蛮少的。

目前来说你遇到的这个错误是由于你的错误使用导致的，你获取的那个目标模块已经存在了 `go.mod` 文件，且其作者要求的模块路径是 `github.com/go-asn1-ber/asn1-ber`（详见：[这里](https://github.com/go-asn1-ber/asn1-ber/blob/master/go.mod#L1)），而你用的是 `gopkg.in/asn1-ber.v1`，属于用错了。

**Comment by aofei** [comment]
鉴于这并不是一个 Bug，所以我就关闭这个 Issue 了哈。

老哥如果还有别的问题欢迎随时提问～😊
