### ISSUE TITLE
Go 模块：很多依赖包都没有

### ISSUE THREAD

**Issue by Justin-Zhuang** [goproxy/goproxy.cn#53]
所依赖的包很多都没有，导致经常出现404。出现404只能更换代理地址

**Comment by aofei** [comment]
这个跟 Go 模块代理无关，在 Go 模块代理中 404 被认为是健康的状态，因为 Go 模块需要依靠 404 来实现很多功能（比如模块路径的推算等）。404 基本全都是自己使用失误或者模块作者操作失误，偶尔也会有为了防止缓存击穿而做的一分钟 CDN 延迟导致的 404，不过这个情况还是蛮少的。

目前为止，世界上所有代理只有 [goproxy.cn](https://goproxy.cn) 和 [proxy.golang.org](https://proxy.golang.org) 支持直接打开那条 404 的 URL 并得到详细错误信息，所以你可以直接打开那条 404 的 URL 就能知道自己用错在哪里了。😊

**Comment by aofei** [comment]
另外，[goproxy.cn](https://goproxy.cn) 目前缓存的模块版本数量是所有已知 Go 模块代理中最多的哦～将近多出 [proxy.golang.org](https://proxy.golang.org) 一半呢。而且是实时回源的，就算我们没有缓存某个模块版本，只要那个目标模块版本是存在且合法的，那么你是得不到 404 的，[goproxy.cn](https://goproxy.cn) 会自动帮你透明拉取缓存起来并正常响应给你。

**Comment by aofei** [comment]
由于这是老哥你自己用错了或者你的目标模块作者写错了，所以你应该做的是直接打开那些 404 的 URL 来查看具体错误信息。鉴于老哥你长时间没有回复，我就当成你那边儿问题已解决，这个 Issue 我就先关闭了哈，如果还有其他问题欢迎随时提问。😊

另外切记一点，别拿阿里云的 Go 模块代理跟 goproxy.cn 和 proxy.golang.org 做比较，阿里云的 Go 模块代理是所有代理中做得最不合规矩的，存在很多缺陷，尤其是它正在使用低版本的 Go 这一点导致了某些情况下它会放过本应该 404 的请求，我通过朋友跟他们反馈过这一点，但他们却一直没有做任何改进，故而***强烈不建议使用阿里云的 Go 模块代理***。
