### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by SsrCoder** [goproxy/goproxy.cn#55]
go get github.com/kataras/iris: module github.com/kataras/iris: reading http://goproxy.cn/github.com/kataras/iris/@v/list: 502 Bad Gateway

**Comment by aofei** [comment]
谢谢反馈！我们已经在处理这次的事故了，初步判定为 CDN 服务那边出现了问题，后台服务均是正常的，云服务商那边儿的运维现在已经在排查中了，进度可在我们的状态页查看到（[status.goproxy.cn](https://goproxy.cn)）。

造成了不便，实在是抱歉！🙏

**Comment by SsrCoder** [comment]
辛苦大佬，元旦快乐

**Comment by aofei** [comment]
你也是，元旦快乐！😊

问题初步得到解决，现在服务已经恢复正常了，我们正在进一步调查以改善服务稳定性。这次的事故实在是抱歉！🙏

**Comment by sendya** [comment]
大佬元旦快乐

**Comment by aofei** [comment]
@sendya 老哥你也是，元旦快乐！🎉

不过你们都不用跨年的嘛？莫非还在写代码？🤯

**Comment by sendya** [comment]
@aofei 
![image](https://user-images.githubusercontent.com/5404542/71627619-6f8f4700-2c2e-11ea-855c-f0c9f324b3fa.png)

CI 炸红了一片 :laughing:

**Comment by aofei** [comment]
@sendya 自责……😢

这次事故是由于我们的网络出现了问题导致的，不知具体是什么原因致使 CDN 无法正常回源到后台服务器，七牛那边儿临时调整了回源线路才使得服务得以恢复正常，现在他们正在排查专线具体是出现了问题。

哎……没想到稳定运行了那么久却在年末出现了事故……实在是不好意思！我们会从这次事故中学习，以后会更稳定的！💪

**Comment by sendya** [comment]
@aofei 哈 没事没事，大佬弄这个已经很方便国内的 go 用户了

**Comment by motoude** [comment]
hello,
unrecognized import path "golang.org/x/tour"  after go get golang.org/x/tour.
I have go env -w GOPROXY=https://goproxy.cn,direct

**Comment by aofei** [comment]
@motoude 你好，你这个错误说明你并没有在使用 Go modules，所以也就谈不上在用 goproxy.cn 了，请你检查一下你的 GO111MODULE 环境变量是否为 on。

**Comment by motoude** [comment]
@aofei 好的，谢谢，初学者，我以为直接就能用的，看的文章和你们的文档都是直接用。谢谢大佬。

**Comment by snowlyg** [comment]
@aofei 
![image](https://user-images.githubusercontent.com/45998760/75638385-9ab20900-5c66-11ea-8a9f-9d3bdeda6665.png)
我这个是不是一个类似问题？
