### ISSUE TITLE
问题：关于包安装失败的问题

### ISSUE THREAD

**Issue by ohohok** [goproxy/goproxy.cn#56]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要咨询的问题吗？

确定，我看过常见问题了

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.13 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/ubuntu/GoProjects/bin"
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/GoProjects"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/home/ubuntu/sdk/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ubuntu/sdk/go1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build711429640=/tmp/go-build -gno-record-gcc-switches"

</pre>
</details>

## 你做了什么？

govendor sync -v

## 你期望看到的结果是什么？

安装依赖文件中我想要的包

## 你实际看到的结果是什么？

fetch "golang.org/x/sys/unix"
Error: Remotes failed for:
        Failed for "golang.org/x/sys/unix" (failed to ping remote repo): unrecognized import path "golang.org/x/sys/unix"

**Comment by aofei** [comment]
你好，goproxy.cn 是给 Go modules 特新用的，无法支持 dep 还有 govendor 等其他依赖管理解决方案，所以在你切换到 Go modules 之前是无法使用的。😊

**Comment by aofei** [comment]
由于问题已解决，所以我就关闭这个 Issue 了哈，如果你还有别的关于 Go modules 的问题想问，欢迎随时创建新的 Issue，我会尽快回复的。
