### ISSUE TITLE
问题：执行 go install 时出现了 malformed HTTP response

### ISSUE THREAD

**Issue by WatchLucky** [goproxy/goproxy.cn#58]
go version ： 1.13.6
 
go env ： 
HOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxxxx/Documents/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
 
报错步骤：

shift+command+P 
   输入 go install tools 
   选择godef 

报错：
 
 
gocode:
Error: Command failed: /usr/local/go/bin/go get -v github.com/mdempsky/gocode
go get github.com/mdempsky/gocode: module github.com/mdempsky/gocode: Get https://goproxy.cn/github.com/mdempsky/gocode/@v/list: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"

**Comment by aofei** [comment]
你好，你的环境变量配置应该是没有问题的，造成这个错误的原因是你拿到了一个不正常的响应结果，正常的应该是个空响应主体，因为目标模块不包含任何已知版本。

在我这里请求 https://goproxy.cn/github.com/mdempsky/gocode/@v/list 是按照预期响应的（即空响应主体），因此我不太确定是你那边儿网络的问题还是我们服务器的问题，所以麻烦你再试一次或者在终端试一下能不能拿到正常的响应：

```bash
$ curl -i https://goproxy.cn/github.com/mdempsky/gocode/@v/list
```

另外，如果可以的话麻烦告知一下你上面那条错误请求发生的大体时间区间，我好过滤日志。

**Comment by aofei** [comment]
由于长时间没有回复，我就先关闭这个 Issue 了哈，如果老哥你还有别的问题欢迎随时提问，我还是会尽快回答的～😊

**Comment by nishaoshan** [comment]
我也出现了这种情况

**Comment by nishaoshan** [comment]
Tools environment: GOPATH=/root/go
Installing 1 tool at /root/go/bin in module mode.
  dlv

Installing github.com/go-delve/delve/cmd/dlv@latest FAILED
{
 "killed": false,
 "code": 1,
 "signal": null,
 "cmd": "/usr/local/sbin/go install -v github.com/go-delve/delve/cmd/dlv@latest",
 "stdout": "",
 "stderr": "go: github.com/go-delve/delve/cmd/dlv@latest: module github.com/go-delve/delve/cmd/dlv: Get \"https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/list\": malformed HTTP response \"\\x00\\x00\\x12\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x03\\x00\\x00\\x00\\x80\\x00\\x04\\x00\\x01\\x00\\x00\\x00\\x05\\x00\\xff\\xff\\xff\\x00\\x00\\x04\\b\\x00\\x00\\x00\\x00\\x00\\u007f\\xff\\x00\\x00\\x00\\x00\\b\\a\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\"\n"
}

1 tools failed to install.

dlv: failed to install dlv(github.com/go-delve/delve/cmd/dlv@latest): Error: Command failed: /usr/local/sbin/go install -v github.com/go-delve/delve/cmd/dlv@latest
go: github.com/go-delve/delve/cmd/dlv@latest: module github.com/go-delve/delve/cmd/dlv: Get "https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/list": malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"

**Comment by aofei** [comment]
@nishaoshan 请问你在控制台手动执行 `go install -v github.com/go-delve/delve/cmd/dlv@latest` 时会出错吗？如果出错的话麻烦提供一下它的详细输出内容。可以的话顺便也提供一下 `curl -iv https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@latest` 和 `curl -iv https://goproxy.cn/github.com/go-delve/delve/cmd/dlv/@v/list` 的输出内容。

**Comment by nishaoshan** [comment]
您好！您的邮件我已查收！谢谢！
