### ISSUE TITLE
问题：Go get 失败

### ISSUE THREAD

**Issue by pmxEr5lZwZ** [goproxy/goproxy.cn#62]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.13.5 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\User\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build660287998=/tmp/go-build
 -gno-record-gcc-switches

</pre>
</details>

## 你做了什么？

我想下载godoc
go get golang.org/x/tools/cmd/godoc

## 你实际看到的结果是什么？

package golang.org/x/tools/cmd/godoc: unrecognized import path "golang.org/x/tools/cmd/godoc" (https fetch: Get https://golang.org/x/tools/cmd/godoc?go-get=1: dial tcp 216.23
9.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because conne
cted host has failed to respond.)

**Comment by aofei** [comment]
你好，这个错误表示你此时并没有在用 Go modules 呢，所以自然也就谈不上在用 Go module proxy 了。你把 GO111MODULE 环境变量设置为 on 就好了。😊

**Comment by cpu100** [comment]
checksum missmatch

**Comment by snowlyg** [comment]
@aofei 
![image](https://user-images.githubusercontent.com/45998760/75638225-def0d980-5c65-11ea-9cd7-7b68ce9c93f1.png)
执行 go mod tidy 失败，这个是什么问题？

**Comment by aofei** [comment]
@snowlyg 你好，我们的 CDN 昨天配置完后还残留一些小问题，目前正在排查解决中，可能会不稳定导致偶尔有 504 产生，临时的解决方案是重试两三次那条错误的命令。如果老哥感兴趣可在 [status.goproxy.cn](https://status.goproxy.cn) 追踪到实时状态。

此外，通过配图我了解到老哥你的配置存在些许问题，建议把 `GOPROXY` 配置成 `https://goproxy.cn,direct`，因为没有“direct”的话会导致很多功能不可用的，比如 `GOPRIVATE` 之类的没有“direct”的话就无法正常工作。

**Comment by aofei** [comment]
@cpu100 你好，Go modules 现在设计上还存在少许缺陷，偶尔可能会发生 checksum mismatch 的情况，这种情况下建议先删除项目的 `go.sum` 文件，然后再执行 `go clean -modcache` 命令，接着再执行 `go mod tidy` 命令重新生成 `go.sum`文件，应该就能解决了。如果还是存在问题，麻烦老哥你重新开个 Issue 详细描述一下具体的错误信息，比如贴出错误内容什么的，那样可以方便我们排查。

这个 Issue 作者原本的问题应该已经解决了，所以我就暂时关闭了，在一个 Issue 下解决多个不同的问题不太好。😊

**Comment by snowlyg** [comment]
@aofei 谢谢回复 。有 ,direct 和没 ,direct 都有尝试。因为以前用这个代理都很正常，所以不太清楚是不是代理了的问题。不过后面用阿里的代理能正常工作。

**Comment by aofei** [comment]
@snowlyg 

[goproxy.cn](https://goproxy.cn) 现在已经恢复啦，可以继续使用了，具体原因我分享在 https://github.com/goproxy/goproxy.cn/issues/66#issuecomment-593275267 这个回复里来。谢谢支持与反馈！😄
