### ISSUE TITLE
问题：小白想问，ubuntu怎么取消Goproxy代理，命令是什么呢谢谢！纯小白

### ISSUE THREAD

**Issue by byalan** [goproxy/goproxy.cn#63]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>

**Comment by aofei** [comment]
将 GOPROXY 改成 direct 就好啦，方法是：

export GOPROXY=direct

或

go env -w GOPROXY=direct

**Comment by byalan** [comment]
谢谢

**Comment by aofei** [comment]
鉴于问题已解决我就先关闭这个 Issue 了哈，如过还有其他问题欢迎随时提问。
