### ISSUE TITLE
Bug: 500 Internal Server Error

### ISSUE THREAD

**Issue by CatchZeng** [goproxy/goproxy.cn#64]
https://goproxy.cn/github.com/timest/env/@v/v0.0.0-20180717050204-5fce78d35255.mod

**Comment by aofei** [comment]
你好，我们正乘着周末改善一下服务，刚才 CDN 配置错了东西导致回源出现了异常，现在已重新配置，应该很快就能生效，具体可在 [status.goproxy.cn](https://status.goproxy.cn) 跟踪到。 造成了麻烦，实在抱歉！😥

**Comment by CatchZeng** [comment]
好的，感谢！



---Original---

**Comment by aofei** [comment]
现已恢复，经监控显示 500 已不再出现。

我会再跟踪一段时间以确保一切正常，谢谢反馈！😊
