### ISSUE TITLE
问题：502 bad gateway

### ISSUE THREAD

**Issue by halfcrazy** [goproxy/goproxy.cn#67]
verifying cloud.google.com/go@v0.38.0/go.mod: cloud.google.com/go@v0.38.0/go.mod: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/cloud.google.com/go@v0.38.0: 502 Bad Gateway
![image](https://user-images.githubusercontent.com/4113173/75675744-b2b77600-5cc2-11ea-8b39-a96d1bef7fd8.png)

**Comment by aofei** [comment]
你好，抱歉晚回复了一会儿。

是这样的，我来解释一下吧。导致 502 的因素有很多，尤其是像我们这种上了 CDN 的源站在海外的服务。我们的 CDN 在回源出海时走的是 HTTP 明文，可能会因为众所周知的问题出现网络不稳定甚至被劫持的情况，这还是在 [goproxy.cn](https://goproxy.cn) 配备了出海专线的情况下，如果没有配备出海专线那会更夸张。老哥你一创建这个 Issue 我们就开始调查了，结果显示你的这条请求就属于在回源出海的时候被劫持了……

实际上我们这两天就正是在想办法解决这一类问题，我在 https://github.com/goproxy/goproxy.cn/issues/66#issuecomment-593275267 也有提到。我们每天产生的 502 其实很少，能遇到的都说明运气不一般。刚开始我们并没有怀疑到回源劫持这一点，因为我们以为走专线这种情况会很少见，但通过老哥你的这次反馈我们经调查就发现我们想错了，确实是回源劫持导致的这间断性的不稳定现象。我们本来的解决思路是在 CDN 端增加容错机制，通过重试来消化掉这些 502，让客户端感觉不到，但产生了今早的 504 激增现象。现在有了新的解决思路，目前已经配置了一部分，监控显示很稳定，所以更加证实了回源劫持的观点。由于晚上不太敢动专线，因为专线并不是给这一个服务用的，所以明早再着手配置专线，理想状态配置完后能根除这个回源劫持导致的问题。

感谢老哥的反馈！这次帮助真的很大～😊

**Comment by halfcrazy** [comment]
谢谢这么详细的调查。这个问题确实是今天下午突然出现，在我们的构建服务器上持续了很长一段时间，本地则没有问题。半个小时前？我们的构建服务器也恢复了。

goproxy.cn非常好用，祝项目越做越好。
