### ISSUE TITLE
问题：proxyconnect tcp: EOF

### ISSUE THREAD

**Issue by PearceDuan** [goproxy/goproxy.cn#68]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.13.4 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pearce/.cache/go-build"
GOENV="/home/pearce/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pearce/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pearce/Proj/iot-imei-finder/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build352571423=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

go get github.com/sirupsen/logrus

## 你期望看到的结果是什么？

可以顺利下载相关package
## 你实际看到的结果是什么？

go get github.com/sirupsen/logrus: module github.com/sirupsen/logrus: Get https://goproxy.cn/github.com/sirupsen/logrus/@v/list: proxyconnect tcp: EOF

**Comment by PearceDuan** [comment]
找到原因了， 因为本地设置了http_proxy导致的。
echo $http_proxy
echo $https_proxy

export http_proxy=
export https_proxy=

再尝试go get,可以了。

**Comment by blueveryday** [comment]
> 找到原因了， 因为本地设置了http_proxy导致的。
> echo $http_proxy
> echo $https_proxy
> 
> export http_proxy=
> export https_proxy=
> 
> 再尝试go get,可以了。

谢谢，我也遇到你同样的问题了。
虽然手动wget可以下载文件，但是编译的时候总是报错EOF
按照你的方法解决了，谢谢。

**Comment by aofei** [comment]
@blueveryday 

如果你感到好奇，https://github.com/goproxy/goproxy.cn/issues/71#issuecomment-599986830 这是 Go modules 在 HTTP(S) Proxy 环境下的工作原理。

**Comment by blueveryday** [comment]
> @blueveryday
> 
> 如果你感到好奇，[#71 (comment)](https://github.com/goproxy/goproxy.cn/issues/71#issuecomment-599986830) 这是 Go modules 在 HTTP(S) Proxy 环境下的工作原理。

谢谢，学习了。
难怪之前开代理反而不行了。
