### ISSUE TITLE
Bug: download token auth failed

### ISSUE THREAD

**Issue by exherb** [goproxy/goproxy.cn#70]
## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.14 darwin/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Herb/Library/Caches/go-build"
GOENV="/Users/Herb/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GOOS="darwin"
GOPATH="/usr/local/lib/go/"
GOPRIVATE=""
GOPROXY="http://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9l/p9fgj70n2kg28w0f_4gt2cmr0000gn/T/go-build173442806=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## What did you do?

go build .

## What is the behavior of the bug?

`download token auth failed`

https://goproxy.cn/github.com/gammazero/deque/@v/v0.0.0-20200124200322-7e84b94275b8.zip

## Do you have any guesses?

no

**Comment by aofei** [comment]
抱歉！我刚才部署了服务更新，错误操作导致了这个问题……😭

现在已经修复了，感谢老哥及时反馈！❤️
