### ISSUE TITLE
问题：proxyconnect 不能正常工作

### ISSUE THREAD

**Issue by YvesZHI** [goproxy/goproxy.cn#71]
## 背景简介
我所用的计算机的操作系统为Ubuntu 16.04.3，该机器在公司内部，访问外网需要靠公司自己搭建的代理。即，在该系统中，我已经设置好三个环境变量：http_proxy，https_proxy和no_proxy，我确认公司的代理是可以正常访问外网的（如，我可以执行apt update、可以wget外网的html页面等）。

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

go version go1.14 linux/amd64
zyh@X86-Xenial-2:~/tmp$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zyh/.cache/go-build"
GOENV="/home/zyh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zyh/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build700388657=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？
go get -u github.com/gorilla/mux

## 你期望看到的结果是什么？

期望看到gorilla/mux成功安装

## 你实际看到的结果是什么？

go get github.com/gorilla/mux: module github.com/gorilla/mux: Get "https://goproxy.cn/github.com/gorilla/mux/@v/list": proxyconnect tcp: tls: first record does not look like a TLS handshake

**Comment by aofei** [comment]
你好，似乎是你的 `http_proxy` 和 `https_proxy` 配置存在问题，麻烦你确认一下相同环境下你执行下述命令的结果：

```bash
$ curl -i https://goproxy.cn/github.com/gorilla/mux/@v/list
```

**Comment by YvesZHI** [comment]
@aofei 

Here is the output:
```
HTTP/1.0 200 Connection established

HTTP/1.1 200 OK
Server: Tengine
Content-Type: text/plain; charset=utf-8
Content-Length: 83
Connection: keep-alive
Date: Tue, 17 Mar 2020 09:59:21 GMT
Cache-Control: public, max-age=300
X-M-Log: QNM:fs171;QNM3
X-M-Reqid: KGAAAG8YVd0FD_0V
X-Qnm-Cache: Hit
Ali-Swift-Global-Savetime: 1584439161
Via: cache7.l2cn1829[113,200-0,M], cache44.l2cn1829[115,0], kunlun9.cn190[0,200-0,H], kunlun8.cn190[2,0]
Age: 174
X-Cache: HIT TCP_HIT dirn:11:187770967
X-Swift-SaveTime: Tue, 17 Mar 2020 09:59:21 GMT
X-Swift-CacheTime: 300
Timing-Allow-Origin: *
EagleId: 3ad7912615844393354595802e

v1.2.0
v1.3.0
v1.4.0
v1.5.0
v1.6.0
v1.6.1
v1.6.2
v1.7.0
v1.7.1
v1.7.2
v1.7.3
```

**Comment by YvesZHI** [comment]
@aofei 

我的操作系统是Ubuntu 16.04.3，apt install只能安装go-1.9，所以我是源码安装的go-1.14.

安装过程：
```
wget https://dl.google.com/go/go1.14.linux-amd64.tar.gz
sudo tar -xvf go1.14.linux-amd64.tar.gz
sudo mv go /usr/local
```
然后配置了go的环境变量：export PATH=$PATH:/usr/local/go/bin/

**Comment by aofei** [comment]
首先，Go HTTP client 会用到你的 `https_proxy` 配置，然后你需要知道的是 Go HTTP client 默认会启用 TLS 证书检查，如果你们公司所配的这个 `https_proxy` 并不包含一个公认可靠的 TLS 证书，那么就会被阻止，比如 `https_proxy` 是 `https://192.168.0.1:1443` 这种时 Go HTTP client 就无法通过那行请求。或者，有些教程会导致大家误用 `https_proxy`，比如把它设置成了跟 `http_proxy` 完全一样的非 HTTPS 代理，即不包含任何 TLS 层，这样也是不行的。

要不你试试这样获取可行不：

```bash
$ go get -insecure github.com/gorilla/mux
```

如果还是不行，恐怕你只能在使用 Go 时关闭 `http_proxy` 和 `https_proxy` 了。

**Comment by aofei** [comment]
https://golang.org/pkg/net/http/#ProxyFromEnvironment

> ...
> HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.
> ...

或许你可以试试看只保留 `http_proxy`，把 `https_proxy` 置空。

**Comment by YvesZHI** [comment]
It works.

Thanks a lot :)

**Comment by blueveryday** [comment]
> 首先，Go HTTP client 会用到你的 `https_proxy` 配置，然后你需要知道的是 Go HTTP client 默认会启用 TLS 证书检查，如果你们公司所配的这个 `https_proxy` 并不包含一个公认可靠的 TLS 证书，那么就会被阻止，比如 `https_proxy` 是 `https://192.168.0.1:1443` 这种时 Go HTTP client 就无法通过那行请求。或者，有些教程会导致大家误用 `https_proxy`，比如把它设置成了跟 `http_proxy` 完全一样的非 HTTPS 代理，即不包含任何 TLS 层，这样也是不行的。
> 
> 要不你试试这样获取可行不：
> 
> ```shell
> $ go get -insecure github.com/gorilla/mux
> ```
> 
> 如果还是不行，恐怕你只能在使用 Go 时关闭 `http_proxy` 和 `https_proxy` 了。

有个疑问，我的127.0.0.1的http通道是可以使用的，本地开启了http代理上网。
浏览器使用这个地址正常使用。
为何go还是走不通呢？

**Comment by aofei** [comment]
> ……有些教程会导致大家误用 https_proxy，比如把它设置成了跟 http_proxy 完全一样的非 HTTPS 代理，即不包含任何 TLS 层，这样也是不行的。

据我所知网上能搜到的国内的教程基本都是写错了，并且类似 v2ray 之类的工具的作者也完全理解错了，把 https_proxy 跟 http_proxy 理解成一样的东西了，但实际上它俩并不相同，自然也就不能设置成一样的东西。
