### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by whyiyhw** [goproxy/goproxy.cn#72]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

没有找到

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.13.4 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/go/"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/xxxxxxxxxxxxxxx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build043346082=/tmp/go-build -gno-record-gcc-switches"

</pre>
</details>

## 你做了什么？

go get  github.com/360EntSecGroup-Skylar/excelize@v2.1.0

## 你期望看到的结果是什么？

成功下载，但是v1.4.1这个版本可以拉下来，之后的从v2.0.0 开始版本都提示，404.

## 你实际看到的结果是什么？

go: finding github.com/360EntSecGroup-Skylar/excelize v2.1.0
go get github.com/360EntSecGroup-Skylar/excelize@v2.1.0: github.com/360EntSecGroup-Skylar/excelize@v2.1.0: reading https://goproxy.cn/github.com/360%21ent%21sec%21group-%21skylar/excelize/@v/v2.1.0.info: 404 Not Found

**Comment by aofei** [comment]
你好，你的 Module path 用错啦，应该是 github.com/360EntSecGroup-Skylar/excelize 才对，你少了个“/v2”后缀，详见：https://github.com/360EntSecGroup-Skylar/excelize/blob/cea3d806ecbec5027a8f0d7f10b700707131a7be/go.mod#L1

此外，你直接打开报错的 https://goproxy.cn/github.com/360%21ent%21sec%21group-%21skylar/excelize/@v/v2.1.0.info 这个 URL 是可以看到详细错误信息的（如果你是 Go 1.14 的话不用打开就直接能在控制台看到）。

**Comment by whyiyhw** [comment]
十分感谢您的帮助~
