### ISSUE TITLE
Bug: 我们github上面的项目缓存只有一个README.md文件

### ISSUE THREAD

**Issue by Qoiuy** [goproxy/goproxy.cn#73]
## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.13.7 darwin/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lilac/Library/Caches/go-build"
GOENV="/Users/lilac/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lilac/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ct/qppvz7j57qxc8wqqj__9gss00000gn/T/go-build259950458=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre>
</details>

## What did you do?

step1 下载 https://github.com/zlzz-rec/zlyq-go/blob/master/example/client.go文件内容到本地
step2 配置 本地go mod 
export GOPROXY=https://goproxy.cn,direct && export GO111MODULE=on && echo \$GOPROXY && go env | grep 111
step3 在本地目录执行go run client.go  

会提示 build command-line-arguments: cannot load github.com/zlzz-rec/zlyq-go/handler: module github.com/zlzz-rec/zlyq-go@latest found (v1.0.1), but does not contain package github.com/zlzz-rec/zlyq-go/handler
但是我们项目是有文件的
项目地址： https://github.com/zlzz-rec/zlyq-go
release包下载地址 https://github.com/zlzz-rec/zlyq-go/archive/v1.0.1.tar.gz

## What is the behavior of the bug?

在本地 $GOPATH /pkg/mod/github.com/zlzz-rec 下只有 一个README.md文件 。正确的情况应该是一整个项目。

项目地址： https://github.com/zlzz-rec/zlyq-go
release包下载地址 https://github.com/zlzz-rec/zlyq-go/archive/v1.0.1.tar.gz

## Do you have any guesses?

因为我这里无法看到https://goproxy.cn 里面缓存的内容，所以不确定在https://goproxy.cn中，我的项目缓存的内容对应是什么？

**Comment by aofei** [comment]
你好，经核查，发现你似乎篡改过已发布的 Tag 是么？也就是当使用 [goproxy.cn](https://goproxy.cn) 访问完一个已发布的 Tag 后，你又删除并重发布了它或者覆盖了它，请问是否有这种情况？如果有的话，那么你需要知道这在现有所有 Go module proxy 中都是不允许的，详情看[这里](https://goproxy.cn/faq#我从我的库中移除了一个有问题的发行版，但它却仍然出现，我该怎么办？)。

**Comment by Qoiuy** [comment]
收到回复。谢谢你的帮助，感谢
