### ISSUE TITLE
问题：关于iris版本更新

### ISSUE THREAD

**Issue by schooltech** [goproxy/goproxy.cn#74]
## 你期望看到的结果是什么？

希望能更新到新版本

## 你实际看到的结果是什么？

一直没有更新，我没有比较其他的库的版本，是否也存在这个问题

**Comment by aofei** [comment]
需要注意，Go modules 中主版本号不同的话模块路径是需要变更的哦，不然 Go modules 是不会跨主版本升级的。

你可以试试把代码中 Iris 对应的 import path 中的 v11 全部替换成 v12 再试试。

**Comment by aofei** [comment]
详见：

https://github.com/kataras/iris/blob/b6ac39480bc98eab1d7f9dbe8ecb53be9851e848/go.mod#L1

**Comment by schooltech** [comment]
改了v12后可以了，谢谢
