### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by UDBIAWDIF** [goproxy/goproxy.cn#76]
用了GO MOD下载依赖包 github.com\satori\go.uuid 后, 发现里面的代码是旧版本的代码, 只能自己在GITHUB上下载新的代码覆盖进去, 不明白是什么原因造成的, 是不是你们仓库同步有问题

**Comment by aofei** [comment]
你好，请问你确定你启用了 Go modules 吗？听着不像，因为 Go modules 抓取的模块代码是比较难替换的，你能描述一下你是如何替的吗？或者，最好是遵循我们为大家提供的 Issue 模版哦，在任何别的项目里提 Issue 时也要注意遵循模版，这很重要，能节约大家的时间，那样我们能尽快地了解一些信息，比如在这里我们就必须先了解你的 go env 配置对不对，否则你现在的描述对于我们来说是比较乱的。

此外，Go 模块代理的工作机制不是传统的镜像服务那种每隔几个小时同步一次，并不存在“同步”这么一说，它是可实时回源的，至少 goproxy.cn 是这么实现的。

**Comment by aofei** [comment]
由于太久没有回应，所以我就先关闭这个 Issue 了哈，如果还有其他问题欢迎随时提问！😊
