### ISSUE TITLE
问题：GO1.14 module/proxy开启，go get 失败

### ISSUE THREAD

**Issue by HypoGump** [goproxy/goproxy.cn#77]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.1 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lxq/.cache/go-build"
GOENV="/home/lxq/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lxq/go_workplace"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build613743633=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

sudo go get -v golang.org/x/tools/go/buildutil

## 你期望看到的结果是什么？

无错误

## 你实际看到的结果是什么？

unrecognized import path "golang.org/x/tools/go/buildutil": https fetch: Get "https://golang.org/x/tools/go/buildutil?go-get=1": dial tcp 216.239.37.1:443: connect: connection refused

**Comment by aofei** [comment]
这种情况下你可以试试把 GOPROXY 中的“.direct”后缀去掉试试，具体原因详见：https://github.com/goproxy/goproxy.cn/issues/75#issuecomment-605975619

**Comment by HypoGump** [comment]
![image](https://user-images.githubusercontent.com/24915336/78671848-69d28d00-7912-11ea-941b-44ef28864c77.png)
我试过，也不行，环境是 vscode + wsl，好难呀

**Comment by aofei** [comment]
那可能你的 vscode 配置有问题了，环境变量应该是分开配置的，你在截图中的这个终端环境下是正常的吧？如果是，那就说明你的 vscode 配置有问题。

**Comment by aofei** [comment]
哦，我看到了，你在用 sudo，如果是 sudo 的话，那么你必须给 root 用户也配置上相关环境变量，你目前只给当前用户配置了。

比如，你执行 sudo go env 就明白了。

**Comment by HypoGump** [comment]
感谢感谢，确实是sudo改变了环境变量
