### ISSUE TITLE
Sonatype Sonatype Nexus 代理设置

### ISSUE THREAD

**Issue by zixianyang** [goproxy/goproxy.cn#78]
使用nexus创建本地代理，将远程地址设置为：https://goproxy.cn，nexus此goproxy的状态为不可用，请问我应该如何设置？

**Comment by aofei** [comment]
你好，请问“不可用”具体是指出现了什么错误？

**Comment by zixianyang** [comment]
‍
感谢您的回复，非常抱歉，可能是我这里网络的原因，有时候获取包超时，nexus的状态也显示成代理不可用，后台nexus错误输出为远程连接超时，如上图所示。
本地从nexus下获取会出现下面的错误提示，如果您有解决此问题的方法，请您告知。万分感谢！阿里云的代理可以正常使用。
`$ go get github.com/codeskyblue/gosuv
go: finding github.com/codeskyblue/gosuv latest
go: downloading github.com/codeskyblue/gosuv v0.0.0-20180605125048-3744b1b28ce4
verifying github.com/codeskyblue/gosuv@v0.0.0-20180605125048-3744b1b28ce4: github.com/codeskyblue/gosuv@v0.0.0-20180605125048-3744b1b28ce4: Get https://sum.golang.org/lookup/github.com/codeskyblue/gosuv@v0.0.0-20180605125048-3744b1b28ce4: dial tcp 216.58.200.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
`




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aofei Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 晚上6:12
收件人:&nbsp;"goproxy/goproxy.cn"<goproxy.cn@noreply.github.com&gt;;
抄送:&nbsp;"Thierry"<yang_thierry@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goproxy/goproxy.cn] Sonatype Sonatype Nexus 代理设置 (#78)





 
你好，请问“不可用”具体是指出现了什么错误？

**Comment by aofei** [comment]
goproxy.cn 是很早就支持代理 sum.golang.org 的，所以如果你配置得当的话是不会出现你给的这种 sum.golang.org 没被代理而是走直连的情况的，你能告诉我你是怎么配置的吗？

**Comment by zixianyang** [comment]
在本地设置代理，服务正常使用。但是nexus下使用您的代理，nexus后台输出里面会显示链接超时。我的nexus的配置页面如下图。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aofei Sheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 中午1:13
收件人:&nbsp;"goproxy/goproxy.cn"<goproxy.cn@noreply.github.com&gt;;
抄送:&nbsp;"Thierry"<yang_thierry@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goproxy/goproxy.cn] Sonatype Sonatype Nexus 代理设置 (#78)





 
goproxy.cn 是很早就支持代理 sum.golang.org 的，所以如果你配置得当的话是不会出现你给的这种 sum.golang.org 没被代理而是走直连的情况的，你能告诉我你是怎么配置的吗？

**Comment by aofei** [comment]
图片似乎没有传上来呢？我看不到。😅

**Comment by aofei** [comment]
由于太久没有回复，所以我先关闭这个 Issue 了哈，如果你还有其他问题欢迎随时提问，我会继续保持快速回复的～😊
