### ISSUE TITLE
问题：如何标注私有仓库不通过proxy

### ISSUE THREAD

**Issue by LucasDove** [goproxy/goproxy.cn#79]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.12.13 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GOARCH="amd64"
GOBIN="/Users/yuanxie/work/go_proj/bin"
GOCACHE="/Users/yuanxie/Library/Caches/go-build"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yuanxie/work/go_proj"
GOPROXY="off"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yuanxie/work/forder-server/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kp/ymr5srdj4_s44jdjbmqqvxhh0000gn/T/go-build845842052=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre>
</details>

## 你做了什么？

在dockerfile里执行 GO111MODULE=on GOPROXY=https://goproxy.cn go mod download 下载项目依赖

## 你期望看到的结果是什么？

拉取所有的依赖库成功

## 你实际看到的结果是什么？

公司私有仓库域名下的包下载失败

**Comment by aofei** [comment]
你好，我来回答下你的问题。

当你们容器环境的 Go 版本 >= 1.13 时，假设你们公司的内网 VCS 源是 `git1.example.com` 和 `git2.example.com`，那么对应你应该配置环境变量 `GOPRIVATE=git1.example.com,git2.example.com`，此时 `go` 在拉取所有 module path 是以这两个端点为前缀的模块版本时都会忽略 `GOPROXY` 和 `GOSUMDB` 配置，并以 `direct` 的形式直接回源拉取。

当你们容器环境的 Go 版本 < 1.13 时，那么情况就会比较复杂了，最好的解决方案是你们在公司内部搭建私有模块代理，并为其配置上相应权限，具体搭建方法可以参考[这里](https://goproxy.cn/#自托管%20Go%20模块代理)。

**Comment by aofei** [comment]
由于太久没有回复，所以我先关闭这个 Issue 了哈，如果你还有其他问题欢迎随时提问，我会继续保持快速回复的～😊
