### ISSUE TITLE
问题：github.com/guonaihong/clop@v0.0.5 下载失败

### ISSUE THREAD

**Issue by guonaihong** [goproxy/goproxy.cn#81]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.13.1 linux/amd6
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/guo/.cache/go-build"
GOENV="/home/guo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/guo/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/home/guo/go-version/go1.13.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/guo/go-version/go1.13.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/guo/use_clop/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build092751184=/tmp/go-build -gno-record-gcc-switches"

<pre>
$ go env

</pre>
</details>

## 你做了什么？
使用goproxy.cn时，下载下面的模块失败，换成goproxy.io就可以。
go get github.com/guonaihong/clop@v0.0.5 

## 你期望看到的结果是什么？
可以成功下载。

## 你实际看到的结果是什么？
报模块找不到 404。

**Comment by aofei** [comment]
你好，

造成了麻烦实在抱歉。

按照惯例，我来详细分享下造成这个问题的原因。是我们境外服务器的后台服务到国内的对象存储服务的环节出现了问题，对象存储服务给了我们过期的证书，证书过期时间显示的是昨晚 20 点，也就是说老哥你遇到的这个问题是昨晚 20 点开始的。其实这个我们是有做预防措施的，类似的这种情况我们会抛回 404，因为 `go` 有对 404 做特殊优化。所以建议老哥可以把 `GOPROXY` 配置成 `https://goproxy.cn,direct`，即多个 `,direct` 后缀，这么做的好处是当 [goproxy.cn](https://goproxy.cn) 返回了 404 时 `go` 命令会自动尝试回源直接抓取，相当于多给了 `go` 一次机会。即使以后不会再出现类似问题，多个 `,direct` 后缀也是有很多好处的，比如 `GONOPROXY`、`GONOSUMDB` 和 `GOPRIVATE` 是需要依赖 `direct` 来正常工作的。

证书异常问题已上报给运维老哥，他们也已加急解决，所以这个 Issue 我就关闭了哈，以后再遇到其他问题欢迎随时反馈，我会尽快回复的！

你可以试着访问一下：https://goproxy.cn/github.com/guonaihong/clop/@v/v0.0.5.info

感谢老哥的及时反馈！帮助很大～❤️
