### ISSUE TITLE
问题：执行go get命令，返回net/http: TLS handshake timeout错误提示

### ISSUE THREAD

**Issue by sunmu01** [goproxy/goproxy.cn#82]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.2 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/sunmu/Library/Caches/go-build"
GOENV="/Users/sunmu/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sunmu/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rm/zgg8nwyd1l96nk8hj6kl487w0000gn/T/go-build231691632=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？

在终端执行命令：
$ go get -u golang.org/x/lint/golint
go get golang.org/x/lint/golint: module golang.org/x/lint/golint: Get "https://goproxy.cn/golang.org/x/lint/golint/@v/list": net/http: TLS handshake timeout

在浏览器中访问URL“https://goproxy.cn/golang.org/x/lint/golint/@v/list”，返回如下信息：
not found: module golang.org/x/lint/golint: no matching versions for query "latest"

## 你期望看到的结果是什么？

能通过go get和install成功安装go tools

**Comment by aofei** [comment]
你好，请问你的终端有没有在使用别的代理机制？比如 HTTP Proxy 之类的，因为这个属于你的终端网络环境错误，你的浏览器访问正常，而且返回内容也正常。

**Comment by sunmu01** [comment]
MacOS环境下的命令行环境，没有使用其他的代理机制。网络环境是：联通家庭宽带，DHCP接入。

$ ping goproxy.cn
PING tinyglobalcdndownload.qiniu.com.w.kunlunar.com (123.129.244.203): 56 data bytes
64 bytes from 123.129.244.203: icmp_seq=0 ttl=46 time=20.621 ms
64 bytes from 123.129.244.203: icmp_seq=1 ttl=46 time=18.868 ms
64 bytes from 123.129.244.203: icmp_seq=2 ttl=46 time=19.322 ms
64 bytes from 123.129.244.203: icmp_seq=3 ttl=46 time=20.411 ms

**Comment by aofei** [comment]
刚我测试了一下 123.129.244.203 这个 CDN 节点，一切正常，所以你那边终端的网络环境可能还是有些问题。麻烦你在终端跑一下这个命令并把结果复制上来：

```bash
$ curl -i -v https://goproxy.cn/golang.org/x/lint/golint/@v/list
```

**Comment by sunmu01** [comment]
# sunmu @ SUNdeMacBook-Pro in ~ [12:24:22] C:1
$ curl -i -v https://goproxy.cn/golang.org/x/lint/golint/@v/list
*   Trying 123.129.244.203...
* TCP_NODELAY set
* Connected to goproxy.cn (123.129.244.203) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.goproxy.cn
*  start date: Jul 19 00:00:00 2019 GMT
*  expire date: Jul 18 12:00:00 2020 GMT
*  subjectAltName: host "goproxy.cn" matched cert's "goproxy.cn"
*  issuer: C=CN; O=TrustAsia Technologies, Inc.; OU=Domain Validated SSL; CN=TrustAsia TLS RSA CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe94580e800)
> GET /golang.org/x/lint/golint/@v/list HTTP/2
> Host: goproxy.cn
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404
HTTP/2 404
< server: Tengine
server: Tengine
< content-type: text/plain; charset=utf-8
content-type: text/plain; charset=utf-8
< content-length: 83
content-length: 83
< date: Sun, 03 May 2020 04:25:45 GMT
date: Sun, 03 May 2020 04:25:45 GMT
< cache-control: public, max-age=600
cache-control: public, max-age=600
< x-m-log: QNM:fs166;SRCPROXY:fs177;SRC:9/404;SRCPROXY:9/404;QNM3:10/404
x-m-log: QNM:fs166;SRCPROXY:fs177;SRC:9/404;SRCPROXY:9/404;QNM3:10/404
< x-m-reqid: FmIAAC7ugTcYagsW
x-m-reqid: FmIAAC7ugTcYagsW
< x-qnm-cache: Miss
x-qnm-cache: Miss
< ali-swift-global-savetime: 1588479945
ali-swift-global-savetime: 1588479945
< via: cache34.l2cm9-5[50,404-1280,M], cache33.l2cm9-5[51,0], kunlun3.cn9[79,404-1280,M], kunlun8.cn9[84,0]
via: cache34.l2cm9-5[50,404-1280,M], cache33.l2cm9-5[51,0], kunlun3.cn9[79,404-1280,M], kunlun8.cn9[84,0]
< x-swift-error: orig response 4XX error
x-swift-error: orig response 4XX error
< x-cache: MISS TCP_MISS dirn:-2:-2
x-cache: MISS TCP_MISS dirn:-2:-2
< x-swift-savetime: Sun, 03 May 2020 04:25:45 GMT
x-swift-savetime: Sun, 03 May 2020 04:25:45 GMT
< x-swift-cachetime: 600
x-swift-cachetime: 600
< x-swift-error: orig response 4XX error
x-swift-error: orig response 4XX error
< timing-allow-origin: *
timing-allow-origin: *
< eagleid: 7b81f49c15884799457774357e
eagleid: 7b81f49c15884799457774357e

<
* Connection #0 to host goproxy.cn left intact
not found: module golang.org/x/lint/golint: no matching versions for query "latest"%

# sunmu @ SUNdeMacBook-Pro in ~ [12:25:45]
$ go get -u golang.org/x/lint/golint
go get golang.org/x/lint/golint: module golang.org/x/lint/golint: Get "https://goproxy.io/golang.org/x/lint/golint/@v/list": net/http: TLS handshake timeout

**Comment by aofei** [comment]
`Connection #0 to host goproxy.cn left intact` 这句话表明使用 cURL 连接 `goproxy.cn` 是一切正常的。如果相同环境下 `go` 无法正常工作，那很有可能是你的系统其他代理设置错误导致的了，因为 `go` 的 HTTP client 对系统代理毕竟严格。麻烦你确认一下这两个环境变量有没有值：

```bash
$ echo $HTTP_PROXY && echo $http_proxy
$ echo $HTTPS_PROXY && echo $https_proxy
```

**Comment by sunmu01** [comment]
执行这两个命令，返回都是空的。

我的系统中，原来安装过go1.9.x（在Cellar目录下，应该是Xcode安装的），我昨天安装go1.14之后，go version仍然显示1.9.x，后来在将Cellar下的go目录改名了，才默认使用go.1.14，会不会这这个操作有关系？

**Comment by aofei** [comment]
在 Cellar 下的话估计你是用 Homebrew 安装的了。

跟你的这些操作应该没有关系，因为你现在发出来的版本已经是 `go version go1.14.2 darwin/amd64` 了。不过你还是可以尝试清理一下环境，你现在似乎是安装器安装的，或者手动安装的，因为你的 `GOROOT` 是 `/usr/local/go`。

我还是觉得你的终端可能有别的什么代理工具，你确定你没有用什么乱七八糟的比如 proxychains 之类的嘛？

**Comment by sunmu01** [comment]
的确没有安装什么代理。这个笔记本用了6年了，环境有点乱了，我还是重装一下系统吧。

打扰你了，这个issue就close了。谢谢！

**Comment by aofei** [comment]
好的，如果还有其他问题的话欢迎随时来提问，我会尽力帮忙的，😊

**Comment by petershi5** [comment]
设置为中国go代理，在cmd中输入：
```
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct
```
