### ISSUE TITLE
cannot go get goimports after I have set GO111MODULE and GOPROXY variables?

### ISSUE THREAD

**Issue by Neulana** [goproxy/goproxy.cn#83]
## Are you sure that our [FAQ](https://goproxy.cn/faq) page doesn't have the question you want to ask?

yes

## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.13.6 darwin/amd64
</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/t50t/Library/Caches/go-build"
GOENV="/Users/t50t/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/t50t/code/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/Cellar/go/1.13.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8w/4hjwb9516sxfm4cx00zxch5w0000gn/T/go-build088862398=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## What did you do?

go get -v golang.org/x/tools/cmd/goimports

## What did you expect to see?

I expect to see that there is a new directory named "tools" in "golang.org/x" directory in my GOPATH? 

## What did you see instead?

But there is no "tools" after i execute "go get".

**Comment by Neulana** [comment]
![WechatIMG109.jpeg](https://i.loli.net/2020/05/05/V12nliuTzpEFtC3.jpg)

**Comment by aofei** [comment]
If you're using Go modules, then you should to know that all the module versions you got are placed in the $GOPATH/pkg/mod dir, instead of in the $GOPATH/src.

**Comment by Neulana** [comment]
Oh, I am sorry. Its my fault, thanks a lot!
