### ISSUE TITLE
问题：按照步骤设置了代理  go get 还是失败

### ISSUE THREAD

**Issue by hoset** [goproxy/goproxy.cn#84]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

确定

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

</pre>
</details>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\PC\AppData\Local\go-build
set GOENV=C:\Users\PC\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\goWork
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\P
C\AppData\Local\Temp\go-build626194590=/tmp/go-build -gno-record-gcc-switches

## 你做了什么？

没有
## 你期望看到的结果是什么？

希望能正常下载

## 你实际看到的结果是什么？

go get golang.org/x/sy: unrecognized import path "golang.org/x/sy": https fetch: Get "https://golang.org/x/sy?go-get=1": dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, o
r established connection failed because connected host has failed to respond.

**Comment by aofei** [comment]
你的描述中显示你的 GOPROXY 是 `direct`，意思是不使用任何 Go module proxy，你需要将它设置为 `https://goproxy.cn,direct` 才行。

**Comment by hoset** [comment]
完美解决。之前用powershell设置的，goland添加依赖，在powershell里面查看GOPROXY=https://goproxy.cn   ，没有注意到 用goland里面要单独设置代理

**Comment by aofei** [comment]
既然问题已解决，那么我就关闭这个 Issue 了哈，如果还有别的问题欢迎随时提问～
