### ISSUE TITLE
问题：win10设置了代理，go get执行失败

### ISSUE THREAD

**Issue by lizcao** [goproxy/goproxy.cn#85]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.2 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lizcao\AppData\Local\go-build
set GOENV=C:\Users\lizcao\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\lizcao\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\lizcao\go\src\hello\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\lizcao\AppData\Local\Temp\go-build815060050=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

go get -u github.com/gin-gonic/gin

## 你期望看到的结果是什么？

顺利安装

## 你实际看到的结果是什么？

go get github.com/gin-gonic/gin: module github.com/gin-gonic/gin: Get "https://goproxy.cn/github.com/gin-gonic/gin/@v/list": dial tcp 27.159.71.218:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by aofei** [comment]
你好，经查证 `27.159.71.218` 这个似乎并不是我们的 CDN 节点 IP，请问你的网络环境是有存在代理之类的东西吗？

或者麻烦你执行一下这个命令并把结果贴上来：

```bash
$ dig goproxy.cn
```

**Comment by lizcao** [comment]
您好，感谢您抽出宝贵的时间帮我解决问题，下面是执行命令的结果，麻烦帮忙看下
nslookup goproxy.cn：
`服务器:  [my-company].com
Address:  10.24.32.19

非权威应答:
名称:    tinyglobalcdndownload.qiniu.com.w.kunlunar.com
Address:  27.159.71.218
Aliases:  goproxy.cn
          goproxy.cn.qiniudns.com
          largeglobal011.qiniudns.com`

**Comment by aofei** [comment]
抱歉晚回复了，请问你是不是在 docker 之类的容器环境中？如果是的话，那么似乎你的容器环境存在有网络通信问题，DNS 查询倒是正常工作的。

**Comment by lizcao** [comment]
谢谢， 可能是与公司的网络有关系，在家里电脑是可以的
