### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by daliyo** [goproxy/goproxy.cn#86]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.2 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\J\AppData\Local\go-build
set GOENV=C:\Users\J\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\J\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\workspace\code\golang\src\daliyo.net\app_517mt\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\J\AppData\Local\Temp\go-build740036238=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你做了什么？

go get github.com/denisenkom/go-mssqldb

## 你期望看到的结果是什么？

希望这个包能安装成功

## 你实际看到的结果是什么？

go get github.com/denisenkom/go-mssqldb: module github.com/denisenkom/go-mssqldb: reading https://goproxy.cn/github.com/denisenkom/go-mssqldb/@v/list: 404 Not Found
        server response:
not found: GET http://localhost:10080/github.com/denisenkom/go-mssqldb/@v/list: 403 Forbidden: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by aofei** [comment]
已修复，感谢反馈！

**Comment by aofei** [comment]
另外顺便说一下，如果你还是在看到这个错误，那是因为 CDN 缓存造成的，稍等几分钟就好了。
