### ISSUE TITLE
问题：请问我能否搭建自身的goproxy.cn并全量镜像你们的缓存

### ISSUE THREAD

**Issue by Alberthchang** [goproxy/goproxy.cn#88]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？
没有

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.2 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

各种环境变量
</pre>
</details>

## 你做了什么？
期望镜像

## 你实际看到的结果是什么？

我希望能全量镜像这个源，因公司需求，我需要在公司内网搭建一个goproxy，所以希望能全量镜像这个库，请问有什么办法？

**Comment by aofei** [comment]
我们没有设置任何 Rate Limit，并且也没有设置带宽限制，所以你是可以从我们的服务上极速下载任意量数据的，这也就意味着你可以完整地拷贝我们的缓存资源。

但是，有几点需要说明一下。首先是从 [goproxy.cn/stats/summary](https://goproxy.cn/stats/summary) 中可以看到我们缓存的数据大小已超过了 3T，所以完整拷贝需要你们提供足够的存储空间。其次，需要注意我们的服务并不等同于平时所说的“传统镜像”，它并不存在“定时回源同步”这么一说，很多操作是动态实时的，所以即使你完整拷贝了我们现有的缓存资源也并不能打造一个功能齐全的 Go 模块代理服务。最后，我们并没有提供类似 [index.golang.org](https://index.golang.org) 的索引服务，所以你是无法完整罗列我们现有的已缓存模块版本的。

我们的建议是，如果可以在一定程度上突破内网限制，那么参考 [goproxy.cn](https://goproxy.cn) 首页中所提到的搭建自托管 Go 模块代理的方法来为你们公司的这个私有 Go 模块代理，并采用 [goproxy.cn](https://goproxy.cn) 作其上游是最好的解决方案。

**Comment by Alberthchang** [comment]
突破内网限制比较难，实在不能我就只能镜像主要的包了

**Comment by aofei** [comment]
问题应该已经回答到了，所以这个 issue 我就先关闭了哈，如果还有其他问题欢迎随时提问～
