### ISSUE TITLE
问题：github.com/mozillazg/request 下载后不能导入

### ISSUE THREAD

**Issue by huifer** [goproxy/goproxy.cn#89]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.3 windows/amd64

</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOENV=C:\Users\admin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\admin\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\desktop\git_repo\go_lang\justauth-go\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ad
min\AppData\Local\Temp\go-build231056210=/tmp/go-build -gno-record-gcc-switches

</pre>
</details>

## 你做了什么？
```
go get -u github.com/mozillazg/request

```

## 你期望看到的结果是什么？
- 找到这个包

## 你实际看到的结果是什么？

```
go: found github.com/mozillazg/request/... in github.com/mozillazg/request v0.8.0
go: finding module for package github.com/bitly/go-simplejson
go: finding module for package github.com/bmizerany/assert
go: finding module for package golang.org/x/net/proxy
go: finding module for package golang.org/x/net/publicsuffix
go: found github.com/bitly/go-simplejson in github.com/bitly/go-simplejson v0.5.0
go: found golang.org/x/net/proxy in golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: found github.com/bmizerany/assert in github.com/bmizerany/assert v0.0.0-20160611221934-b7ed37b82869
go: finding module for package github.com/kr/pretty
go: found github.com/kr/pretty in github.com/kr/pretty v0.2.0

```

**Comment by aofei** [comment]
你好，抱歉没有太理解你的问题，因为你贴出的输出结果第一行显示的内容就表示你已经找到这个 github.com/mozillazg/request 包了。

麻烦更详细地描述下你现在所遇到的问题。

**Comment by huifer** [comment]
在编辑器中
![image](https://user-images.githubusercontent.com/26766909/84230113-c96d3480-ab1d-11ea-90fb-13ceda6be727.png) 没有将相应的包导入
![image](https://user-images.githubusercontent.com/26766909/84230159-e9045d00-ab1d-11ea-8d50-3bdebf35f4f4.png)

**Comment by aofei** [comment]
你的左侧目录树中的 go.mod 报红了呢，代码可以使用这个包之前，你需要确保 go.mod 中有与之对应的模块条目，否则就说明你并没有配置对 Go modules，或者说你的 go get 命令是在错误的地方执行的。建议先排查一下你的 go.mod 文件。

**Comment by huifer** [comment]
- mod文件如下
```mod
module oauth

go 1.14

require (
	github.com/bitly/go-simplejson v0.5.0 // indirect
	github.com/mozillazg/request v0.8.0 // indirect
	golang.org/x/net v0.0.0-20200602114024-627f9648deb9 // indirect
)

```

**Comment by huifer** [comment]
我解决了. 
![image](https://user-images.githubusercontent.com/26766909/84232619-3fc06580-ab23-11ea-9785-600627229880.png)忘记开启mod了 T_T

**Comment by aofei** [comment]
需要注意，GoLand 之类的 IDE 会覆盖系统环境变量的，所以你还需要在这个“Environment”输入框中再配置一下 GOPROXY 环境变量。

**Comment by huifer** [comment]
![image](https://user-images.githubusercontent.com/26766909/84234693-3e913780-ab27-11ea-8444-1720fd59c5a2.png)
这个配置是存在的. 不知道是否正确呢

**Comment by aofei** [comment]
我还没有使用过 GoLand，但看起来似乎是正确的，可以用用看，不出问题就行。
