### ISSUE TITLE
请教下go mod 多目录分模块的问题

### ISSUE THREAD

**Issue by taadis** [goproxy/goproxy.cn#9]
通常这样新建一个模块并且发布:

```
go mod init github.com/username/modulename
git tag v1.0.0
git push origin v1.0.0
go get github.com/username/modulename@v1.0.0
```

上面这样以根目录发布一个模块, 没有问题.

问题是同一个仓库下多个目录分模块:

```
github.com/username/modulename/moda
github.com/username/modulename/modb
github.com/username/modulename/modc
```

这样分 `moda/modb/modc` 模块, 应该如果发布各自的版本?

**Comment by aofei** [comment]
你好，我想你所描述的控制不同版本的场景不应该是只存在一个模块，而应该是三个完全独立的模块，因为一个模块只对应一个版本树才更合理。所以你不应该在 `modulename` 下执行 `go mod init` 或直接放置 `go.mod` 文件，而是应该分别在 `modulename/moda`、`modulename/modb`、`modulename/modc` 下执行，这样就分别创建了你所提到的三个模块，也就可以分别管理版本了。

**Comment by taadis** [comment]
@aofei 我现在就是在 不同目录下各自有一个 `go.mod` 文件, 但是应该如何发布版本tag呢? 直接 `git tag vx.y.z`, `go get` 会报异常...

**Comment by aofei** [comment]
如果非要对一个仓库的不同子文件夹打标签的话理论上也不是不可以，因为在 Git 中每个子文件夹都是一棵树。但是，这种做法总感觉没有太大的实用价值，我暂时也想不出它有什么应用场景。我一直认为在使用 CVS 来管理不同的模块时，一个 CVS 的单元（仓库）应该只去对应一个模块而不是多个，这样会让开发和维护的思路更清晰不是吗？

抱歉这么久才回复。

**Comment by taadis** [comment]
懂得, 我也知道一个模块一个独立的仓库会更好, 但是我现在想知道, 一个仓库多个模块应该如何发布版本tag才能正常被使用者`go get`. 求解!!!

**Comment by aofei** [comment]
[aofei/test-go-modules](https://github.com/aofei/test-go-modules)

你可以这样使用：

```go
package main

import (
	"github.com/aofei/test-go-modules/modulea"
	"github.com/aofei/test-go-modules/moduleb"
	"github.com/aofei/test-go-modules/modulec"
)

func main() {
	modulea.HelloA()
	moduleb.HelloB()
	modulec.HelloC()
}
```

解决办法就是打标签时采用指定“先行版本号”的小技巧来指明这个版本是为哪个具体模块而发布的，而且它们的父目录，也就是仓库的根目录本身并不作为一个模块而存在（即没有 `go.mod` 文件），这样就可以做到互不干扰了。

抱歉我从没有接触过这个场景，所以这是我目前能想到的最好的解决办法了。

**Comment by aofei** [comment]
`go get` 的查询规则：https://tip.golang.org/cmd/go/#hdr-Module_queries

**Comment by taadis** [comment]
额 这些我都知道, 但是还是不清楚一个仓库多个模块如何分别打版本tag, 以便使用...
我问题的重点是: "一个仓库多个模块如何打版本tag", 其实我想问的这个操作细节...我试过各种方式, 总是不对...能否麻烦尝试一下给个答案...

**Comment by taadis** [comment]
就拿你测试这个而言 `https://github.com/aofei/test-go-modules`, 不发布任何 tag 版本的时候, 使用时会下载安装 master 下的最新代码, 但是当发布 v0.0.1 后, 使用时就会报错, 你可以试一下...

**Comment by aofei** [comment]
抱歉，既然我知道的你都已经知道了，那看来我没有能力继续解答你这个问题了，我刚也提到了我的确没有见过哪个项目有这个应用场景，所以请原谅我的经验储备不足。

不过我建议你去 https://github.com/golang/go/issues 提问，那里的专家非常多，而且我相信 Go team 也会非常乐意帮助你的。

鉴于这个 Issue 本身和这个项目关系不大，所以我要把这个 Issue 关闭了，如果你还有其他和这个项目相关的问题，可以直接创建新的 Issue，谢谢支持。

**Comment by taadis** [comment]
好吧 多谢了...

**Comment by wlx10011101** [comment]
，打tag时按modulea/v1.0.0应该可以解决多目录按tag go get

**Comment by aofei** [comment]
@wlx10011101 谢谢回复！有心了👍

我也是最近知道的同仓库多模块的发版方式，可以参考这个：https://github.com/golang/tools/releases

**Comment by 00LT00** [comment]
@wlx10011101 @aofei 想请教下为什么可以这么写，或者说有哪里可以看到关于这个操作的文档，目前我只是看有人再用，但是不知道在哪规定了这种写法，单纯好奇

**Comment by aofei** [comment]
@00LT00 

https://golang.org/ref/mod#vcs-version

> If a module is defined in a subdirectory within the repository, that is, the module subdirectory portion of the module path is not empty, then each tag name must be prefixed with the module subdirectory, followed by a slash. For example, the module golang.org/x/tools/gopls is defined in the gopls subdirectory of the repository with root path golang.org/x/tools. The version v0.4.0 of that module must have the tag named gopls/v0.4.0 in that repository.

**Comment by 00LT00** [comment]
感谢 @aofei
