### ISSUE TITLE
问题：go get

### ISSUE THREAD

**Issue by antkit** [goproxy/goproxy.cn#90]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

没有。

## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.3 linux/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/gopath"
GOPRIVATE=""
GOPROXY="http://goproxy.my.com"
GOROOT="/data/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/tmp/mygo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build266790386=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

## 你做了什么？

<pre>
$ go get github.com/dgrijalva/jwt-go
</pre>

## 你期望看到的结果是什么？

正确获取到 github.com/dgrijalva/jwt-go 这个包。

## 你实际看到的结果是什么？

go get 输出：
<pre>
go: downloading github.com/dgrijalva/jwt-go v1.0.2
go get github.com/dgrijalva/jwt-go: github.com/dgrijalva/jwt-go@v1.0.2: verifying module: github.com/dgrijalva/jwt-go@v1.0.2: Get "https://sum.golang.org/lookup/github.com/dgrijalva/jwt-go@v1.0.2": dial tcp 34.64.4.113:443: connect: connection timed out
</pre>

goproxy 输出：
<pre>
2020/06/10 10:35:11 github.com/dgrijalva@latest: invalid github.com/ import path "github.com/dgrijalva"
2020/06/10 10:35:15 github.com@latest: unrecognized import path "github.com": parse https://github.com/?go-get=1: no go-import meta tags ()
</pre>

## 其他说明

测试通过 go get 获取其他包未见异常。

**Comment by aofei** [comment]
你好，这个错误表明你配置的这个 GOPROXY="http://goproxy.my.com" 模块代理并不支持代理校验和数据库呢，请问这个模块代理是你自己搭建的吗？如果是的话，那么请问是如何搭建的？

**Comment by antkit** [comment]
> 你好，这个错误表明你配置的这个 GOPROXY="http://goproxy.my.com" 模块代理并不支持代理校验和数据库呢，请问这个模块代理是你自己搭建的吗？如果是的话，那么请问是如何搭建的？

是的，我们是自己搭建了一台 goproxy 服务器。这台 goproxy 服务器的 go env 部分输出：
```
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOPROXY="https://goproxy.cn,direct"
```

经测试，在这台机器上获取 github.com/dgrijalva/jwt-go 是正常的，也就是从 goproxy.cn 官网代理是可以走通的：
```
$ go get github.com/dgrijalva/jwt-go
go: downloading github.com/dgrijalva/jwt-go v1.0.2
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: github.com/dgrijalva/jwt-go upgrade => v3.2.0+incompatible
```

但是我们需要自己搭建一台服务供公司内网使用，搭建过程是参照 goproxy.cn 首页文档 [自托管 Go 模块代理](https://goproxy.cn/#%E8%87%AA%E6%89%98%E7%AE%A1%20Go%20%E6%A8%A1%E5%9D%97%E4%BB%A3%E7%90%86) 进行操作的，main.go 全部代码如下：
```go
package main

import (
        "net/http"
        "os"

        "github.com/goproxy/goproxy"
)

func main() {
        g := goproxy.New()
        g.GoBinEnv = append(
                os.Environ(),
                "GOPROXY=https://goproxy.cn,direct", // 使用 goproxy.cn 作为上游代理
                "GOPRIVATE=my.com",         // 解决私有模块的拉取问题（比如可以配置成公司内部的代码源）
        )
        http.ListenAndServe("0.0.0.0:6678", g)
}
```

编译并运行：
```bash
$ go build -o goproxy
$ ./goproxy
```

然后在另外一台机器（这台机器是不能联通外网的）上配置 GOPROXY 指向了上面运行 goproxy 的这台机器，经测试其他一些包均能正常获取到（此时goproxy服务不会打印任何日志），唯独 github.com/dgrijalva/jwt-go 会出问题，goproxy 服务会打印两行日志：
```
2020/06/10 10:35:11 github.com/dgrijalva@latest: invalid github.com/ import path "github.com/dgrijalva"
2020/06/10 10:35:15 github.com@latest: unrecognized import path "github.com": parse https://github.com/?go-get=1: no go-import meta tags ()
```

**Comment by aofei** [comment]
首先，服务打印的那两行日志是正常的，即使他们是“错误”信息，因为这就是 Go modules 的工作方式，它会根据 404 依次为某个 module path 做 fallback，每次修剪掉尾部的一个 path element，直到没有 path element 时抛出错误。总之，这两行日志不用过多在意。

其次，你可以看到 [Goproxy 文档](https://pkg.go.dev/github.com/goproxy/goproxy?tab=doc#Goproxy) 中的 `Goproxy` 结构体拥有一个 `ProxiedSUMDBs` 字段，你现在是需要参考如下设置一下它才行，即表示为模块代理开启代理校验和数据库的功能，否则你就必须在使用你搭建的模块代理的客户端关闭 GOSUMDB 环境变量才行了。

```go
...
g.ProxiedSUMDBs = []string{"sum.golang.org https://goproxy.cn/sumdb/sum.golang.org"}
...
```

**Comment by antkit** [comment]
> 首先，服务打印的那两行日志是正常的，即使他们是“错误”信息，因为这就是 Go modules 的工作方式，它会根据 404 依次为某个 module path 做 fallback，每次修剪掉尾部的一个 path element，直到没有 path element 时抛出错误。总之，这两行日志不用过多在意。
> 
> 其次，你可以看到 [Goproxy 文档](https://pkg.go.dev/github.com/goproxy/goproxy?tab=doc#Goproxy) 中的 `Goproxy` 结构体拥有一个 `ProxiedSUMDBs` 字段，你现在是需要参考如下设置一下它才行，即表示为模块代理开启代理校验和数据库的功能，否则你就必须在使用你搭建的模块代理的客户端关闭 GOSUMDB 环境变量才行了。
> 
> ```go
> ...
> g.ProxiedSUMDBs = []string{"sum.golang.org https://goproxy.cn/sumdb/sum.golang.org"}
> ...
> ```

非常感谢，参照着加上去后问题得到解决！
