### ISSUE TITLE
问题：使用go get 安装一个go 的bin程序时，404报错。直接访问github无此问题

### ISSUE THREAD

**Issue by hoojos** [goproxy/goproxy.cn#91]
## 你确定我们的[常见问题](https://goproxy.cn/faq)页面中没有你想要询问的问题吗？

没有
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.2 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bjhl/Library/Caches/go-build"
GOENV="/Users/bjhl/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="git.baijiahulian.com"
GONOSUMDB="git.baijiahulian.com"
GOOS="darwin"
GOPATH="/Users/bjhl/go"
GOPRIVATE="git.baijiahulian.com"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bjhl/Git/git.baijiahulian.com/proj-apps/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nc/zw50f9n502j13cnkc6hzxnb80000gn/T/go-build296613709=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

## 你做了什么？

go get github.com/twitchtv/twirp/protoc-gen-twirp@v5.11.0

## 你期望看到的结果是什么？

在$GOPATH/bin目录下，安装好`protoc-gen-twirp`命令

## 你实际看到的结果是什么？

go get github.com/twitchtv/twirp/protoc-gen-twirp@v5.11.0: github.com/twitchtv/twirp/protoc-gen-twirp@v5.11.0: reading https://goproxy.cn/github.com/twitchtv/twirp/protoc-gen-twirp/@v/v5.11.0.info: 404 Not Found
	server response: not found: github.com/twitchtv/twirp/protoc-gen-twirp@v5.11.0: invalid version: unknown revision protoc-gen-twirp/v5.11.0

**Comment by aofei** [comment]
你好，github.com/twitchtv/twirp 这个模块并不存在 v5.11.0 这个版本，尽管它的 tag tree 中有，但是它的 module path 不遵循 Go modules 的规则，所以你无法在 go get 的 @ 后面使用它。

你可以试试这样：go get github.com/twitchtv/twirp/protoc-gen-twirp@v5.11.0+incompatible

**Comment by hoojos** [comment]
谢谢，我用你提供的方案可以正常安装了
