### ISSUE TITLE
go get -v github.com/go-delve/delve/cmd/dlv一直失败

### ISSUE THREAD

**Issue by Endlife93** [goproxy/goproxy.cn#92]
我是vscode 安装呢golang插件  
Installing github.com/mdempsky/gocode SUCCEEDED
Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/cweill/gotests/... SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl SUCCEEDED
Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
Installing github.com/godoctor/godoctor SUCCEEDED
**Installing github.com/go-delve/delve/cmd/dlv FAILED**
Installing github.com/stamblerre/gocode SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing golang.org/x/tools/cmd/goimports SUCCEEDED
Installing golang.org/x/lint/golint SUCCEEDED
Installing golang.org/x/tools/gopls SUCCEEDED

**Comment by aofei** [comment]
你好，请问你的 VSCode 所在环境的环境变量跟系统一致嘛？麻烦贴个 go env 的输出结果我看一下是否配置正确。

**Comment by aofei** [comment]
由于长时间未回复，所以这个 Issue 我就先关闭了哈，如果还有其他问题欢迎随时提问，我会继续保持及时回应的～

**Comment by wubaolin-art** [comment]
![Uploading 截屏2021-04-12 下午5.00.39.png…]()
