### ISSUE TITLE
问题：设置了GOPROXY还是出现i/o timeout

### ISSUE THREAD

**Issue by hzjnet** [goproxy/goproxy.cn#93]
环境情况：
1 go env  ：
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aajnet/.cache/go-build"
GOENV="/home/aajnet/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/aajnet/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build077723499=/tmp/go-build -gno-record-gcc-switches"

2 版本
OS：
 lsb_release -ra
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core

 go version
go version go1.13.11 linux/amd64

3 设置：
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct

4 问题参考：https://github.com/goproxy/goproxy.cn/issues/29

我的问题：
经过以上设置和检查还是出现：
Get "https://proxy.golang.org/github.com/dgryski/go-metro/@v/v0.0.0-20180109044635-280f6062b5bc.mod": dial tcp 34.64.4.113:443: i/o timeout

求：如何处理？

**Comment by aofei** [comment]
你好，麻烦确认两点内容：

1. 你所贴的 `go env` 内容和你执行的 `go get` 等命令所处的环境一致，比如 `go env` 内容是终端环境，那么 `go get` 等命令就不能在 GoLand 等 IDE 环境中执行，因为 GoLand 之类的 IDE 会覆盖系统环境变量
2. 你执行 `go get` 等命令时所用的用户是 `aajnet`，比如你不能执行 `sudo go get`，因为 `sudo` 命令会把执行用户更换为 `root`，更换后就会采用 `root` 用户的环境变量，而你目前贴出的内容均是 `aajnet` 用户的

**Comment by hzjnet** [comment]
> 你好，麻烦确认两点内容：
> 
> 1. 你所贴的 `go env` 内容和你执行的 `go get` 等命令所处的环境一致，比如 `go env` 内容是终端环境，那么 `go get` 等命令就不能在 GoLand 等 IDE 环境中执行，因为 GoLand 之类的 IDE 会覆盖系统环境变量
> 2. 你执行 `go get` 等命令时所用的用户是 `aajnet`，比如你不能执行 `sudo go get`，因为 `sudo` 命令会把执行用户更换为 `root`，更换后就会采用 `root` 用户的环境变量，而你目前贴出的内容均是 `aajnet` 用户的

首先谢谢回复,如上1-2情况如下
1 都是在aajnet用户下命令行执行,终端环境一致，不需要其它用户或者环境
2 没有使用sudo

**Comment by aofei** [comment]
麻烦试下这条命令，看一下能否正常输出：

```bash
$ GO111MODULE=on GOPROXY=https://goproxy.cn,direct go list -m -json -versions golang.org/x/text@latest
```

**Comment by hzjnet** [comment]
> ```shell
> GO111MODULE=on GOPROXY=https://goproxy.cn,direct go list -m -json -versions golang.org/x/text@latest
> ```

GO111MODULE=on GOPROXY=https://goproxy.cn,direct go list -m -json -versions golang.org/x/text@latest
go: finding golang.org/x/text v0.3.3
{
        "Path": "golang.org/x/text",
        "Version": "v0.3.3",
        "Versions": [
                "v0.1.0",
                "v0.2.0",
                "v0.3.0",
                "v0.3.1",
                "v0.3.2",
                "v0.3.3"
        ],
        "Time": "2020-06-16T18:28:43Z"
}

**Comment by aofei** [comment]
这个输出结果表明你的网络是正常的，所以你的配置环境和执行环境可能还是有些问题。

请问你是在哪里执行什么命令时才看到的那句 `i/o timeout`？

**Comment by hzjnet** [comment]
我是编译openwrt，其中包含go语言源码的应用如：frps\v2ray\NeteaseMusic等出现该问题

**Comment by aofei** [comment]
那你需要深入挖掘一下编译过程了，看看有没有涉及环境变量的覆盖或者用户身份的切换等行为，因为你的超时结果表明了当时所用的 `GOPROXY` 环境变量并不是你所设置的。

请问你编译时有添加 `sudo` 命令吗？如果有的话，后续所有的操作都会在 `root` 用户下完成的，包括 `go get` 等。

**Comment by hzjnet** [comment]
> 那你需要深入挖掘一下编译过程了，看看有没有涉及环境变量的覆盖或者用户身份的切换等行为，因为你的超时结果表明了当时所用的 `GOPROXY` 环境变量并不是你所设置的。
> 
> 请问你编译时有添加 `sudo` 命令吗？如果有的话，后续所有的操作都会在 `root` 用户下完成的，包括 `go get` 等。

喔，谢谢！ 确定中间没有使用sudo

**Comment by aofei** [comment]
要不你换一种设置环境变量的方式吧，比如在 `.bashrc` 中添加，或者在编译命令前临时添加，记得要同时设置 `GO111MODULE=on` 和 `GOPROXY=https://goproxy.cn,direct`。

**Comment by hzjnet** [comment]
> 要不你换一种设置环境变量的方式吧，比如在 `.bashrc` 中添加，或者在编译命令前临时添加，记得要同时设置 `GO111MODULE=on` 和 `GOPROXY=https://goproxy.cn,direct`。

嗯，不过已经这样尝试过了！

**Comment by aofei** [comment]
由于问题得到了解决，所以这个 Issue 我就关闭了哈，如果还有其他问题欢迎随时提问～

**Comment by LeeYearJ** [comment]
PS E:\Go_Path\src\github.com\grafana> go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\Go_Path
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=F:\Go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=F:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Go_Path\src\github.com\grafana\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build428437666=/tmp/go-build -gno-record-gcc-switches

===设置了goproxy，但是在执行docker build -t xxx 进行到RUN go mod verify 这步报错：
go: github.com/BurntSushi/toml@v0.3.1: Get https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod: dial tcp 34.64.4.113:443: i/o timeout
==这个是因为我设置的goproxy没起作用吗？

**Comment by aofei** [comment]
@LeeYearJ 

Docker 内需要再单独设置环境变量的，请问你设置了吗？

**Comment by LeeYearJ** [comment]
在使用docker通过dockerfile创建镜像的时候也要设置环境变量吗？

**Comment by aofei** [comment]
@LeeYearJ 

是的，Docker 容器内部的环境是完全独立于宿主系统的。

**Comment by LeeYearJ** [comment]
好的，谢谢解答，我去设置下看看。

**Comment by 3481554467** [comment]
> 由于问题得到了解决，所以这个 Issue 我就关闭了哈，如果还有其他问题欢迎随时提问～

你好，我也遇到了相似的问题，即GOLAND的goproxy和用户以及root三者不一致，目前我想知道root下的goenv如何永久修改，每次的修改只能是在终端单次生效，找不到root下goenv合适的设置文件

**Comment by aofei** [comment]
> 目前我想知道root下的goenv如何永久修改，每次的修改只能是在终端单次生效，找不到root下goenv合适的设置文件

@3481554467  切换到 `root` 用户后执行 `go env -w GOPROXY=https://goproxy.cn,direct` 或者 `echo "export GOPROXY=https://goproxy.cn,direct" >> ~/.profile` 都行。

**Comment by JoyceWang-zk** [comment]
@aofei 

> 麻烦试下这条命令，看一下能否正常输出：
> 
> ```shell
> $ GO111MODULE=on GOPROXY=https://goproxy.cn,direct go list -m -json -versions golang.org/x/text@latest
> ```

@aofei 我也遇到了这个问题，试了这条命令在之后，依然是timeout.

**Comment by hahahashen** [comment]
你好，我在WSL上也遇到了这个问题
我WSL的系统是ubuntu2204
![image](https://github.com/goproxy/goproxy.cn/assets/59725322/82653465-3828-4977-a534-3d91fc8cef86)
我GO111MODULE=on GOPROXY=https://goproxy.cn,direct go list -m -json -versions golang.org/x/text@latestzhe't这条命令是可以正常输出的

**Comment by aofei** [comment]
> 你好，我在WSL上也遇到了这个问题 我WSL的系统是ubuntu2204 ![image](https://private-user-images.githubusercontent.com/59725322/321915013-82653465-3828-4977-a534-3d91fc8cef86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTAzOTAsIm5iZiI6MTcxMjkxMDA5MCwicGF0aCI6Ii81OTcyNTMyMi8zMjE5MTUwMTMtODI2NTM0NjUtMzgyOC00OTc3LWE1MzQtM2Q5MWZjOGNlZjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4MjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOWI3YzUxZWUxN2E5NWIyMjNhMGFhYzM1OGZkN2U0NDcwZWQyYjg2NDgyOWM5ZWQ2MjgyMDczZjhhYzY4ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3cw8WhvzG63HOF6puSXqjKMEk3mGg-dFmDuZrZMmIaw) 我GO111MODULE=on GOPROXY=https://goproxy.cn,direct go list -m -json -versions golang.org/x/text@latestzhe't这条命令是可以正常输出的

注意看，你少打了个 `Y`。

**Comment by zhaobaizhou** [comment]
您好，我尝试设置了 goproxy.cn，但是还是报错 timeout，请帮我看看，感谢🙏

`GO111MODULE=on GOPROXY=https://goproxy.cn,direct go list -m -json -versions golang.org/x/text@latest`
运行这个输出如下：

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/a7604941-eba0-40de-bd8b-feb84c5a581c" />

我是运行 brew upgrade hugo 的时候遇到的问题，已经试了好久，没有办法继续，错误信息如下：

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/3ade6395-9281-43cb-947e-1614026b9fee" />
