### ISSUE TITLE
问题：go get  not found: invalid mod file

### ISSUE THREAD

**Issue by ysicing** [goproxy/goproxy.cn#94]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.14.4 darwin/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

...
GOPROXY="https://goproxy.cn"
...
</pre>
</details>

## 你期望看到的结果是什么？

https://goproxy.io/github.com/kunnos/homedir/@v/v1.1.1.mod

## 你实际看到的结果是什么？

https://goproxy.cn/github.com/kunnos/homedir/@v/v1.1.1.mod

**Comment by aofei** [comment]
这是由于 [goproxy.cn](https://goproxy.cn) 目前做的是强验证，你请求的目标模块 `go.mod` 中的实际 module path 是 `github.com/mitchellh/go-homedir`，跟你请求的是有出入的，所以被判定为了无效模块。

这种强验证确实会阻碍一部分拉取，稍后我会优化一下，不过今晚才能部署更新，现在请求量太大。

感谢反馈！

**Comment by ysicing** [comment]
ok

**Comment by aofei** [comment]
已修复，已部署。

https://goproxy.cn/github.com/kunnos/homedir/@v/v1.1.1.mod
