### ISSUE TITLE
重建的repository什么时候会生效?

### ISSUE THREAD

**Issue by romberli** [goproxy/goproxy.cn#97]
我在github有一个repo, 里面有v1.0.0版本和v1.0.1版本,
后面我删除了整个repo, 使用新的代码重新创建了同名的repo, 并创建了v1.0.0版本,
现在我通过goproxy.cn拉取v1.0.0版本, 发现是老的v1.0.0而不是新代码,
我的理解是goproxy.cn把老的v1.0.0作了缓存,
我想问新的v1.0.0什么时候会生效?

**Comment by aofei** [comment]
你好，Go 模块代理存在的其中一大意义就是为了保护世界上其他依赖你的模块的项目在构建时能百分百重现。所以一旦某个模块版本被模块代理缓存住后，即使其作者在源端删除它或者篡改了它（比如 `git push --force` 等操作），被缓存的内容也不会有任何改变。所以，其作者只能选择发布新的补丁版来让其改动可见，比如你的场景下应该发个 `v1.0.1`。

**Comment by romberli** [comment]
新的v1.0.0永远都不会生效吗?

**Comment by aofei** [comment]
目前 [goproxy.cn](https://goproxy.cn) 还不存在删除缓存的策略。事实上，就算在 [goproxy.cn](https://goproxy.cn) 移除了某个特定的模块版本也于事无补，因为 Go 的校验和数据（默认 [sum.golang.org](https://sum.golang.org)）已经把它的校验和给写死了，其数据结构在设计上不可逆，所以即使拿到了新的代码也无法通过安全校验。

**Comment by aofei** [comment]
由于问题已回答，所以这个 Issue 我就先关闭了哈，如果还有其他问题欢迎随时提问～
